### ISSUE TITLE
Launching frigate-hass-card from notification on iOS

### ISSUE THREAD

**Issue by kirsch33** [dermotduffy/advanced-camera-card#1008]
This is not so much an issue or feature request (because what I'm asking for may not be possible) but theres no discussion board enabled so here we go :)

I currently have notifications working well within Home Assistant. However, when I click to view a clip (on iOS at least) it is launched in the browser as opposed to within Home Assistant.

I would love configure it to launch straight into the media gallery view of frigate-hass-card for the relevant event. Is this possible, and if so, any pointers on getting it setup?

**Comment by dermotduffy** [comment]
May I ask for an example of the URL that is in the notification?

Just a few days back I completed https://github.com/dermotduffy/frigate-hass-card/issues/929 which (from the next build) allows the card to respond to parameters passed in the URL This is not quite what you need, but it's close ...

**Comment by kirsch33** [comment]
for example, right now the action part of my notifications looks like this 
```yaml
    action:
      - condition: trigger
        id: "frigate-event"
      - delay: "00:02:15"
      - service: script.send_dynamic_notification
        data:
          id: "{{ id }}"
          message: >-
            {{ label | capitalize }} detected in the {{ after_zones[0] | replace("_", " ") | title | lower }} zone.
          notifTag: "{{ id }}"
          group: 'frigate-notification-{{ trigger.payload_json["after"]["camera"] }}'
          image: "https://hass.mydomain.net/api/frigate/notifications/{{ id }}/snapshot.jpg"
          video: "https://hass.mydomain.net/api/frigate/notifications/{{ id }}/{{ camera }}/clip.mp4"
```

but that opens in the default browser. i agree what you described is close. basically what im looking for is a URL to pass to my notification that would tell iOS/Home Assistant Companion app to open the card in the app, avoiding the browser all together.

**Comment by felipecrs** [comment]
The ability of opening within the Home Assistant Companion app has nothing to do with the Frigate Card.

The following works with Android:

```yaml
service: notify.all_mobile_devices
data:
  message: Alguém tocou o interfone, por favor atenda.
  title: Vídeo porteiro chamando
  data:
    clickAction: /lovelace/default_view
    group: video-porteiro-chamando
    tag: video-porteiro-chamando
    channel: Video Porteiro
    importance: high
    priority: high
    ttl: 0
    vibrationPattern: 1000, 100, 1000, 100, 1000, 100
    persistent: true
    timeout: 120
    visibility: public
    image: /api/camera_proxy/camera.video_porteiro
    actions:
      - action: URI
        title: Atender
        uri: /lovelace/default_view?call=888
      - action: IGNORE
        title: Ignorar
```

As you can see, you can use the `uri` to pass in URL to your dashboard and even include any parameters you want. Since the Frigate Card supports parameters for customizing its behaviors, you could use it. https://github.com/dermotduffy/frigate-hass-card/issues/929

Now, if it does not work with iOS, you should be asking the Companion guys about it.
