### ISSUE TITLE
Renewal time ignored on static image

### ISSUE THREAD

**Issue by CoMPaTech** [dermotduffy/advanced-camera-card#1064]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 5.0.0-rc1

**Last working release (if known):** 4.0.x

**Browser and Operating System:** HassOS 2023.4 and Latest Chrome on whatever (multiple OSes)

**Description of problem:**

Camera view 'continually' refreshes (i.e. live view instead of static view). This happened after the upgrade to 5 RC1 and clicking through lovelace to upgrade them all. The 'defaulted' to 10 seconds on `update_seconds` but even now on 0 (as shown below) it does not yield (it streams regardless of setting).

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.somecamera
    view:
      default: snapshot
      timeout_seconds: 30
image:
  mode: camera
view:
  default: image
  update_seconds: 0
menu:
  buttons:
    frigate:
      enabled: true
    live:
      enabled: true
    clips:
      enabled: true
    snapshots:
      enabled: true
    image:
      enabled: true
    download:
      enabled: false
    fullscreen:
      enabled: true
    camera_ui:
      enabled: false
  style: hidden
  position: right
live:
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: none
  draggable: true
  lazy_load: true
  lazy_unload: never
dimensions:
  aspect_ratio_mode: static
media_viewer:
  controls:
    next_previous:
      style: none
```

**Comment by dermotduffy** [comment]
@CoMPaTech I see some things invalid (but harmless) in that config. Can you clarify what you _want_ to happen?

**Comment by CoMPaTech** [comment]
> @CoMPaTech I see some things invalid (but harmless) in that config. Can you clarify what you _want_ to happen?

It's an older 'always upgraded' version of the card. What I expected to happen/used to work up to the upgrade:

- Card showing latest 'static' image (live, not latest snapshot)
- Maybe updating every 10 seconds, but rather just static and only refresh on page refresh.
- All the other cruft is just to map less/more icons into the view

Maybe I should start over fresh, but I might not be the only one running into the upgrade issue?

**Comment by dermotduffy** [comment]
> Maybe I should start over fresh, but I might not be the only one running into the upgrade issue?

You need this:

```yaml
image:
  mode: camera
  refresh_seconds: 0
```

The `update_seconds` controls how often the entire card re-renders, which you do not want. The image view will automatically refresh its image every 1 second (in high performance mode), or 10 seconds (in low performance mode). The above config will force it to never refresh (verified working on `v5.0.0-beta.1`).

**Comment by CoMPaTech** [comment]
I think most of the defaults came through toggling switches back and forth in the past. The `update_seconds` I already looked at and it doesn't change it for me, all camera's keep updating at approx 1fps. I did found how to restore the functionality though:

```
image:  
  mode: camera  
  refresh_seconds: 0
```

Changing the `update_seconds` doesn't yield - refresh does. So setting it to the below does still images with 10 second refreshes

```
image:  
  mode: camera  
  refresh_seconds: 0
view:  
  default: image
  update_seconds: 10
```

So it's working as intended again, feel free to close and/or should we figure something wrt why it change they way it used to work?

**Comment by dermotduffy** [comment]
> Changing the update_seconds doesn't yield - refresh does. So setting it to the below does still images with 10 second refreshes

I don't understand what you mean with "doesn't yield"? If you want the image to refresh every 10 seconds, why does this not work:

```
image:  
  mode: camera  
  refresh_seconds: 0
view:
  default: image
  [ NOTHING ELSE HERE]
```
