### ISSUE TITLE
Gallery view filter to one camera

### ISSUE THREAD

**Issue by varunpan** [dermotduffy/advanced-camera-card#1228]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Frigate Lovelace Card v5.2.0

**Last working release (if known):**

**Browser and Operating System:**
HAOS on raspi
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Description of problem:**

I added multiple camera and set my default view to clips (it applies to Clips gallery, Snapshots gallery, Records gallery, Most recent clip, Most recent snapshot, Most recent recording), however, this filters the list of clips to just the first camera that was added to the card. Based on my config below, it auto filters to the `camera_entity: camera.frontdoor_2` camera. 

This is not ideal since I can have a more recent alert.

**Frigate card diagnostic information**
See my card YAML:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.frontdoor_2
  - camera_entity: camera.front
  - camera_entity: camera.side
  - camera_entity: camera.back
  - camera_entity: camera.basement
live:
  preload: false
  draggable: false
  zoomable: false
  lazy_load: false
  show_image_during_load: false
view:
  default: clips
  dark_mode: auto
  update_cycle_camera: false
  scan:
    enabled: false
  update_force: false
menu:
  buttons:
    substreams:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    recordings:
      enabled: true
    image:
      enabled: true
    camera_ui:
      enabled: true
    expand:
      enabled: true
media_viewer:
  auto_mute: all
media_gallery:
  controls:
    filter:
      mode: right

```

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
> however, this filters the list of clips to just the first camera that was added to the card. 

Yes. This is working as intended, you can change the camera in the filter sidebar if you want? What do you want to happen?

**Comment by dermotduffy** [comment]
> Well I wanted to see all the most recent captures across all the cameras. I know I can remove the filter from the sidebar, but I have to do that everytime I load the page.

The card will combine events for cameras marked as dependencies. Try this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.frontdoor_2
    dependencies:
      all_cameras: true
  - camera_entity: camera.front
  - camera_entity: camera.side
  - camera_entity: camera.back
  - camera_entity: camera.basement
// REST OF CONFIG
```

This will make the first card depend on all the others, and should combine the events in the gallery view. Is this what you're looking for?

> I would like the have an option to remove the filter gallery.

Do you mean remote the little 'tab' on the side of the gallery? Why?
