### ISSUE TITLE
Live Stream not automatically playing

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/advanced-camera-card#127]
[Filed originally in https://github.com/blakeblackshear/frigate-hass-integration/issues/154 by @thundergreen ]

## Version of the custom_component

2.1.0
## Configuration

```yaml

- type: custom:swipe-card
  cards:
      - type: custom:frigate-card
        camera_entity: camera.front_door
        view_default: live
#        live_provider: frigate
        autoplay_clip: true
        dimensions:
          aspect_ratio_mode: static
        controls: {}
        menu_mode: overlay-right
#        webrtc: {}
        elements:
          - type: custom:frigate-card-menu-state-icon
            entity: script.preset_garage
            tap_action:
              action: toggle
          - type: custom:frigate-card-menu-state-icon
            entity: script.preset_street
            tap_action:
              action: toggle
          - type: custom:frigate-card-menu-state-icon
            entity: script.preset_maindoor
            tap_action:
              action: toggle
        #   - type: state-badge
        #     entity: sensor.date_time
        #     style:
        #       right: '52px'
        #       top: '80px'
        # #      color: rgba(0,0,0,0)
        #       opacity: 1.0

      - type: custom:frigate-card
        camera_entity: camera.garden
        view_default: live
        # live_provider: frigate-jsmpeg
        autoplay_clip: true
        dimensions:
          aspect_ratio_mode: static
        controls: {}
        menu_mode: overlay-right
#        webrtc: {}
        elements:
          - type: conditional
            conditions:
              - entity: light.garden
                state: 'on'
            elements:
              - type: custom:frigate-card-menu-state-icon
                entity: light.garden
                tap_action:
                  action: toggle

      - type: custom:frigate-card
        camera_entity: camera.garden_upstairs_2
        view_default: live
        # live_provider: frigate-jsmpeg
        autoplay_clip: true
        dimensions:
          aspect_ratio_mode: static
        controls: {}
        menu_mode: overlay-right
 #       webrtc: {}

```

## Describe the bug

Livestream not starting itself. When I click on clips or snapshots and after on live stream, then stream starts running.

## Debug log

```text

Nothing in logs
```
