### ISSUE TITLE
Custom menu elements lost on certain re-renders

### ISSUE THREAD

**Issue by thundergreen** [dermotduffy/advanced-camera-card#139]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.2.1
**Last working release (if known):**

**Browser and Operating System:**
Microsoft Edge / Chrome

**Description of problem:**
When adding elements to the card like scripts etc They wont be shown. Sometimes it shows but sometimes not.

**Javascript errors shown in the web inspector (if applicable):**

```
nothing in console
```

**Additional information:**
here my card config:

```
## Created by Thorsten Fröhlich
## More-page add-on: Camera
## Version: 1.0.0
- type: custom:swipe-card
  cards:
    - type: custom:frigate-card
      camera_entity: camera.front_door
      view_default: live
      live_preload: true
      #        live_provider: frigate
      autoplay_clip: true
      dimensions:
        aspect_ratio_mode: static
      controls: {}
      menu_mode: hidden-right
      #        webrtc: {}
      elements:
        - type: custom:frigate-card-menu-state-icon
          entity: script.restart_foscam
          tap_action:
            action: toggle
        - type: custom:frigate-card-menu-state-icon
          entity: script.preset_garage
          tap_action:
            action: toggle
        - type: custom:frigate-card-menu-state-icon
          entity: script.preset_street
          tap_action:
            action: toggle
        - type: custom:frigate-card-menu-state-icon
          entity: script.preset_maindoor
          tap_action:
            action: toggle
      #   - type: state-badge
      #     entity: sensor.date_time
      #     style:
      #       right: '52px'
      #       top: '80px'
      # #      color: rgba(0,0,0,0)
      #       opacity: 1.0

    - type: custom:frigate-card
      camera_entity: camera.garden
      view_default: live
      # live_provider: frigate-jsmpeg
      autoplay_clip: true
      live_preload: true
      dimensions:
        aspect_ratio_mode: static
      controls: {}
      menu_mode: overlay-right
      #        webrtc: {}
      elements:
        - type: conditional
          conditions:
            - entity: light.garden
              state: "on"
          elements:
            - type: custom:frigate-card-menu-state-icon
              entity: light.garden
              tap_action:
                action: toggle

    - type: custom:frigate-card
      camera_entity: camera.garden_upstairs_2
      view_default: live
      live_preload: true
      # live_provider: frigate-jsmpeg
      autoplay_clip: true
      dimensions:
        aspect_ratio_mode: static
      controls: {}
      menu_mode: overlay-right
    #       webrtc: {}

    - type: custom:frigate-card
      camera_entity: camera.garage
      view_default: live
      # live_provider: frigate-jsmpeg
      autoplay_clip: true
      live_preload: true
      dimensions:
        aspect_ratio_mode: static
      controls: {}
      menu_mode: overlay-right
      #        webrtc: {}
      elements:
        - type: custom:frigate-card-menu-state-icon
          entity: light.garage
          tap_action:
            action: toggle
        # - type: conditional
        #   conditions:
        #     - entity: light.garage
        #       state: 'on'
        #   elements:
        #     - type: custom:frigate-card-menu-state-icon
        #       entity: light.garage
        #       tap_action:
        #         action: toggle

```

![image](https://user-images.githubusercontent.com/13320319/137802747-f1c0d714-e857-4be3-a901-c65a09b16f5e.png)

More info: When the page loads I can see super shortly the icons but they disappear directly after finished loading
