### ISSUE TITLE
Birdseye view works only using local url

### ISSUE THREAD

**Issue by freddyf** [dermotduffy/advanced-camera-card#154]
I can’t make birdseye view working if i use my remote url (https://homeassistant.xxxxxx.duckdns.org/lovelace/home) but it works perfect if i use my lan IP (http://10.0.0.5:8123/lovelace/home)
this is the error (400 Bad Request)

![immagine](https://user-images.githubusercontent.com/1830630/139093920-b57d1977-ca24-4629-b2dc-aa7e4db9e19e.png)

HomeAssistant: core-2021.10.6
Frigate Integration: v2.1.0
Frigate Card: v1.2.1

Frigate: 0.9.2-25bb515

Frigate is on different server than Home Assistant.

All applications are on docker. I use swag for manage remote access and certificate

this my card:
```
type: custom:frigate-card
frigate_camera_name: birdseye
live_provider: frigate-jsmpeg
view_default: live
dimensions: {}
controls: {}
menu_buttons:
  fullscreen: true
  live: false
  snapshots: false
  clips: false
  frigate: false
  frigate_ui: false
menu_mode: overlay-top
webrtc: {}
```

Thank you
