### ISSUE TITLE
Constrain the view port (only) to a fixed aspect ratio 

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/advanced-camera-card#1581]
**Is your feature request related to a problem? Please describe.**

In 5.2.0 I was able to constrain the view port to 16:9 with:

```yaml
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```

But the same configuration now will constrain the whole card, including the external menu, to 16:9.

Instead of:

![image](https://github.com/user-attachments/assets/00c4d0c9-b2cd-4531-a81b-4cb46f9dadf6)

It now looks like:

![image](https://github.com/user-attachments/assets/4dd11bd5-11fa-4036-b7d3-a4ae0ba4b80a)

Which is not optimal, as it is very hard to predict the card aspect ratio when taking into consideration the menu.

The reason why I want to constrain the card is to make the dashboard loading look a bit better. For example, the following:

![image](https://github.com/user-attachments/assets/bbe6a86a-328c-48ee-ab5b-5b02e5865f99)

In favor of:

![image](https://github.com/user-attachments/assets/3ee3ccd3-f150-46c9-b83a-1a69867eb992)

**Describe the solution you'd like**

Perhaps...

```yaml
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
  aspect_ratio_view_port_only: true
```

Or maybe just make it the default with no ability to configure? I wonder if there is a use case to constrain the card _beyond_ the view port.

**Describe alternatives you've considered**
I was playing with the camera dimensions configuration, but that doesn't seem to have the effect I wanted.

**Additional context**

- Related to https://github.com/dermotduffy/frigate-hass-card/issues/1369
- Related to https://github.com/dermotduffy/frigate-hass-card/pull/1394

**Comment by dermotduffy** [comment]
I think you want to set the _camera_ aspect-ratio, but not the card, with this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    dimensions:
      aspect_ratio: '4:3'
# Not this, as this sets it for the whole card
# dimensions:
#   aspect_ratio: '4:3'
menu:
  style: outside
```
