### ISSUE TITLE
MSE not working anymore

### ISSUE THREAD

**Issue by Tibladar** [dermotduffy/advanced-camera-card#1711]
**Card diagnostic information:**

<details><summary>First instance</summary>

```yaml
card_version: 6.0.0-beta.9
browser: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
date: 2024-12-08T12:20:13.981Z
lang: de
git:
  hash: b2b7a08
  build_date: Wed, 04 Dec 2024 04:35:32 GMT
  commit_date: Tue, 3 Dec 2024 20:26:56 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      ea6e96948ede12da875101e6804b6754: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.backyard
  live:
    show_image_during_load: false
```

</details>

<details><summary>Second instance</summary>

```yaml
card_version: 6.0.0-beta.9
browser: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
date: 2024-12-08T12:22:15.050Z
lang: de
git:
  hash: b2b7a08
  build_date: Wed, 04 Dec 2024 04:35:32 GMT
  commit_date: Tue, 3 Dec 2024 20:26:56 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      35c891929a742101f4a93682e43d598c: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.backyard
    - camera_entity: camera.cars
    - camera_entity: camera.garden
    - camera_entity: camera.garden_2
    - frigate:
        camera_name: birdseye
      dependencies:
        all_cameras: true
  menu:
    buttons:
      snapshots:
        enabled: false
      display_mode:
        enabled: false
    style: overlay
  live:
    controls: {}
  status_bar:
    style: none
```

</details>

**Description of problem:**
On two HA+Frigate instances the card will only use mjpeg for displaying the cameras, not MSE/HLS anymore.
MSE directly on the Frigate website and HLS from hass-integration work fine.

All cameras (Reolink+TP-Link) are non-PTZ and frigate displays the following error when opening the hass-card, one for each camera:
```
Type: error
Timestamp: 2024-12-08 13:05:40
Tag: frigate.ptz.onvif
Message: Onvif is not setup for Backyard
```
This error is **NOT** shown when viewing via sensor "Backyard Recording" (HLS) or Frigate UI (MSE)

When adding `show_image_during_load: false` to the card, no image/video is shown and the JS console displays an error:
```text
Uncaught (in promise) Object { code: "not_found", message: "Subscription not found." }
 FRIGATE-HASS-CARD 
 Version 6.0.0-beta.9
```

According the network analysis in the console the card doesn't seem to attempt a MSE/HLS connection.

When clicking on the hass-integration sensor "Backyard Recording" on the HASS devices page the video is played fine via HLS `/api/hls/*/playlist.m3u8?_HLS_msn=`

`about:webrtc` shows no active connection when "Use Frigate-native WebRTC support" is disabled.
When enabled it fails (probably since I haven't configured webrtc)
![grafik](https://github.com/user-attachments/assets/2069f38d-ed9d-4c4c-834f-55d8f2e5a0c5)

Tested everything from local network
Frigate and HASS are on the same device
HASS Core + Frigate Docker

**Last working release:**
Home Assistant 2024.10.4 with card 5.2.0 and integration 5.4.0

**Comment by dermotduffy** [comment]
Perhaps you can clarify the goal, are you specifically trying to get `mse` working, or are you just saying video streams in general do not work.

If you want to use `mse`, you need to ask for it, e.g.:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.backyard
    live_provider: go2rtc
    modes:
      - mse
```
