### ISSUE TITLE
Auto-reload/retry when server is down

### ISSUE THREAD

**Issue by snoack** [dermotduffy/advanced-camera-card#1830]
Whenever I have to restart the Frigate server, all my various devices showing camera feeds in Home Assistant using Frigate card get stuck with a failed server connection, and I have to go around, manually refreshing the page / restarting the companion app.

It would be nice if the Frigate card would periodically attempt to reconnect after a failed connection in order to automatically recover from a server down scenario.

**Comment by Sarah-Connelli** [comment]
Strange, mine does recover, I'm often tweaking things in Frigate and stopping/starting the docker container for Frigate.

So if I stop Frigate, all the frigate-hass-cards then say "Camera unavailable: <cameraname>" on the display, and then when I restart Frigate, all the frigate-hass-card's return back to normal. No refresh needed, nothing.

This is on Chromium, Edge desktop browsers and the latest Home Assistant app on Android, I am using the frigate-hass-card v6.3.3 with latest stable Frigate and HA.

**Comment by dermotduffy** [comment]
+1, it should automatically recover from both the loss of a camera, and indeed loss of Home Assistant itself. @snoack Can you record a video of what you're seeing?

**Comment by snoack** [comment]
After some further testing, I can confirm that it only happens on Chrome and the HA companion app on Android (not on Firefox), and only when using following settings:

```yaml
live_provider: go2rtc
go2rtc:
  modes:
    - webrtc
```

In that scenario, the card remains black when restarting the Docker container running Frigate (and go2rtc). If I don't set `live_provider` or use Firefox then it seems to recover from the lost server connection.

**Comment by dominikandreas** [comment]
Same problem here, live view often gets "stuck" and does not recover unless you navigate somewhere else and back in home assistant. Not using any custom settings, just displaying a camera entity leaving everything else at default. This is probably caused by interruptions in the camera stream, but having an option to reload the card when no data is received after x seconds would be nice.

**Comment by felipecrs** [comment]
If you are using the Frigate integration, try with this option in the camera in the card:

```yaml
always_error_if_entity_unavailable: true
```

**Comment by teji24** [comment]
same problem. HA andoid app stay on fullscreen card, on birdeye. when frigate crash (3 times a day) and auto-restart, card stay on stopped birdeye view (time of crash). i dream about auto retry/reload...

**Comment by NicusorFlorinBaluta** [comment]
same issue here, any fix on the horizon? 🤞

**Comment by dermotduffy** [comment]
@NicusorFlorinBaluta @teji24 Mind sharing your configs? If you can give me exact reproduction instructions, e.g. "When I use config X, and then restart Frigate, the card will always stay stuck on an error, and here's a screenshot" that would be super helpful!

**Comment by NicusorFlorinBaluta** [comment]
<img width="1032" height="190" alt="Image" src="https://github.com/user-attachments/assets/d253d11f-4001-4ad9-a1c0-19e191fe1092" />

Setup:
HA running in docker container - any version, been happening for months now
Frigate running in separate docker container - any version, been happening for months now

Frigate Config:
```
mqtt:
  host: homeassistant.local
  user: homeassistant
  password: my-password

database:
  path: /config/frigate.db

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p    # better compatibility than 'vaapi'

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 15
    mode: motion
  alerts:
    retain:
      days: 15
  detections:
    retain:
      days: 15

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  # streams:
  #   outdoor_camera:
  #     - rtsp://my-camera-path/Streaming/Channels/101/
  webrtc:
    candidates:
      - my-camera-path:8555
      - stun:8555

detect:
  fps: 6

cameras:
  outdoor_camera:
    ffmpeg:
      inputs:
        - path: rtsp://my-camera-path/Streaming/Channels/102/
          # - path: rtsp://my-camera-path/Streaming/Channels/102/ low quality channel disabled since switching to Ubuntu PC
          # Remove other input_args like preset-rtsp-generic for this specific test if you added them
          input_args: # Using a list format for input_args
            - -analyzeduration # Analyze a decent portion of the stream
            - 2M               # 2 Megabytes, or try '2000000' (2 seconds for typical streams)
            - -probesize       # Probe a decent amount of data
            - 2M               # 2 Megabytes, or try '2000000'
            - -fflags
            - nobuffer          # Try to reduce latency
            - -flags
            - low_delay         # Try to reduce latency
            - -rtsp_transport   # Force RTSP transport protocol
            - tcp               # Use TCP
          roles:
            - detect
        - path: rtsp://my-camera-path/Streaming/Channels/101/
          input_args: preset-rtsp-restream # This preset is good for recording
            # You can also try adding -rtsp_transport tcp here if the preset alone isn't enough
            # For example, if preset-rtsp-restream already includes some args, you might need to find a generic preset
            # or list all args. For now, let's assume preset-rtsp-restream tries TCP.
            # If issues persist with this stream, consider adding:
            # - -rtsp_transport
            # - tcp
          roles:
            - audio
            - record
    motion:
      mask:
        - 0,0.174,0.002,0,0.999,0,0.999,0.781,0.903,0.597,0.845,0.564,0.697,0.429,0.542,0.387,0.498,0.38,0.452,0.348,0.374,0.36,0.174,0.285,0.042,0.251,0.017,0.247
        - 0.017,0.249,0.012,0.421,0.088,0.421,0.054,0.256
        - 0.004,0.612,0.001,1,0.827,0.996,0.503,0.687,0.182,0.657,0.121,0.645
      threshold: 10
      contour_area: 20
      improve_contrast: true
      lightning_threshold: 0.8
    objects:
      mask: 
        0,0.179,0.017,0.245,0.16,0.283,0.368,0.359,0.449,0.352,0.502,0.39,0.694,0.429,0.839,0.569,0.899,0.6,1,0.781,1,0,0.001,0.003,0,0.047
      filters:
        car:
          mask: 0.184,0.311,0.188,0.408,0.287,0.381,0.281,0.304
version: 0.15-1

#logger:
  # Optional: default log level (default: shown below)
#  default: debug
  # Optional: module by module log level configuration
#  logs:
#    watchdog.outdoor_camera: debug
#    ffmpeg.outdoor_camera: debug
auth:
  enabled: false
semantic_search:
  enabled: true
  reindex: true
  model_size: large

```

Advanced camera card config:
```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.my_camera_entity
view:
  default: live
grid_options:
  columns: full
```

Steps:
1. Have Dashboard open on an android device in browser
2. Restart HA
3. Observe camera card not rendering camera 

Repro rate: 90%
