### ISSUE TITLE
Reolink Audio Working in Desktop Browser but not IOS Mobile App/Browsers

### ISSUE THREAD

**Issue by joehoman** [dermotduffy/advanced-camera-card#1834]
I have HA and frigate running on docker with nginx reverse proxy forwarding traffic to them over https. Frigate card and frigate installed from HACS.

I have a Reolink Video Doorbell Wifi and Reolink Duo 2 Wifi.

Two way audio works correctly on frigate itself on macos firefox. The  HA frigate card two way audio works correctly with some delay in chrome on macos desktop, but the microphone and mute button do not appear in the card on macos firefox, ios homeassistant app, ios safari, or ios chrome.

I tried switching audio from opus to aac as described here with no success. That broke both desktop chrome as well as everything else.
https://github.com/blakeblackshear/frigate/discussions/12716

# card info

## doorbell card
```
card_version: 6.3.3
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101
  Firefox/134.0
date: 2025-01-18T15:51:25.548Z
lang: en
timezone: 
git:
  hash: 6b3736b
  build_date: Mon, 13 Jan 2025 00:27:45 GMT
  commit_date: Sun, 12 Jan 2025 16:26:30 -0800
ha_version: 2025.1.2
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JHKT9MP4B37NS336PWZVJ1R2: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.reolink_doorbell
      go2rtc:
        modes:
          - webrtc
      live_provider: go2rtc
  menu:
    buttons:
      microphone:
        enabled: true
        alignment: opposing
        type: momentary
        priority: 100
      mute:
        enabled: true
        permanent: true
        alignment: opposing
        priority: 100
    style: outside
  grid_options:
    columns: 12
    rows: 8
  media_viewer:
    auto_play:
      - selected
```
## garage card 
```
card_version: 6.3.3
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101
  Firefox/134.0
date: 2025-01-18T15:53:42.665Z
lang: en
timezone: 
git:
  hash: 6b3736b
  build_date: Mon, 13 Jan 2025 00:27:45 GMT
  commit_date: Sun, 12 Jan 2025 16:26:30 -0800
ha_version: 2025.1.2
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JHKT9MP4B37NS336PWZVJ1R2: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  media: video, audio, microphone
  cameras:
    - camera_entity: camera.reolink_garage
      go2rtc:
        modes:
          - webrtc
      live_provider: go2rtc
  menu:
    buttons:
      microphone:
        enabled: true
        alignment: opposing
        type: toggle
      mute:
        enabled: true
        permanent: true
        alignment: opposing
    style: outside
  grid_options:
    columns: 24
    rows: 5
```

# frigate config
```
tls:
  enabled: false
mqtt:
  host: 192.168.50.51
  port: 1883
  user: user
  password: pass
go2rtc:
  streams:
    reolink_doorbell:
      - rtsp://user:pass@192.168.50.53:554/Preview_01_main
      - ffmpeg:reolink_doorbell#audio=opus#audio=volume
    reolink_garage:
      - rtsp://user:pass@192.168.50.54:554/Preview_01_sub
      - ffmpeg:reolink_garage#audio=opus#audio=volume
  webrtc:
    candidates:
      - http://192.168.50.51:8555
      - stun:8555
  ffmpeg:
    volume: -af "volume=30dB"
cameras:
  reolink_doorbell:
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          roles:
            - audio
            - detect
  reolink_garage:
    audio:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_garage
          roles:
           - audio
           - detect
version: 0.14
```

# go2rtc info 

## doorbell card
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.50.53/Preview_01_main/",
      "remote_addr": "192.168.50.53:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1737153484127509 1 IN IP4 192.168.50.53\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=27010372, senders=2",
        "97 MPEG4-GENERIC/16000, bytes=201314, senders=2"
      ],
      "recv": 27454386
    },
    {
      "url": "ffmpeg:reolink_doorbell#audio=opus#audio=volume"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/reolink_doorbell",
      "remote_addr": "127.0.0.1:52612",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=27010372, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=201314, receivers=1"
      ],
      "send": 27527926
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/reolink_doorbell",
      "remote_addr": "127.0.0.1:52604",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=27010372, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=201314, receivers=1"
      ],
      "send": 27527926
    }
  ]
}

```
## garage card
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.50.54/Preview_01_sub/",
      "remote_addr": "192.168.50.54:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1737138406954145 1 IN IP4 192.168.50.54\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKBgBJk=,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=12201076, senders=2",
        "97 MPEG4-GENERIC/16000, bytes=787932, senders=2"
      ],
      "recv": 13117912
    },
    {
      "url": "ffmpeg:reolink_garage#audio=opus#audio=volume"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/reolink_garage",
      "remote_addr": "127.0.0.1:52620",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKBgBJk=,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=12201076, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=787932, receivers=1"
      ],
      "send": 13158192
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/reolink_garage",
      "remote_addr": "127.0.0.1:52608",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKBgBJk=,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=12201076, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=787932, receivers=1"
      ],
      "send": 13158192
    }
  ]
}

```
