### ISSUE TITLE
Live stream freezes frequently

### ISSUE THREAD

**Issue by jjb2016** [dermotduffy/advanced-camera-card#1861]
Hello all - I have recently started using the Frigate Card in Home Assistant for the first time.  I have Home Assistant running on a RPi5 and Frigate running on a different machine as a Docker container.  I have two cameras setup and running.  In HA I've created two Frigate cards, one for each camera.  When I first open the dashboard with these cards the live streams start OK, but if I switch one feed to full screen and then go out of full screen then the live streams hang.  Not sure if it has anything to do with switch in/out of full screen mode ... or it's caused by something completely different.  However, in the HA logs I see these log error entries ...

```
Logger: frontend.js.modern.202501092
Source: components/system_log/__init__.py:331
First occurred: 18:03:50 (20 occurrences)
Last logged: 18:07:49

Uncaught error from Firefox 134.0 on Linux x86_64 RangeError: source array is too long onmse/this.onmessage.mse/this.ondata (/hacsfiles/frigate-hass-card/index-d1b21874.js:1:6208) onopen/< (/hacsfiles/frigate-hass-card/index-d1b21874.js:1:4286)
```
Anybody know what could be causing this behaviour and associated error messages?

Added info:
In Frigate, both cameras are defined for 1920x1080 30fps live streams.
Both the HA RPi5 and the machine running Frigate are connected to good stable gigabit LAN.
When viewing the HA dashboard with both Frigate cards live streaming I'm seeing network usage on the RPi5 of rx: 8.4MiB/s and tx: 10MiB/s.
I thought perhaps the issue was due to the 2k resolution I'm streaming at, but the issue seems quite intermittent and thought I'd try here for an expert opinion.

**Comment by dermotduffy** [comment]
Can you provide the [diagnostics](https://card.camera/#/support?id=diagnostics-missing-in-issue) from the card so we can see your config & versions?

Have you tried other devices? Is it always related to fullscreen? I'd also recommend other [live providers](https://card.camera/#/configuration/cameras/live-provider?id=overview) to see if the results are any different (e.g. for Frigate cameras I find the `go2tc` provider very stable).

> Uncaught error from Firefox 134.0 on Linux x86_64 RangeError: source array is too long onmse/this.onmessage.mse/this.ondata (/hacsfiles/frigate-hass-card/index-d1b21874.js:1:6208) onopen/< (/hacsfiles/frigate-hass-card/index-d1b21874.js:1:4286)

Haven't seen that before, but yes potentially related if the issue is occurring with an MSE stream.

**Comment by jjb2016** [comment]
Hi Dermot, 
Thanks for responding!  Here's one of the cards configs (the one that seems to freeze most often) ...
```
card_version: 6.4.0
browser: Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0
date: 2025-01-30T19:22:00.106Z
lang: en_GB
timezone: Europe/London
git:
  hash: 3e8e688
  build_date: Mon, 27 Jan 2025 15:24:21 GMT
  commit_date: Mon, 27 Jan 2025 07:23:07 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JH3EJQ935GGGGTBNT1K7HJD1: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.office_camera1
      go2rtc:
        modes:
          - webrtc
          - mse
        stream: office_camera1
      dimensions:
        layout: {}
      live_provider: go2rtc
      frigate: {}
      title: House Front
  view:
    default: live
    camera_select: live
    theme:
      themes: []
  menu:
    style: hover-card
    position: top
  profiles: []
  status_bar: {}
  dimensions: {}
  live:
    lazy_load: false
    preload: true
```
Have I tried other devices : yes, I get the same issue when viewing the camera feeds in the Home Assistant companion app on my phone.
I am already using the go2rtc live provider, as I have found (by much trial and error) that it is the most stable.
Since my original message I've been doing a bit more testing and I'm convinced that I'm seeing a big increase in network bandwidth usage at night when it's dark .... does this sound crazy?  Throughout today, and into this evening, I've been monitoring the network bandwidth usage in htop on the RPi5 running HA.  During the day both camera feeds, running at 1920x1080 30fps, are rock solid when viewed in the HA frigate card (on the RPi5) and also in the Frigate webapp (running on a different machine).  Network bandwidth on the HA RPi5 is around 2 - 3MiB/s.  However at night it increases to anywhere between 8 - 12MiB/s. I don't understand how/why a video stream bandwidth can increase like this in different lighting conditions, assuming the framerate stays constant.  But this is a bit beyond my knowledge of how ffmpeg and video encoding/decoding works.

The issue I raised here with the Frigate Card may not even be an issue with the card itself, although it would be useful to know what could have caused the error message I originally posted.  If you have any suggestions for how I could configure the card that would be much appreciated.  I'm using go2rtc in my Frigate config.
