### ISSUE TITLE
Reolink: Clips gallery and timeline show no media

### ISSUE THREAD

**Issue by ecdlguy** [dermotduffy/advanced-camera-card#1870]
**Checklist:**

-  Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases). **Done**
- Please try clearing your browser cache. **Done**

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.5.1
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/132.0.0.0 Safari/537.36
date: 2025-02-03T16:46:44.380Z
lang: en
timezone: Europe/Berlin
git:
  hash: 43947b4
  build_date: Sun, 02 Feb 2025 00:09:40 GMT
  commit_date: Sat, 1 Feb 2025 16:08:32 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - live_provider: auto
      reolink:
        url: https://192.168.7.56
      camera_entity: camera.cx410_fliessend
  status_bar:
    style: outside
```

**[REQUIRED] Description of problem:**
Clips gallery says "Waiting for media to load..." and finally "No media to display".
However, in HA under "Media Sources" I can see the Reolink Integration with the camera listed.
When clicking on it, there are two folders, "Low resolution" and "High resolution".
Both contain folders for each day and each day has subfolders for every event containing the recorded clip stored on the SD card of the camera. I can play them fine directly out of HA.
I don't know how to debug further, please advice / guide me.

cheers, Thorsten

Edit: Here is some logging information from the browser console:

```

[log.log](https://github.com/user-attachments/files/18646205/log.log)

connection-mixin.ts:180 Sending {type: 'media_source/browse_media', media_content_id: 'media-source://reolink'}id: 1111media_content_id: "media-source://reolink"type: "media_source/browse_media"[[Prototype]]: Object
connection-mixin.ts:188 Received {title: 'Reolink', media_class: 'app', media_content_type: '', media_content_id: 'media-source://reolink', children_media_class: 'channel', …}
connection-mixin.ts:180 Sending {type: 'media_source/browse_media', media_content_id: 'media-source://reolink/RES|87b98e1046534254cdb28ff6cf3e3ace|0|sub'}id: 1112media_content_id: "media-source://reolink/RES|87b98e1046534254cdb28ff6cf3e3ace|0|sub"type: "media_source/browse_media"[[Prototype]]: Object
connection-mixin.ts:188 Received {title: 'CX410 Low res.', media_class: 'channel', media_content_type: 'playlist', media_content_id: 'media-source://reolink/DAYS|87b98e1046534254cdb28ff6cf3e3ace|0|sub', children_media_class: 'directory', …}
connection-mixin.ts:180 Sending {type: 'media_source/browse_media', media_content_id: 'media-source://reolink/DAY|87b98e1046534254cdb28ff6cf3e3ace|0|sub|2025|2|3'}
connection-mixin.ts:188 Received {title: 'CX410 Low res. 2025/2/3', media_class: 'channel', media_content_type: 'playlist', media_content_id: 'media-source://reolink/FILES|87b98e1046534254cdb28ff6cf3e3ace|0|sub', children_media_class: 'video', …}
```
It's just a snippet, I've left out older days. I've attached the json of the last response.

[log.txt](https://github.com/user-attachments/files/18646216/log.txt)

**Comment by dermotduffy** [comment]
Let me start with: This functionality is fairly new, I have only a single Reolink camera, and this is the first issue report I can ever recall on reolink media. As such, either it works perfectly for everyone else (extremely unlikely) or you're the guinea pig here running into the early issues. These kind of things may take a bit of iteration, so thank you in advance for your patience.

Would it be possible for you to open the Media sidebar in HA, take a screenshot of what you see, drill down into "Reolink" (take a screenshot), then into resolutions (take a screenshot), then into a particular day (take a screenshot), until you reach rock bottom? That might save some iterations, as I can work through what the card might be seeing in your setup.

I can already see at least one problem, the card is expecting media to be a timestamp followed by a duration, but your media items have another parameter, in this case "Person": `08:00:18 0:00:27 Person`. Do you know what provides that? Is this something you have configured, or you have it stock? I could have the card either ignore it, or I could have it associate a label of "person" when it sees that third term (is the third term always a label like this?).

Another potential issues, the card expects folders with days to be called (e.g.) `2025/2/3` but it looks like you might have the camera title in front of that, e.g. `CX410 Low res. 2025/2/3'. Was that out of the box, or did you somehow configure it to be like that, or am I misunderstanding?

**Comment by ecdlguy** [comment]
Thank you for looking into this! Pleas find the screenshots below.

I've configured the camera to only record events of the type "person" and "vehicle" to save space on the SD card. Maybe no labels are added if recording 24/7. In the last screenshot, there is also an event with both labels. In my case every recording has a label attached. I assume (have not tested it) that if I also enable recording in case of a pet detection, there would be a corresponding label. 

It would be great if you could add the label to the clips and/or even provide an option to filter for that.

Regarding the formatting of the days, as far as I remember I did not configure anything to have this. A few month ago I had a second Reolink connected, maybe the Reolink integration adds this for clearness?


![Image](https://github.com/user-attachments/assets/d840d62e-4798-44d3-909e-f313b77a47e2)
![Image](https://github.com/user-attachments/assets/8859d472-08c8-4483-90bd-427780fd03c7)
![Image](https://github.com/user-attachments/assets/eb19e269-f350-4890-b82a-9497797e6c2b)
![Image](https://github.com/user-attachments/assets/31d2dbca-432e-4ee6-a08f-3843be45909e)
![Image](https://github.com/user-attachments/assets/6f722406-03c9-498a-94c5-bf63d37c96c9)

**Comment by dermotduffy** [comment]
@sherryxiao1988 No, if you have the same issue as the original poster, you need to wait for the issue to be fixed I'm afraid. I think I have what I need here, just didn't get around to it yet.

**Comment by sherryxiao1988** [comment]
@dermotduffy Thanks for the quick reply! Also thank you for making and maintaining such a wonderful repo!

**Comment by sherryxiao1988** [comment]
@dermotduffy Created the issue here: https://github.com/dermotduffy/advanced-camera-card/issues/1899

Thank you!

**Comment by ecdlguy** [comment]
@dermotduffy Thank you, I just found some time to test it and it is working great for me!

Two things came up to my mind:
1. It would be great if there was an option to filter for specific events based on the labels (like e.g "person" or "vehicle") in the clips or timeline view.
2. The clips and timeline view is missing thumbnails:

![Image](https://github.com/user-attachments/assets/de6ee625-860c-4a06-88b4-2f32d34affd0)

![Image](https://github.com/user-attachments/assets/3bbecc99-f2a3-4dea-97ec-a53b9ef8e52a)

 
Like pointed out [here](https://github.com/dermotduffy/advanced-camera-card/issues/1903#issuecomment-2666430537), it seems like the Reolink integration is not able to provide these due to lacking support of Reolink's API. However, I already do the following:
1. If the Reolink integration receives an AI motion detection event (like "person detected"), I fetch an image snapshot of the current camera's live stream
2. This image is send to an intance of [doods2](https://github.com/snowzach/doods2) (see also [here](https://www.home-assistant.io/integrations/doods/)).
3. Doods detects the person and provides a bounding box around the detected person.
4. Using the bounding box, the image from step a) is cropped and saved in a HA media folder.

I use this image as a notification thumbnail when sending a notification to my android phone.
So, since I already have a snapshot image for all clips stored in HA media folder, it would be great to use these images as thumbnails in the clips and timeline view.

I've [seen](https://github.com/dermotduffy/advanced-camera-card/issues/1748) that there are plans for a general HA media folder integration, however I feel unsure about if that would bring thumbnails to the Reolink clips.

cheers, Thorsten

**Comment by dermotduffy** [comment]
It's works, a miracle!

> It would be great if there was an option to filter for specific events based on the labels (like e.g "person" or "vehicle") in the clips or timeline view.

I looked into this. The issue is that fetching from Reolink cameras is _slow_. The only way to know the filter "options" would be to recurse the entire camera looking for these tags, as there's no way I know of to simply ask "Tell me the tags you know about". This would be incredibly slow. This leaves two options:

 - Hardcode labels we want to show up in the filter (e.g. via a new configuration option we'd pass to the camera)
 - [Maybe] Only allow filtering _within_ media already fetched, e.g. you have the way it works now, and if there are tags detected in the media, the media filter box would show you those tags. It would never show you tags it has not fetched the media for, so you might have a `zebra` tag yesterday, but the filter box wouldn't show you that (yet) since you only searched today. No configuration required, but "partial results".

Thoughts?

> however I feel unsure about if that would bring thumbnails to the Reolink clips.

It would not. That feature is all about exposing your _existing_ HA media folders to the card. If they already have thumbnails, it would work. In this case, if I'm reading it right, you also have no way of associating the saved image with the media, so this would not work for you.

Maybe there's some heuristic that could be applied here, e.g. if a non-image media is found in a folder with name X, and there's an image media in the same folder, with the same name (but ending in an image extension), use that as the thumbnail. Something like this might be possible as a later revision on the "folder" proposal you link to. I think this is also what @barbierp35 was looking for. Could something like this work for you?

I'll warn you that development on this card is [slow](https://github.com/dermotduffy/advanced-camera-card/issues/1248), so and this is several steps down the line...

**Comment by ecdlguy** [comment]
> It's works, a miracle!

I had no doubts :) 
However, meanwhile I had the following issues but I don't think they're related to advanced-camera-card:

1. Sometimes there's a "Seek time not found" error, cf. screenshot below. The clip plays fine in the background though and also without any error in the HA media browser.

![Image](https://github.com/user-attachments/assets/5d8126c0-d16c-4242-bc11-568bd85676f7)

2. I cannot seek in the clips (but this also doesn't work in the HA media browser)

> Thoughts?

Both options would be ok for me. If we go with the second approach, any changes to the labels (e.g due to a camera firmware update) would not break anything.

Regarding the thumbnails, am I right in my understanding that you rely on the thumbnails provided by the HA media source? If you have control over the thumbnail being displayed for each clip, these could simply be loaded from a folder using the heuristic you've described. 

I was also thinking about if it would be possible to "inject" my own thumbnails into the media source provided by the HA Reolink integration. Do you know if this is feasible?

**Comment by barbierp35** [comment]
> Maybe there's some heuristic that could be applied here, e.g. if a non-image media is found in a folder with name X, and there's an image media in the same folder, with the same name (but ending in an image extension), use that as the thumbnail. Something like this might be possible as a later revision on the "folder" proposal you link to. I think this is also what [@barbierp35](https://github.com/barbierp35) was looking for. Could something like this work for you?

---

For information, in media folder where I put my reolink records with FTP, many times there is a little difference in file name between video and image. 

Exemple : 
Camera terasse_00_20250218104900.mp4
Camera terasse_00_20250218104901.jpg

@ecdlguy For your idea to take a screen when there is a person détection, how can you link this screen with the video media ?

**Comment by ecdlguy** [comment]
@barbierp35 I try to summarize what I've done in order to send notifications to my mobile containing a thumbnail of the detected person:
In the HA configuration.yaml we need to setup doods:
```yaml
image_processing:
  - platform: doods
    scan_interval: 1576800000 # 50 years
    url: "http://192.168.6.10:8091" # Doods container webinterface
    detector: pytorch # Much better ootb detection quality than tensorflow 
    file_out:
      - "/config/www/doods_latest.jpg"
    labels:
      - name: person
        confidence: 20
    source:
      - entity_id: camera.cx410_schnappschusse_klar
```
The source entity is the camera stream "Snapshots Clear" (disabled by default), see [here](https://www.home-assistant.io/integrations/reolink/). The `scan_interval`-Parameter is chosen such that doods does not periodically run, but the object detection can of course still be triggered using the action `image_processing.scan`:
```yaml
alias: Run doods if person detected
description: ""
mode: single
triggers:
  - type: turned_on
    device_id: f23dbdab3d397d09ce36c1594464374a
    entity_id: 4287d11d205ab68c95c1bc075ca8b3ca
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - data: {}
    target:
      entity_id: image_processing.doods_cx410_schnappschusse_klar
    action: image_processing.scan
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
```
This automation is executed if a person is detected using the corresponding binary sensor of the HA Reolink Integration. The 5 s delay along with the `mode: single`-option prevents calling doods to frequent.

The next step is to react upon a successful detection of a person:
```yaml
alias: Crop, Resize and send Doods Snapshot
description: ""
mode: single
triggers:
  - entity_id:
      - image_processing.doods_cx410_schnappschusse_klar
    trigger: state
conditions: []
actions:
  - if:
      - condition: numeric_state
        entity_id: image_processing.doods_cx410_schnappschusse_klar
        attribute: total_matches
        above: 0
    then:
      - data:
          a: "{{ trigger.to_state.attributes.matches.person.0.box.0 }}"
          b: "{{ trigger.to_state.attributes.matches.person.0.box.1 }}"
          c: "{{ trigger.to_state.attributes.matches.person.0.box.2 }}"
          d: "{{ trigger.to_state.attributes.matches.person.0.box.3 }}"
          i: "1"
        action: shell_command.crop_doods_image_params
      - data:
          i: "1"
        action: shell_command.fit_doods_image
      - data:
          message: Kamera Garage hat um {{now()}} eine Person erkannt!
          title: Kamera Alarm
          data:
            ttl: 0
            priority: high
            visibility: public
            image: /local/doods_fit_1.jpg
            clickAction: >-
              intent://scan/#Intent;launchFlags=0x14000000;component=com.mcu.reolink/com.android.bc.login.WelcomeActivity;S.UID=95270005TJ8O109W;S.ALMTIME={{now().isoformat()}};S.ALMNAME=Detection;S.DEVNAME=CX410;S.ALMTYPE=PEOPLE;S.ALMCHN=1;end    
        action: notify.mobile_app_pixel_7a
    else:
      - data:
          message: Person erkannt!
          title: Kamera Alarm
          data:
            ttl: 0
            priority: high
            visibility: public
            image: /api/camera_proxy/camera.cx410_snapshots_main
            clickAction: >-
              intent://scan/#Intent;launchFlags=0x14000000;component=com.mcu.reolink/com.android.bc.login.WelcomeActivity;S.UID=95270005TJ8O109W;S.ALMTIME={{now().isoformat()}};S.ALMNAME=Detection;S.DEVNAME=CX410;S.ALMTYPE=PEOPLE;S.ALMCHN=1;end    
        action: notify.mobile_app_pixel_7a
```
Here,  we check if doods found at least one match (at least one person). If this is the case, a shell command is executed. This command is defined in the configuration.yaml:
```yaml
ffmpeg:

shell_command:
  crop_doods_image_params: 'ffmpeg -i /config/www/doods_latest.jpg -y -vf "crop=iw*({{ d }}-{{ b }})-2:ih*({{ c }}-{{ a }})-2:iw*{{ b }}+2:ih*{{ a }}+2" /config/www/doods_crop_{{ i }}.jpg'
```
The shell commands defined above uses [FFmpeg](https://www.home-assistant.io/integrations/ffmpeg/).

Another shell script is used in order to create a thumbnail with a fixed size without distorting the cropped snapshot:
```yaml
fit_doods_image: 'ffmpeg -i /config/www/doods_crop_{{ i }}.jpg -y -vf scale=1024:512:force_original_aspect_ratio=decrease,pad=1024:512:-1:-1:color=black" /config/www/doods_fit_{{ i }}.jpg'
```
This is important for sending it as a notification thumbnail. The intent used for the notification's click action is defined such that clicking the notification directly opens the Reolink App and plays the stream for the given timestamp. 

Btw I'd love to change that to an intent wich opens the HA companion app, and plays the corresponding clip within the advanced-camera-card... Do you know if this is possible? Using e.g. a timestamp?
