### ISSUE TITLE
Slow framerate (live view)

### ISSUE THREAD

**Issue by Spectre5** [dermotduffy/advanced-camera-card#1874]
**Checklist:**

- [x] Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- [x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.5.1
browser: Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
date: 2025-02-06T18:54:33.865Z
lang: en
timezone: America/Los_Angeles
git:
  hash: 43947b4
  build_date: Sun, 02 Feb 2025 00:09:40 GMT
  commit_date: Sat, 1 Feb 2025 16:08:32 -0800
ha_version: 2025.2.0
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      99113d150293ecb72e60e25ea397df16: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - frigate:
        client_id: frigate
        url: 192.168.8.11
      live_provider: webrtc-card
      go2rtc:
        modes:
          - webrtc
      camera_entity: camera.front_door
    - camera_entity: camera.camera_back
      live_provider: webrtc-card
      go2rtc:
        modes:
          - webrtc
  view:
    default: live
    camera_select: live
  menu:
    buttons:
      microphone:
        enabled: true
        priority: 100
        alignment: opposing
      timeline:
        enabled: false
      camera_ui:
        enabled: false
      download:
        enabled: false
      mute:
        enabled: true
    style: overlay
  live:
    auto_unmute: []
    controls:
      builtin: false
```

**[REQUIRED] Description of problem:**

When viewing the live video feed, the framerate is really slow.  I'd estimate maybe 1 frame every 2 seconds.  When viewing a recording from within the card, it is smooth with great frame rate.  This applies to both my phone (Android) as well as my wired (not wifi) desktop.  I also have the frigate proxy installed and when viewing the live video in HA through the proxy, it is clear and smooth as expected (same if using the frigate webapp outside of HA).  So I assume it must be something to do with this card that makes it slow since using the proxy within HA is fine.

I know it used to work smoothly, but I'm not sure which version of the card that was.  This issue has persisted for some time now, but I kept expecting the next version to fix it...which hasn't happened yet.
