### ISSUE TITLE
Allow to pass current camera name in `navigation_path`

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/advanced-camera-card#1878]
**[REQUIRED] Describe the feature you'd like:**

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.video_porteiro
  - camera_entity: camera.portao
  - camera_entity: camera.rua
  - camera_entity: camera.morro
live:
  show_image_during_load: false
  actions:
    tap_action:
      action: navigate
      navigation_path: >-
        /lovelace/cameras?advanced-camera-card-action.camera_select={{current_camera}}
```

**[OPTIONAL] Describe alternatives you've considered:**

Not very fun, but works:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.video_porteiro
  - camera_entity: camera.portao
  - camera_entity: camera.rua
  - camera_entity: camera.morro
overrides:
  - conditions:
      - condition: camera
        cameras:
          - camera.video_porteiro
    merge:
      live:
        actions:
          tap_action:
            action: navigate
            navigation_path: /lovelace/video-porteiro
  - conditions:
      - condition: camera
        cameras:
          - camera.portao
    merge:
      live:
        actions:
          tap_action:
            action: navigate
            navigation_path: >-
              /lovelace/cameras?advanced-camera-card-action.camera_select=camera.portao
  - conditions:
      - condition: camera
        cameras:
          - camera.rua
    merge:
      live:
        actions:
          tap_action:
            action: navigate
            navigation_path: >-
              /lovelace/cameras?advanced-camera-card-action.camera_select=camera.rua
  - conditions:
      - condition: camera
        cameras:
          - camera.morro
    merge:
      live:
        actions:
          tap_action:
            action: navigate
            navigation_path: >-
              /lovelace/cameras?advanced-camera-card-action.camera_select=camera.morro
```

**[OPTIONAL] Additional context:**

I suppose some other fields could leverage this too, but this is the only one I needed so far.

I am not sure if it's worth exploring a full-blown templating mechanism just for this (can be easily solved by regex replacing a fixed pattern like `{{current_camera}}`).

But if you keen to explore it, please take a look at https://github.com/Nerwyn/ha-nunjucks.
