### ISSUE TITLE
Thumbnails not showing up on live view

### ISSUE THREAD

**Issue by nabheet** [dermotduffy/advanced-camera-card#1880]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing

card_version: 7.0.0
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
date: 2025-02-08T15:09:25.259Z
lang: en
timezone: America/Denver
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.1
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JJSAWM6GT4AH6EJT8ZFNQXM1: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - frigate:
        camera_name: birdseye
  view:
    timeout_seconds: 0
    update_seconds: 300
    update_cycle_camera: true
    scan:
      enabled: true
      untrigger_reset: false
      trigger_show_border: true
  live:
    controls:
      thumbnails:
        media_type: events
        events_media_type: all
        size: 100
        show_details: true
        show_download_control: false
        show_favorite_control: false
        show_timeline_control: false
        mode: above
  menu:
    style: outside
    position: top
    alignment: left
    buttons:
      iris:
        enabled: true
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: true
      clips:
        enabled: true
      snapshots:
        enabled: true
      image:
        enabled: false
      timeline:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      fullscreen:
        enabled: true
      expand:
        enabled: false
      media_player:
        enabled: false
      microphone:
        enabled: false
      mute:
        enabled: false
      play:
        enabled: false
      ptz_controls:
        enabled: false
      ptz_home:
        enabled: false
```

**[REQUIRED] Description of problem:**

I had been using the old frigate hass card for a while. Just upgraded to v7 of this card. The live view is showing the birdseye video and the right buttons are displayed. But I cant get the thumbnails to show up on live view.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
None related to camera card
```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
`birdseye` cameras do not have events/thumbnails associated with them, as it's not a real camera.

**Comment by nabheet** [comment]
That's unfortunate as it used to work really well in the previous frigate-hass-card version. 

I did notice that they showed up for the actual cameras. But I have too many cameras for my HA dashboard monitor in the kitchen. 

I guess I don't really have much of a choice here. I will see if I can work something else out. 

Thank you for your reply.

**Comment by dermotduffy** [comment]
> That's unfortunate as it used to work really well in the previous frigate-hass-card version.

Events for `birdseye` camera has never been supported or possible in any version of this card. [It's literally in the code](https://github.com/dermotduffy/advanced-camera-card/blob/main/src/camera-manager/frigate/camera.ts#L143). Is it possible you are thinking of something different?

If you want to see media for other cameras when you view `birdseye`, you can setup dependencies between cameras like [this example](https://card.camera/#/examples?id=using-dependent-cameras-with-birdseye-for-all-cameras). Good luck!

**Comment by nabheet** [comment]
Oh! I was wondering what that dependencies line was doing in the YAML! LOL!

Thank you! I will give this a shot. (Again). 😀

I only edit this file every so often so I forget what I had done. Which is to say how incredible of a job yall are doing with backwards compatibility!

**Comment by nabheet** [comment]
Finally got around to this again. Is there still a way to `hide` the other cameras in the card and only show the birdseye?

I used to do this. But this doesnt seem to be worker. 

```
cameras:
  - camera_entity: camera.front_door
    title: Front Door
    hide: true
  - camera_entity: camera.garage
    title: Garage
    hide: true
  - camera_entity: camera.carport
    title: Carport
    hide: true
  - camera_entity: camera.patio
    title: Patio
    hide: true
  - frigate:
      camera_name: birdseye
    dependencies:
      all_cameras: true
```

**Comment by dermotduffy** [comment]
It's more verbose, but play around with something like this (it should hide that camera for everything other than getting snapshots and clips):

```yaml
  - camera_entity: camera.front_door
    title: Front Door
    capabilities:
      disable_except:
        - snapshots
        - clips
```

**Comment by nabheet** [comment]
These settings worked for me! And it feels way "smoother" than the previous implementation. Thank you!

**Comment by nabheet** [comment]
sorry to bother you again  - the clips/snapshots don't seem to be refreshing. Not sure what I am missing in my config:

```
- type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.front_door
            title: Front Door
            capabilities:
              disable_except:
                - snapshots
                - clips
          - camera_entity: camera.garage
            title: Garage
            capabilities:
              disable_except:
                - snapshots
                - clips
          - camera_entity: camera.carport
            title: Carport
            capabilities:
              disable_except:
                - snapshots
                - clips
          - camera_entity: camera.patio
            title: Patio
            capabilities:
              disable_except:
                - snapshots
                - clips
          - frigate:
              camera_name: birdseye
            dependencies:
              all_cameras: true
        live:
          controls:
            thumbnails:
              media_type: events
              events_media_type: all
              size: 100
              show_details: false
              show_download_control: false
              show_favorite_control: false
              show_timeline_control: false
              mode: above
        menu:
          style: outside
          position: top
          alignment: left
          buttons:
            iris:
              enabled: false
            cameras:
              enabled: false
            substreams:
              enabled: false
            live:
              enabled: true
            clips:
              enabled: true
            snapshots:
              enabled: true
            image:
              enabled: false
            timeline:
              enabled: false
            download:
              enabled: false
            camera_ui:
              enabled: false
            fullscreen:
              enabled: true
            expand:
              enabled: false
            media_player:
              enabled: false
            microphone:
              enabled: false
            mute:
              enabled: false
            play:
              enabled: false
            ptz_controls:
              enabled: false
            ptz_home:
              enabled: false
```

**Comment by dermotduffy** [comment]
@nabheet Try adding `trigger` to the capabilities allowed, e.g.:

```yaml
capabilities:
  disable_except:
    - snapshots
    - clips
    - trigger           <------------------- Added this
```
