### ISSUE TITLE
Action button.turn_off not found.

### ISSUE THREAD

**Issue by NickyNOS** [dermotduffy/advanced-camera-card#1882]
**Checklist:**

- [7.0.0](https://github.com/dermotduffy/advanced-camera-card/compare/v6.5.1...v7.0.0).

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/132.0.0.0 Safari/537.36
date: 2025-02-10T11:30:12.314Z
lang: en
timezone: Europe/Berlin
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.1
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.baby_watch_live_view
  status_bar: {}
  actions:
    double_tap_action:
      action: custom:advanced-camera-card-action
      advanced_camera_card_action: fullscreen
  elements:
    - type: custom:advanced-camera-card-menu-icon
      entity: button.baby_watch_pan_right
      icon: mdi:pan-left
      name: Pan left
      tap_action:
        action: toggle
    - type: custom:advanced-camera-card-menu-icon
      entity: button.baby_watch_tilt_up
      icon: mdi:pan-up
      name: Tilt up
      tap_action:
        action: toggle
      show_state: true
    - type: custom:advanced-camera-card-menu-icon
      entity: button.baby_watch_pan_left
      icon: mdi:pan-right
      name: Pan right
      tap_action:
        action: toggle
    - type: custom:advanced-camera-card-menu-icon
      entity: button.baby_watch_tilt_down
      hold_action:
        action: more-info
      icon: mdi:pan-down
      name: Tilt down
      tap_action:
        action: toggle
      double_tap_action:
        action: more-info
    - type: custom:advanced-camera-card-menu-icon
      entity: number.baby_watch_pan_degrees
      name: Degrees
      double_tap_action:
        action: toggle
      icon: mdi:pan-horizontal
    - type: custom:advanced-camera-card-menu-icon
      entity: number.baby_watch_tilt_degrees
      name: Tilt degrees
      icon: mdi:pan-vertical
```

**[REQUIRED] Description of problem:**

When I click in the button to tilt, it shows `Action button.turn_off not found.`

![Image](https://github.com/user-attachments/assets/12dd20b7-28ac-4142-bc8b-6099b2c62b79)

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
dwains-dashboard-layout.js:44  DWAINS-DASHBOARD-JS  Version 3.7.1
dwains-dashboard.js:92 Starting Dwains Dashboard
timer-bar-card.js?hacstag=3769045171310:590  TIMER-BAR-CARD  Version 1.31.0 
card-mod.js?hacstag=190927524344:1 CARD-MOD 3.4.4 IS INSTALLED
card-mod.js?hacstag=190927524344:1 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
mini-graph-card-bundle.js?hacstag=1512800620121:1  MINI-GRAPH-CARD  0.12.1 
bubble-card.js?hacstag=680112919240:1445  Bubble Card  v2.4.0 
card-bc00afb6.js:604  📷 Advanced Camera Card  7.0.0 
hass-hue-icons.js?hacstag=3844345221253:2074  HASS-HUE-ICONS  Version 1.2.53 
mushroom.js?hacstag=444350375421:309 🍄 Mushroom 🍄 - 4.2.1
connection-mixin.ts:157  Uncaught (in promise) {code: 'not_found', message: 'Service button.turn_off not found.', translation_key: 'service_not_found', translation_placeholders: {…}, translation_domain: 'homeassistant'}code: "not_found"message: "Service button.turn_off not found."translation_domain: "homeassistant"translation_key: "service_not_found"translation_placeholders: domain: "button"service: "turn_off"[[Prototype]]: Object[[Prototype]]: Object
callService @ connection-mixin.ts:157
await in callService
(anonymous) @ card-bc00afb6.js:75
tt @ card-bc00afb6.js:75
nt @ card-bc00afb6.js:75
execute @ card-bc00afb6.js:83
execute @ card-bc00afb6.js:88
executeActions @ card-bc00afb6.js:88
Cb.handleActionExecutionRequestEvent @ card-bc00afb6.js:88
Gg @ card-bc00afb6.js:75
Jx @ card-bc00afb6.js:119
actionHandler @ card-bc00afb6.js:119
(anonymous) @ card-bc00afb6.js:177
handleEvent @ card-bc00afb6.js:18
Je @ card-bc00afb6.js:75
i @ card-bc00afb6.js:75
```

**[OPTIONAL] Additional information:**
It works when I use the button as a button, in other interfaces.

**Comment by dermotduffy** [comment]
> It works when I use the button as a button, in other interfaces.

Can you clarify what this statement means? What other interfaces?

It's interesting that your config doesn't actually refer to `button.turn_off`, yet that is what is failing.

**Comment by dermotduffy** [comment]
I did this simple test and it seems to work fine. Let me know if this is still an issue for you.

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.front_door
elements:
  - type: custom:advanced-camera-card-menu-icon
    entity: light.office_main_lights
    icon: mdi:pan-left
    name: Pan left
    tap_action:
      action: toggle
```
