### ISSUE TITLE
Overlay menu doesn't round corners according to the card bellow

### ISSUE THREAD

**Issue by maxcerny** [dermotduffy/advanced-camera-card#1885]
**Checklist:**

- [x] Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- [x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

Imight be stupid but I'm not able to get the diagnostics... Holding the Icon for over 20 seconds does nothing.

```yaml

```

**[REQUIRED] Description of problem:**

Quite a simple bug, the overlay menu option extends past the rounded corners of the card on some corners. Simillar to #816 (you were right when you said this won't be the last time you see this :D )

Card editor:

![Image](https://github.com/user-attachments/assets/9b86da25-1981-487d-9f0f-e1cf3bcbb76b)

Dashboard:

![Image](https://github.com/user-attachments/assets/1dc74df0-0b3f-442d-8095-b301f1ab3922)

Dashboard with a theme

![Image](https://github.com/user-attachments/assets/7652f871-9ea9-453b-8fdc-816397b55b36)

weirdly enough in the dashboard itself it's only on one corner when I use a theme (ios-dark-mode-blue-red)

Config:

```yaml
type: custom:advanced-camera-card
cameras:
  - live_provider: webrtc-card
    webrtc_card:
      url: front_porch
      muted: true
    go2rtc:
      stream: front_porch
      modes: []
menu:
  buttons:
    microphone:
      enabled: true
      type: toggle
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: true
    timeline:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
    iris:
      enabled: true
      permanent: false
  position: right
  button_size: 50
  style: overlay
live:
  microphone:
    always_connected: false
  preload: true
  controls:
    builtin: false
  draggable: false
  show_image_during_load: false
media_viewer:
  controls:
    builtin: true
performance: {}
image: {}
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: "16:9"
cameras_global:
  dimensions:
    layout:
      fit: contain
```
