### ISSUE TITLE
Status bar disapears if title is disabled

### ISSUE THREAD

**Issue by snoack** [dermotduffy/advanced-camera-card#1887]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.0.0
browser: Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
date: 2025-02-12T16:26:19.525Z
lang: en
timezone: America/New_York
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.1
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JH10S36V9KVCPDT3WR597C98: 5.7.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.doorbell_package
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
  status_bar:
    style: overlay
    items:
      resolution:
        enabled: false
      title:
        enabled: false
```

**[REQUIRED] Description of problem:**

The status bar doesn't show up when `status_bar.style` is set to `overlay` and `status_bar.items.title.enabled` is set to `false`. I'd expect still the technology and camera engine indicators to show up in the bottom right corner.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
