### ISSUE TITLE
Card creates multiple backchannel consumers; mic button not always present for 2-way audio

### ISSUE THREAD

**Issue by esand** [dermotduffy/advanced-camera-card#1888]
**Checklist:**

[x] Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
[x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
date: 2025-02-12T21:42:52.970Z
lang: en
timezone: America/Toronto
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.1
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      e3358bedbfd47b4a9f76b316d491501b: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.front_doorbell
      live_provider: go2rtc
      id: 2way
      go2rtc:
        modes:
          - webrtc
          - mse
        stream: Front_doorbell_2way
      frigate:
        camera_name: Front_doorbell_2way
      capabilities:
        disable:
          - ptz
      dimensions:
        layout:
          fit: fill
  view:
    default: live
    interaction_seconds: 10
    default_reset:
      after_interaction: true
  menu:
    buttons:
      cameras:
        enabled: false
      live:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      fullscreen:
        enabled: false
      microphone:
        enabled: true
        type: momentary
        icon: mdi:microphone
        permanent: true
      mute:
        enabled: false
      iris:
        enabled: true
      substreams:
        enabled: false
    style: hidden
    position: bottom
    alignment: right
    button_size: 100
  live:
    controls:
      builtin: false
    microphone:
      always_connected: true
      disconnect_seconds: 1
    draggable: false
    lazy_unload:
      - unselected
      - hidden
    auto_unmute:
      - selected
      - visible
      - microphone
  cameras_global:
    dimensions:
      layout:
        fit: fill
```

**[REQUIRED] Description of problem:**

It seems that this card opens 2-3 stream connections when this card is activated. I can watch my go2rtc state page and see up to 3 consumers, which will then go down to 2 and sometimes finally go down to 1. The real issue is that this camera can only have *one* consumer to allow 2-way audio to function (so that the mic button is present and functions), but what often happens is that the card isn't using(?) the right consumer and so the mic button isn't displayed and I can't use this card for 2-way chatting (which is it's sole purpose).

**[OPTIONAL] Last working release (if known):**
This was working in earlier (5.x?) releases with Frigate 0.14.1. I am now using Frigate 0.15 (2-way audio works *sometimes* so I don't think it's Frigate or go2rtc - but not ruling it out entirely).

In earlier releases of this card I used to have a slightly more complex setup so that the 2-way audio wasn't always consumed, but this is a simplified config which I am hoping should/would work given all the updates concerning 2-way audio in this card, Frigate and go2rtc.

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
card-bc00afb6.js:75  jo: Failed to receive response from Home Assistant for request
    at Pv (https://mydomain/hacsfiles/frigate-hass-card/card-bc00afb6.js:75:185684)
    at async https://mydomain/hacsfiles/frigate-hass-card/engine-frigate-84c26527.js:1:4206
    at async V._getPTZCapabilities (https://mydomain/hacsfiles/frigate-hass-card/engine-frigate-84c26527.js:1:4186)
    at async V._initializeCapabilities (https://mydomain/hacsfiles/frigate-hass-card/engine-frigate-84c26527.js:1:3566)
    at async V.initialize (https://mydomain/hacsfiles/frigate-hass-card/engine-frigate-84c26527.js:1:2558)
    at async Se.createCamera (https://mydomain/hacsfiles/frigate-hass-card/engine-frigate-84c26527.js:3:11320)
    at async https://mydomain/hacsfiles/frigate-hass-card/card-bc00afb6.js:79:220
    at async Promise.all (index 0)
    at async df (https://mydomain/hacsfiles/frigate-hass-card/card-bc00afb6.js:75:143674)
    at async uy._initializeCameras (https://mydomain/hacsfiles/frigate-hass-card/card-bc00afb6.js:79:184) Object
af @ card-bc00afb6.js:75
```

**[OPTIONAL] Additional information:**

**Comment by esand** [comment]
> When the mic button doesn't show up, do you have a small blue circle on the top right of the live view? If yes, [your stream is not loading](https://card.camera/#/troubleshooting?id=stream-does-not-load).

No, that circle comes and goes - the stream loads and I have video and I can hear the incoming audio (very quiet since the 2-way stream doesn't have my audio boost on it). If I leave the dashboard and come back a few times, it sometimes works and I finally see the mic button.

If you'd like me to test anything to help out, let me know.

**Comment by dermotduffy** [comment]
I wonder if it's because you're ending up with an MSE stream. 2-way audio is only supported by `webrtc`. Remove `mse` from your config and see if it behaves any differently?

**Comment by esand** [comment]
I removed mse and it seems I have issues establishing a webrtc connection to that feed. I saw that I had port 8555 blocked locally on my LAN, and now after opening that up, I get no video, but audio is coming through. I had also tried playing with adding #audio=opus to the 2-way stream but I didn't notice a difference.

I also noticed that I get this error in Home Assistant though:
```
This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:381
integration: Frigate (documentation, issues)
First occurred: 1:04:45 PM (1 occurrences)
Last logged: 1:04:45 PM

Client response error (404) for URL http://172.18.3.1:5000/api/Front_doorbell_2way/ptz/info: Not Found
```

Something is obviously wrong with my webrtc configuration. How can I tell what URL this card tries to use when establishing webrtc? I have Frigate set using its internal address (http://172.x.x.x:5000) w/out authentication, and in HA I have Frigate set to use Frigate-native WebRTC support. My Frigate instance isn't exposed externally - HA is basically supposed to act like a proxy to it. I have an SSL cert for a hostname that resolves to the LAN IP if needed, but not sure where I'd plug that in.

BTW, my HA instance is accessed with an SSL enabled hostname, so it shouldn't be that.

**Comment by esand** [comment]
Ok, I believe I have figured my WebRTC issues... they were compounded and to be honest, no idea how things were working before.

1) I had a missing firewall rule preventing WebRTC from working on my LAN
2) None of the streams were outputting OPUS encoded audio which is required for WebRTC
3) The doorbell is H265 which is not supported by Chrome for WebRTC, thus I wasn't getting any video
4) The two-way stream is also H265 encoded, however this poses an issue because I cannot pass it through ffmpeg to recode it, otherwise ffmpeg becomes a stream consumer and breaks my doorbell

Specifically relating to this issue, removing MSE from the protocols and leaving only WebRTC has eliminated the additional consumers when accessing the card - it now correctly shows just 1 consumer.

However, I am now left with a bigger question... how do I get a 2-way audio card working if I need WebRTC, but I can't pass it through ffmpeg?

**Comment by esand** [comment]
I was able to resolve all issues, including getting WebRTC to work with 2-way audio without using ffmpeg on the backchannel. For anyone coming to this (and maybe this should get tossed in to some docs or something), it required a go2rtc config change:

```
streams:
  Front_doorbell:
      # 2560x1920 @15fps
  - ffmpeg:rtsp://XXXX:XXXX@192.168.4.11:554/cam/realmonitor?channel=1&subtype=0#backchannel=0#video=h264#hardware#audio=myvol#audio=opus
  Front_doorbell_detect:
      # 720x576 @15fps
  - ffmpeg:rtsp://XXXX:XXXX@192.168.4.11:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
  Front_doorbell_2way:
  - ffmpeg:Front_doorbell#video=copy
  - rtsp://XXXX:XXXX@192.168.4.11:554/cam/realmonitor?channel=1&subtype=0
```

I had to merge my two ffmpeg lines in to one for `Front_doorbell` because go2rtc only publishes the first video/audio it's given (having two `ffmpeg:` lines with the video transcoding on the 2nd wasn't being published). Then, for the 2-way audio stream, I have the video from the main stream copied (it's copying the h264 transcoded stream), and since I don't add #audio, it doesn't copy that.

I also had to add my docker bridge IP for Frigate to the webrtc candidates, since Home Assistant was configured to access it via that IP.

After all this, I was able to get WebRTC working properly, and the doorbell stream works correctly with the mic button present. Also, things are very "snappy" now - accessing the doorbell card and having video/audio/mic showing is almost instant.
