### ISSUE TITLE
Implement support for PTZ presets

### ISSUE THREAD

**Issue by Bjoern3003** [dermotduffy/advanced-camera-card#1889]
Hi,

I have configured Frigate and the Advanced-camera-card. 

For now everything is working well, but I can not see my Camera PTZ Presets.

They are available in Frigate. And The API does also have all Presets in the JSON.

`{"features":["pt","zoom"],"name":"garten","presets":["strasse","garten","terrasse"]}`

But I only see the Home, Zoom and Movement Buttons. Maybe I missunderstand the Documentation. This is my Actual Card Config:

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.garten
    live_provider: go2rtc
    ptz:
      presets:
        strasse: null
        garten: null
        terrasse: null
menu:
  buttons:
    recordings:
      enabled: true
```
