### ISSUE TITLE
Question/Request: Can a filter be saved/applied to a gallery view?

### ISSUE THREAD

**Issue by b-neufeld** [dermotduffy/advanced-camera-card#1890]
**Checklist:**

- ✅Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- ✅Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36
date: 2025-02-13T16:08:48.116Z
lang: en
timezone: America/Regina
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.2
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      fc484cef2c94b6395cfa6fda6d1aab05: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.front_door
    - camera_entity: camera.garage
  view:
    default: clips

```

**[REQUIRED] Description of problem:**

Background & use case: I have Frigate set up to capture all "person" and "car" objects on my front door camera. I have four "zones" for object detection: Driveway, Street, Front Steps, and Lawn. I would like the card in HA to only show clips from the Driveway, Front Steps, and Lawn. 

In both the web browser and app, I can configure filters on the media gallery to get the desired outcome, but the filters don't seem to survive a dashboard save & refresh. 

![Image](https://github.com/user-attachments/assets/0c68ff30-fd71-47f4-87fe-8141eb32c185)

![Image](https://github.com/user-attachments/assets/405e61bc-3e0a-4e34-b7ee-c0f7df446b84)

In a fairly recent combined version of Frigate & Advanced Camera Card, I _SEEMED_ to have the ability to save a filter on a Gallery View on the Advanced Camera Card. I had this behaviour working previously: for months and months my gallery view had excluded the "Street" detected objects. 

**[OPTIONAL] Last working release (if known):**

Unfortunately I did not keep careful track of which versions I had this working and when it broke, as I've upgraded HA, Frigate, and ACC to latest versions over the last 2 weeks. 

I have checked the documentation to see if this is/was possible using YAML configuration but I do not think it is. My sincere apologies if I have overlooked something easy! Great project, I love this card.

**Comment by dermotduffy** [comment]
> In a fairly recent combined version of Frigate & Advanced Camera Card, I SEEMED 

I don't think the behavior here has ~ever changed. I suspect you might be able to get what you want by just setting the zones on the camera, like this:

```yaml
  cameras:
    - camera_entity: camera.front_door
      frigate:
        zones:      <------------- Try adding these
          - driveway
          - lawn
        labels:     <------------- Try adding these
          - person
```

**Comment by b-neufeld** [comment]
``Thank you so much for the reply and the example. That gave me enough to get it figured out. I still have no idea how I had this config previously then lost it somehow!

I'll share some notes that will hopefully help others. I also wanted to mix two camera results in the gallery. I found this older post with details: https://github.com/dermotduffy/advanced-camera-card/issues/1455#issuecomment-2118997954

Here is my gallery card config for reference, mixing two cameras and filtering for different labels on each camera:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.front_door
    dependencies:
      cameras:
        - camera.garage
    frigate:
      zones:
        - driveway
        - lawn
        - front_steps
      labels:
        - person
        - car
  - camera_entity: camera.garage
    frigate:
      labels:
        - person
view:
  default: clips

```

Thanks again.
