### ISSUE TITLE
Click a Notification to Go To Specific Camera View?

### ISSUE THREAD

**Issue by bricenice17** [dermotduffy/advanced-camera-card#1892]
Is there a way to click a notification that goes to a specific camera view in the card? For example, I get a notification of motion from a camera. I click on it, it takes me to that exact camera stream. Currently, I have it so that if I get that notification, it takes me to the page in my dash with all the camera views.. But was wondering if possible, if it could open the stream of the camera that triggered the notification.

**Comment by dermotduffy** [comment]
@bricenice17 Yes. This is possible, as the card will respond to query parameters (or at least should!). Documentation: https://card.camera/#/usage/url-actions

@xAcrosonicx That should work (and does work for me). Note that you'd need to be running a recent version of the card. Would you mind sharing your config so I can test out if your settings are interfering somehow?

**Comment by xAcrosonicx** [comment]
@dermotduffy - first of all, thank you for all your work on this incredible card!

Here is my card:
```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: auto
    title: Doorbell
    icon: phu:reolink-doorbell
    id: doorbell
    go2rtc:
      modes: []
    image:
      mode: camera
    triggers:
      occupancy: true
      motion: false
  - camera_entity: camera.frontcamera
    live_provider: auto
    title: Driveway
    icon: phu:reolink-842
    id: frontcamera
    image:
      mode: camera
    triggers:
      occupancy: true
  - camera_entity: camera.westside
    live_provider: auto
    title: Westside
    icon: phu:reolink-842
    id: westside
    image:
      mode: camera
    triggers:
      occupancy: true
  - camera_entity: camera.backyard
    live_provider: auto
    title: Backyard
    icon: phu:reolink-842
    id: backyard
    image:
      mode: camera
    triggers:
      occupancy: true
  - camera_entity: camera.eastside
    live_provider: auto
    title: Eastside
    icon: phu:reolink-842
    id: eastside
    image:
      mode: camera
    triggers:
      occupancy: true
profiles:
  - scrubbing
view:
  default: live
  camera_select: live
  dim: true
  interaction_seconds: 14
  triggers:
    show_trigger_status: false
  keyboard_shortcuts:
    ptz_left:
      key: ArrowLeft
    ptz_right:
      key: ArrowRight
    ptz_up:
      key: ArrowUp
    ptz_down:
      key: ArrowDown
    ptz_zoom_in:
      key: +
    ptz_zoom_out:
      key: "-"
    ptz_home:
      key: h
menu:
  style: overlay
  position: top
  alignment: left
  buttons:
    iris:
      permanent: true
    substreams:
      enabled: false
    mute:
      enabled: true
    play:
      enabled: false
    microphone:
      enabled: true
status_bar:
  style: none
live:
  auto_pause:
    - unselected
    - hidden
  auto_mute:
    - unselected
    - microphone
    - hidden
  auto_play:
    - selected
  auto_unmute:
    - selected
  display:
    grid_selected_width_factor: 0
    mode: single
image:
  mode: camera
timeline:
  style: ribbon
```
