### ISSUE TITLE
Confusing message after update

### ISSUE THREAD

**Issue by mark-harmison** [dermotduffy/advanced-camera-card#1893]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases) - issue is with the update process.
- Please try clearing your browser cache. - _Note that here the working is "browser cache" which is the point of this bug._

**Card diagnostic information:**

```yaml
card_version: 7.0.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/132.0.0.0 Safari/537.36
date: 2025-02-14T19:00:28.101Z
lang: en
timezone: America/Chicago
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JKFB7CVP9PNB40YY1Z8HKD02: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.duck_house_sd_stream
```

**Confusing message after update**

After the most recent Frigate update in HA you get a message to "manually clear the frontend cache". Better wording in English would be "manually clear the browser cache". 

As evidence that this is confusing, see the following thread which has been active for over a year: https://community.home-assistant.io/t/how-to-clear-the-frontend-cache/670491

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
