### ISSUE TITLE
Dragging cameras sometimes don't work

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/advanced-camera-card#1897]
**Checklist:**

- [x] Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- [x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.1.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36
date: 2025-02-17T14:32:03.254Z
lang: en
timezone: America/Sao_Paulo
git:
  hash: 7fb710d
  build_date: Fri, 14 Feb 2025 15:24:30 GMT
  commit_date: Fri, 14 Feb 2025 07:23:19 -0800
ha_version: 2025.2.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      624fd5a51dc304193d7e34ab79e1dae3: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.video_porteiro
    - camera_entity: camera.portao
    - camera_entity: camera.rua
    - camera_entity: camera.morro
  cameras_global:
    live_provider: image
    image:
      refresh_seconds: 3
    always_error_if_entity_unavailable: true
    dimensions:
      layout:
        fit: cover
        position:
          x: 0
  profiles:
    - low-performance
    - casting
  live:
    show_image_during_load: false
    actions:
      tap_action:
        action: navigate
        navigation_path: >-
          /lovelace/cameras?advanced-camera-card-action.camera_select={{
          advanced_camera_card.camera }}
    controls:
      ptz:
        mode: 'off'
      next_previous:
        style: none
    draggable: true
  overrides:
    - conditions:
        - condition: camera
          cameras:
            - camera.video_porteiro
      merge:
        live:
          actions:
            tap_action:
              action: navigate
              navigation_path: /lovelace/video-porteiro
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '16:9'
  menu:
    style: outside
    buttons:
      iris:
        enabled: true

```

**[REQUIRED] Description of problem:**

It's a bit hard to explain, but sometimes dragging a camera doesn't work. For example, see 11th second of the video below.

https://github.com/user-attachments/assets/026e001c-3ba7-42e0-8b36-68f50573664c

**[OPTIONAL] Last working release (if known):** N/A

**[OPTIONAL] Javascript errors shown in the web inspector:** No relevant logs.

**[OPTIONAL] Additional information:**

This issue is super low-priority. Don't worry about it.

I am more curious if you can reproduce the issue.
