### ISSUE TITLE
Issues with Reolink POE white doorbell 2-way audio

### ISSUE THREAD

**Issue by JSa1987** [dermotduffy/advanced-camera-card#1898]
For the last couple of days I have been trying to setup the 2-way audio for a White Reolink POE Doorbell. I have now managed to get this working when connecting to the Frigate UI via HTTPS, but I still cannot get this working in Home Assistant using the advance-camera-card.

My Frigate configuration is as follows:
```
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - Frigate_IP:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"
  streams:
    doorbell_camera:
      - rtsp://admin:PWD@Reolik_IP:554/
      - ffmpeg:http://Reolik_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PWD#audio=opus#audio=volume
    doorbell_camera_sub:
      - rtsp://admin:PWD@Reolik_IP:554/h264Preview_01_sub
      - ffmpeg:http://Reolik_IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=PWD#audio=opus#audio=volume
cameras:
  doorbell_camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell_camera
    onvif:
      host: Reolink_IP
      port: 8000
      user: admin
      password: PWD
```

If in the card I select `go2rtc: modes:` = `webrtc` then the microphone button shows up in the menu, and the audio from the microphone of the device running the Home Assistant app to the speaker of the doorbell works fine. However, the audio from the doorbell microphone to the speaker of the device running the Home Assistant app does not work. The mute/unmute button does not show up in the card even if this is enabled in the card configuration.

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.doorbell_camera
    engine: frigate
    live_provider: go2rtc
    title: Dorbell
    icon: mdi:doorbell-video
    go2rtc:
      modes:
        - webrtc
```

If in the card I select `go2rtc: modes: `= `MSE` then the mute/unmute button shows up in the menu, and the audio from the microphone of the doorbell to the speaker of the device running the Home Assistant app works fine. However, the microphone button does not show up in the card even if this is enabled in the card configuration and therefore there is no audio from the microphone of the device running the Home Assistant app to the speaker of the doorbell.

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.doorbell_camera
    engine: frigate
    live_provider: go2rtc
    title: Dorbell
    icon: mdi:doorbell-video
    go2rtc:
      modes:
        - mse
```

How can I get both audio streams to work at the same time from the Home Assistant advance-camera-card?

**Comment by dermotduffy** [comment]
> If in the card I select go2rtc: modes: = webrtc then the microphone button shows up in the menu, and the audio from the microphone of the device running the Home Assistant app to the speaker of the doorbell works fine. However, the audio from the doorbell microphone to the speaker of the device running the Home Assistant app does not work. The mute/unmute button does not show up in the card even if this is enabled in the card configuration.

Suspect the video simply has no audio stream, which is why the card isn't playing any sound or showing you mute/unmute buttons. No point in experimenting with `mse` here, you must use `webrtc` for this to work. As for why there's no audio on your stream, I'm afraid I can't say. Is there audio if you visit the stream on your go2rtc UI?

**Comment by jdmccreight** [comment]
Hello, I am having the same issue, previously I had a working Reolink Doorbell 2-Way-Audio setup. (Connecting to Home Assistant through HTTPS)

I am also no longer receiving audio from my Garage Camera. The Garage Camera doesn't have a built in audio output, but the Microphone still shows up when it didn't previously.

The strange thing is I don't get audio when I pull up the go2rtc stream (HTTP), but I do get audio when listening through Frigate (HTTPS)

Here is the go2rtc Doorbell JSON output while playing audio and having the microphone connected through Frigate:
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://10.10.37.25/Preview_01_main/",
      "remote_addr": "10.10.37.25:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1739692860211301 1 IN IP4 10.10.37.25\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=881333505, senders=2",
        "97 MPEG4-GENERIC/16000, bytes=6632386, senders=1"
      ],
      "senders": [
        "0 PCMU/8000, bytes=60480, receivers=1"
      ],
      "recv": 895834159,
      "send": 66528
    },
    {
      "url": "ffmpeg:doorbell#audio=opus#audio=volume"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/doorbell",
      "remote_addr": "127.0.0.1:60618",
      "user_agent": "FFmpeg Frigate/0.15.0-cea210d",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=881333505, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=6632386, receivers=1"
      ],
      "send": 898401651
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "tcp4 prflx 10.10.15.10:63361 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0",
      "medias": [
        "video, sendonly, VP8, VP9, H264",
        "audio, recvonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, L16, PCML"
      ],
      "receivers": [
        "0 PCMU/8000, bytes=60480, senders=1"
      ],
      "senders": [
        "126 H264, bytes=4053324, receivers=1"
      ],
      "recv": 65016,
      "send": 4096270
    }
  ]
}
```

And here is the go2rtc Doorbell JSON output while having the microphone connected through the Advanced Camera Card:
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://10.10.37.25/Preview_01_main/",
      "remote_addr": "10.10.37.25:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1739692860211301 1 IN IP4 10.10.37.25\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=944483809, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=7107742, senders=1"
      ],
      "senders": [
        "0 PCMU/8000, bytes=319040, receivers=0"
      ],
      "recv": 960024395,
      "send": 350944
    },
    {
      "url": "ffmpeg:doorbell#audio=opus#audio=volume"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/doorbell",
      "remote_addr": "127.0.0.1:60618",
      "user_agent": "FFmpeg Frigate/0.15.0-cea210d",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=944483809, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=7107742, receivers=1"
      ],
      "send": 962775695
    }
  ]
}
```

Doorbell Pictures: (missing audio, but still has the microphone)
![Image](https://github.com/user-attachments/assets/8bbfbb9e-59e5-455f-bba9-d539980c3fbb)
![Image](https://github.com/user-attachments/assets/42aa4719-85f9-4a24-ab54-7e7efbced6e9)
Garage Pictures: (Shouldn't have the microphone, missing audio)
![Image](https://github.com/user-attachments/assets/94138d12-dbee-4f67-b7a7-19410f4b1309)
![Image](https://github.com/user-attachments/assets/df663405-6e79-428e-bfac-f94a5251e90e)

**Comment by fergalom** [comment]
I had this issue in the last few days with the same doorbell and what solved it for me was to comment out the ffmpeg in the go2rtc element of the config.

Comment out:
```
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"
```

**Comment by JSa1987** [comment]
I realized I was getting the following error:
`[exec] error=exec: "ffmpeg": executable file not found in $PATH url=exec:ffmpeg`

This seems to be because:
```
  ffmpeg:
    bin: ffmpeg
```

does not provide the full path to ffmpeg as mentioned [here](https://github.com/blakeblackshear/frigate/discussions/14027). And there is not need to override the ffmpeg path. To adjust the volume all that is needed is:
```
  ffmpeg:
    volume: -af "volume=25dB"
```
With this change I managed to get the two way audio to work.

Just for reference this is my working configuration:

```
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - Frigate_IP:8555
      - stun:8555
  ffmpeg:
    volume: -af "volume=10dB"
  streams:
    doorbell_camera:
      - rtsp://admin:PWD@Doorbell_IP:554/
      - ffmpeg:http://Doorbell_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PWD#audio=opus#audio=volume
    doorbell_camera_sub:
      - rtsp://admin:PWD@Doorbell_IP:554/h264Preview_01_sub
      - ffmpeg:http://Doorbell_IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=PWD#audio=opus#audio=volume
cameras:
  doorbell_camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell_camera
    onvif:
      host: Doorbell_IP
      port: 8000
      user: admin
      password: PWD
```
