### ISSUE TITLE
Reolink Camera doesn't display recordings in either clips gallery or timeview

### ISSUE THREAD

**Issue by sherryxiao1988** [dermotduffy/advanced-camera-card#1899]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.1.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/129.0.0.0 Safari/537.36
date: 2025-02-17T21:56:42.489Z
lang: en
timezone: America/Los_Angeles
git:
  hash: 7fb710d
  build_date: Fri, 14 Feb 2025 15:24:30 GMT
  commit_date: Fri, 14 Feb 2025 07:23:19 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.backyard_right_fluent
      live_provider: auto
      capabilities:
        disable: []
    - camera_entity: camera.backyard_left_fluent
    - camera_entity: camera.main_gate_2_fluent
    - camera_entity: camera.main_outside_fluent
    - camera_entity: camera.left_gate_camera_fluent
  live:
    display:
      mode: grid

```

**[REQUIRED] Description of problem:**
Live view works fine.

Clips gallery says "no media to display":

![Image](https://github.com/user-attachments/assets/2b1bdc80-a5ce-4d3d-ae9a-1538f31c7d36)

Switching to "recordings" get this:

<img width="1032" alt="Image" src="https://github.com/user-attachments/assets/fd9d0e04-cde5-46de-94e5-d5b1b57d9573" />

Switching to "snapshot" get a similar error:

<img width="1251" alt="Image" src="https://github.com/user-attachments/assets/9ed5fa89-b270-44f2-b4e4-2417fe4af4ca" />

Timeview displays nothing:

<img width="1451" alt="Image" src="https://github.com/user-attachments/assets/9e546267-616e-4fd2-9383-879779215cdd" />

Here are some screenshots for things under media:

<img width="955" alt="Image" src="https://github.com/user-attachments/assets/0a4b3158-5240-43c9-bd67-608c12517805" />

<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/d41f5a7f-36fe-4802-862b-cef7eab21c00" />

<img width="1460" alt="Image" src="https://github.com/user-attachments/assets/130a0a38-6998-4a8a-bd29-32aaff749a80" />

<img width="1263" alt="Image" src="https://github.com/user-attachments/assets/4754eaba-0759-4198-a0cb-999f16dbbd9b" />

**Comment by dermotduffy** [comment]
`recordings` and `snapshots` not showing anything is not surprising, there's no support for that. There is support for `clips` though (i.e. non-continuous recordings), so our goal is to get that first screenshot working, the one that currently says "No media to display".

Looking through your screenshots (hugely helpful, thank you), I don't know why it's not working though. As all the titles appear to match what the card is looking for.

Next step in debugging is to look at the websocket messages being exchanged between the card, and your browser. If you're not a developer, this will be quite intimidating/difficult. To do that we can either:

 - If you're familiar with web debugging tools, you'd open them (usually F12), navigate to `Network`, choose `WS`, click the `websocket` row, then the `Messages` tab, then refresh the page and look through the messages (requests and their results) with the type field set to `media_source/browse_media` and paste as many of them in here as you can.
 - OR: Give me temporary access to your HA instance, I can do it remotely, and you can revoke my access. This is a huge leap of faith on your part though.
 - OR: I can try to add a new debugging mode that dumps out content like this...

Sorry, no nice options :-(

**Comment by sherryxiao1988** [comment]
Thanks for the detailed explanation @dermotduffy. I am a developer so things might be easier for us :)

I am having another issue with those cameras (battery draining with HA integration). I will get back to this one once I A/B tested having the pooling update turned off for the battery issue.

**Comment by dermotduffy** [comment]
Sounds good, thank you!

**Comment by sherryxiao1988** [comment]
FYI, it seems this battery issue might also be relate to the advanced camera card, I am linking it here for reference:
https://github.com/home-assistant/core/issues/136963#issuecomment-2645977588

**Comment by sherryxiao1988** [comment]
> `recordings` and `snapshots` not showing anything is not surprising, there's no support for that. There is support for `clips` though (i.e. non-continuous recordings), so our goal is to get that first screenshot working, the one that currently says "No media to display".
> 
> Looking through your screenshots (hugely helpful, thank you), I don't know why it's not working though. As all the titles appear to match what the card is looking for.
> 
> Next step in debugging is to look at the websocket messages being exchanged between the card, and your browser. If you're not a developer, this will be quite intimidating/difficult. To do that we can either:
> 
> * If you're familiar with web debugging tools, you'd open them (usually F12), navigate to `Network`, choose `WS`, click the `websocket` row, then the `Messages` tab, then refresh the page and look through the messages (requests and their results) with the type field set to `media_source/browse_media` and paste as many of them in here as you can.
> * OR: Give me temporary access to your HA instance, I can do it remotely, and you can revoke my access. This is a huge leap of faith on your part though.
> * OR: I can try to add a new debugging mode that dumps out content like this...
> 
> Sorry, no nice options :-(

I only found two that's "media_source/browse_media":
```

{type: "media_source/browse_media", media_content_id: "media-source://reolink", id: 64}
id
: 
64
media_content_id
: 
"media-source://reolink"
type
: 
"media_source/browse_media"


{type: "media_source/browse_media", media_content_id: "media-source://reolink", id: 66}
id
: 
66
media_content_id
: 
"media-source://reolink"
type
: 
"media_source/browse_media"
```

I am only displaying one camera this time:
```
card_version: 7.1.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/129.0.0.0 Safari/537.36
date: 2025-02-18T05:46:11.525Z
lang: en
timezone: America/Los_Angeles
git:
  hash: 7fb710d
  build_date: Fri, 14 Feb 2025 15:24:30 GMT
  commit_date: Fri, 14 Feb 2025 07:23:19 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.backyard_right_fluent
  live:
    lazy_unload:
      - unselected
    auto_pause:
      - unselected
```

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.backyard_right_fluent
live:
  lazy_unload:
    - unselected
  auto_pause:
    - unselected
```

I updated
```
live:
  lazy_unload:
    - unselected
  auto_pause:
    - unselected
```
to test the battery issue. I think it's not relevant to this issue.

Thanks.
