### ISSUE TITLE
advanced camera card works only "Sometimes"

### ISSUE THREAD

**Issue by kgiedrius** [dermotduffy/advanced-camera-card#1902]
HA plugin is latest, but issue started to happen from 7.0 version

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.durys_2
    live_provider: auto
  - camera_entity: camera.kiemas_2
    live_provider: auto
  - camera_entity: camera.slaitas_2
    live_provider: auto
  - camera_entity: camera.terasa_2
    live_provider: auto
  - camera_entity: camera.varteliai_2
    live_provider: auto
live:
  display:
    mode: grid
```

**Description of problem:**
```
Issue is that sometimes this card show cameras, but sometimes do not show and shows error:
Work/not work - absolutely random

![Image](https://github.com/user-attachments/assets/d1691ba5-6598-4c21-b3c7-5c08c55fdf60)

url in resources: /hacsfiles/advanced-camera-card/advanced-camera-card.js?hacstag=394082552721 
this url works in both cases (good and bad)
```
Issue still exist in 

![Image](https://github.com/user-attachments/assets/e73d3585-ca5e-447c-abbc-065f5aaa6dfa)
