### ISSUE TITLE
Override for `live` view is not working with multiple overrides specified.

### ISSUE THREAD

**Issue by luisiam** [dermotduffy/advanced-camera-card#1905]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.2.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
date: 2025-02-18T23:39:47.452Z
lang: en
timezone: America/Los_Angeles
git:
  hash: bb147a4
  build_date: Tue, 18 Feb 2025 04:14:32 GMT
  commit_date: Mon, 17 Feb 2025 20:13:21 -0800
ha_version: 2025.2.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JEVEHTJZT0PVB2MNPWB15B57: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.doorbell
  overrides:
    - conditions:
        - condition: view
          views:
            - live
      merge:
        menu:
          buttons:
            live:
              enabled: false
    - conditions:
        - condition: expand
          expand: true
```

**[REQUIRED] Description of problem:**

When multiple overrides are set up, the overrides for the `live` view condition is not working. In the above example, the menu button is still shown under `live` view. If I remove the second overrides for `expand` condition, the first override will be working as expected.

**[OPTIONAL] Last working release (if known):** 7.2.0

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
N/A
```

**[OPTIONAL] Additional information:** N/A
