### ISSUE TITLE
Card should respect entity unavailable color

### ISSUE THREAD

**Issue by haforme** [dermotduffy/advanced-camera-card#1906]
![Image](https://github.com/user-attachments/assets/501809da-3db3-4503-8c50-f44053a2cb20)

**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases). - Done card_version: 7.2.1
- Please try clearing your browser cache. - Done

 Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.2.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
date: 2025-02-19T01:39:36.037Z
lang: en
timezone: America/New_York
git:
  hash: bb147a4
  build_date: Tue, 18 Feb 2025 04:14:32 GMT
  commit_date: Mon, 17 Feb 2025 20:13:21 -0800
ha_version: 2025.2.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      975c7200f53a18575cbe53c5d9524bdb: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.kitchen
      title: KITCHEN
      frigate:
        camera_name: kitchen
      always_error_if_entity_unavailable: true
  view:
    default: live
    theme:
      themes:
        - dark
  live:
    preload: true
    controls:
      builtin: false
      thumbnails:
        mode: none
    show_image_during_load: true
  media_viewer:
    controls:
      builtin: false
      timeline:
        mode: below
        style: stack
        pan_mode: seek
    auto_pause: []
    auto_mute: []
    auto_unmute:
      - selected
      - visible
  menu:
    buttons:
      mute:
        enabled: true
      recordings:
        enabled: true
        icon: mdi:video-vintage
      screenshot:
        enabled: true
        priority: 0
        icon: mdi:camera
      cameras:
        enabled: false
      clips:
        enabled: false
      fullscreen:
        priority: 0
      expand:
        enabled: true
        priority: 0
      play:
        enabled: false
      timeline:
        enabled: false
      download:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: true
      image:
        enabled: false
      snapshots:
        enabled: false
      camera_ui:
        enabled: true
      iris:
        enabled: true
    style: outside
    position: bottom
    alignment: bottom
    button_size: 38
  timeline: {}
  media_gallery:
    controls:
      thumbnails:
        show_details: true
        show_favorite_control: false
        show_timeline_control: false
  performance:
    features:
      card_loading_indicator: false
      animated_progress_indicator: false
  elements:
    - type: custom:advanced-camera-card-menu-state-icon
      entity: switch.kitchen_recordings
      title: Record for 10 Min or turn Off
      icon: mdi:record-rec
      tap_action:
        action: perform-action
        data:
          entity_id: switch.kitchen_recordings
        perform_action: switch.toggle
    - type: custom:advanced-camera-card-menu-state-icon
      entity: light.summer_kitchen_repeater
      title: Summer Kitchen Lamp
      icon: mdi:lamp
      tap_action:
        action: toggle
    - type: state-badge
      entity: sensor.summer_kitchen_temperature
      style:
        top: 65px
        right: 28px
        opacity: 0.6
    - type: state-badge
      entity: sensor.kitchen_sink_temperature
      style:
        top: 65px
        right: '-33px'
        opacity: 0.6
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '4:3'
  status_bar:
    style: none

```

Description of problem:**
Unavailable Entity color for light.summer_kitchen_repeater is not shown on card menu yet light toggle on/off shows correct color. I've seen this previously with HA Views that had "theme: Backend-selected" coded for the view.  My defined color is "state-unavailable-color: var(--red-color)" as shown on the screenshot for the entity I added to a separate card for testing.  My solution was to remove "theme: Backend-selected" from the dashboards via the raw configuration editor. The camera card view does not have this theme defined.

Additional information:**

![Image](https://github.com/user-attachments/assets/901a8110-7974-4308-9ba8-7a293e3079a8)
