### ISSUE TITLE
Uncaught error from Chrome 133.0.0.0 on macOS 10.15.7 Error: Failed to execute 'define' on 'CustomElementRegistry'

### ISSUE THREAD

**Issue by Uschinator** [dermotduffy/advanced-camera-card#1907]
**[REQUIRED] Card diagnostic information:**

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.driveway_cam
menu:
  position: bottom
live:
  preload: true
  draggable: false
  zoomable: false
  lazy_load: false
  controls:
    timeline:
      show_recordings: false
    builtin: false
    thumbnails:
      show_details: false
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
performance:
  features:
    animated_progress_indicator: false
    card_loading_indicator: false
  style:
    box_shadow: false
    border_radius: false
status_bar:
  popup_seconds: 0
view:
  default: live
timeline:
  show_recordings: false
  controls:
    thumbnails:
      show_download_control: false
      show_timeline_control: false
      show_favorite_control: false
      show_details: false
media_gallery:
  controls:
    thumbnails:
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
```

**[REQUIRED] Description of problem:**

I have two Cards, each showing a different camera. The cards are working and showing the cameras, but i get the error message as soon as i open up the page with the two cards.

Cache Cleared multiple times.

Uncaught error from Chrome 133.0.0.0 on macOS 10.15.7 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "focus-trap" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/advanced-camera-card/card-1ab50869.js:75:3686
