### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/advanced-camera-card#1909]
**Checklist:**

- [x] Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- [x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

I noticed the issue in my HA logs, so I'm not completely sure which card exactly threw it.

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: go2rtc
    image:
      refresh_seconds: 1
    always_error_if_entity_unavailable: true
live:
  lazy_unload:
    - unselected
    - hidden
  auto_unmute:
    - microphone
  show_image_during_load: true
  draggable: false
  microphone:
    always_connected: false
    disconnect_seconds: 120
    mute_after_microphone_mute_seconds: 120
  controls:
    builtin: false
menu:
  buttons:
    snapshots:
      enabled: false
    fullscreen:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    microphone:
      type: toggle
      priority: 49
    mute:
      enabled: true
    iris:
      enabled: false
  style: overlay
  button_size: 85
overrides:
  - conditions:
      - condition: microphone
        connected: true
    merge:
      menu:
        buttons:
          microphone:
            enabled: true
elements:
  - type: custom:advanced-camera-card-menu-state-icon
    entity: cover.porta
    state_color: true
    alignment: opposing
    tap_action:
      action: perform-action
      perform_action: cover.open_cover
      data:
        entity_id: cover.porta
    priority: 48
  - type: custom:advanced-camera-card-menu-state-icon
    entity: switch.alarme_da_casa
    state_color: true
    tap_action:
      action: toggle
    alignment: opposing
    priority: 49
  - type: custom:advanced-camera-card-menu-state-icon
    entity: input_boolean.nao_perturbe_ap02
    state_color: true
    tap_action:
      action: toggle
    alignment: opposing
    priority: 50
  - type: custom:advanced-camera-card-conditional
    conditions:
      - condition: state
        state: "on"
        entity: input_boolean.video_porteiro_chamando_ap02
    elements:
      - type: custom:advanced-camera-card-menu-icon
        icon: mdi:phone
        priority: 90
        style:
          color: green
        tap_action:
          - action: perform-action
            data:
              entity_id: input_boolean.video_porteiro_chamando_ap02
            perform_action: input_boolean.turn_off
          - action: custom:advanced-camera-card-action
            advanced_camera_card_action: microphone_unmute
  - type: custom:advanced-camera-card-conditional
    conditions:
      - condition: state
        state: "off"
        entity: input_boolean.video_porteiro_chamando_ap02
      - condition: microphone
        connected: false
    elements:
      - type: custom:advanced-camera-card-menu-icon
        icon: mdi:phone-outgoing
        priority: 90
        style:
          color: green
        tap_action:
          - action: custom:advanced-camera-card-action
            advanced_camera_card_action: microphone_unmute
  - type: custom:advanced-camera-card-conditional
    conditions:
      - condition: state
        state: "on"
        entity: input_boolean.video_porteiro_chamando_ap02
    elements:
      - type: custom:advanced-camera-card-menu-icon
        icon: mdi:phone-ring
        priority: 89
        style:
          color: red
        tap_action:
          - action: perform-action
            data:
              entity_id: input_boolean.video_porteiro_chamando_ap02
            perform_action: input_boolean.turn_off
  - type: custom:advanced-camera-card-conditional
    conditions:
      - condition: state
        state: "off"
        entity: input_boolean.video_porteiro_chamando_ap02
      - condition: microphone
        connected: true
    elements:
      - type: custom:advanced-camera-card-menu-icon
        icon: mdi:phone-hangup
        priority: 89
        style:
          color: red
        tap_action:
          - action: custom:advanced-camera-card-action
            advanced_camera_card_action: microphone_disconnect
          - action: custom:advanced-camera-card-action
            advanced_camera_card_action: mute
profiles:
  - low-performance
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: "16:9"
```

**[REQUIRED] Description of problem:**

```
Logger: frontend.js.modern.202502140
Source: components/system_log/__init__.py:331
First occurred: 5:51:52 AM (1 occurrences)
Last logged: 5:51:52 AM

Uncaught error from Chrome WebView 132.0.6834.163 on Android 14 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. k (/hacsfiles/advanced-camera-card/zoomer-663c2456.js:1:2689) v (/hacsfiles/advanced-camera-card/zoomer-663c2456.js:1:5418) M (/hacsfiles/advanced-camera-card/zoomer-663c2456.js:1:6787) /hacsfiles/advanced-camera-card/zoomer-663c2456.js:1:7836
```

**[OPTIONAL] Last working release (if known):** N/A

**[OPTIONAL] Javascript errors shown in the web inspector:** N/A

**[OPTIONAL] Additional information:**

Apparently the same as https://github.com/dermotduffy/advanced-camera-card/issues/1217.
