### ISSUE TITLE
Add tap_action for entire card

### ISSUE THREAD

**Issue by Greminn** [dermotduffy/advanced-camera-card#1912]
Hi There, we have a tablet dashboard in which we have cameras - you can click anywhere on the camera card, and navigates to a different view with a large live video and some other info (vehicles etc), you can then click the large view camera card to navigate back to the default view. This works really well. 

Is there any way to add a tap_action to the entire card using advanced-camera-card? 

Thanks!

**Comment by dermotduffy** [comment]
Try `view.actions.tap_action` as shown in the [fully expanded reference](https://card.camera/#/configuration/view?id=fully-expanded-reference). Perhaps this is what you mean?

**Comment by Greminn** [comment]
> Try `view.actions.tap_action` as shown in the [fully expanded reference](https://card.camera/#/configuration/view?id=fully-expanded-reference). Perhaps this is what you mean?

Thanks for that, I had missed this part. Checking the reference, it does not let you know how to use tap_action as the docs just say "none". I tried as per other tap_actions, but this does not work as expected (e.g. does nothing).

```
view:
  default: live
  entity: camera.front_camera_substream
  tap_action:
    action: navigate
    navigation_path: /dashboard-tablet/front-camera?kiosk

```

**Comment by dermotduffy** [comment]
Your config is not quite right. Try this:

```yaml
view:
  default: live
  entity: camera.front_camera_substream
  actions:                   <-------------------------------------- ADDED
    tap_action:
      action: navigate
      navigation_path: /dashboard-tablet/front-camera?kiosk
```
