### ISSUE TITLE
how to display/link recordings

### ISSUE THREAD

**Issue by DomenicOtto** [dermotduffy/advanced-camera-card#1913]
I am have a question regarding the advanced camera card configuration in HA.
I have a Ring Video Doorbell integrated and it is recording to my HA in /config/video.
I want to show these recordings in the card next to the camera or whatever is possible.
However I cannot seem to make this work in any way.

Should it be possible or am I just looking for something that is not supported?

my current yaml looks like this - I can see the camera however no videos...
Would appreciate any help here.

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.03cabcc9_ring_mqtt
    live:
      show: true
      autoplay: true
      preload: true
    clips:
      show: true
      directory: /local/video/
      filename_template: ring_*.mp4
```
thank you.
