### ISSUE TITLE
Preload does not work with `go2rtc`

### ISSUE THREAD

**Issue by niker** [dermotduffy/advanced-camera-card#1914]
```yaml
card_version: 7.2.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
date: 2025-02-21T15:24:26.457Z
lang: en
timezone: Europe/Prague
git:
  hash: bb147a4
  build_date: Tue, 18 Feb 2025 04:14:32 GMT
  commit_date: Mon, 17 Feb 2025 20:13:21 -0800
ha_version: 2025.2.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01J4SNWJKJZTDH8A5CH09FE87T: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.cam_obyvak
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: cam_obyvak
      triggers:
        motion: false
        occupancy: false
        entities:
          - input_boolean.camswitch_obyvak
      image:
        mode: camera
    - camera_entity: camera.cam_schody
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: cam_schody
      triggers:
        motion: false
        occupancy: false
        entities:
          - input_boolean.camswitch_schody
      image:
        mode: camera
    - camera_entity: camera.cam_garaz
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: cam_garaz
      triggers:
        motion: false
        occupancy: false
        entities:
          - input_boolean.camswitch_garaz
      image:
        mode: camera
  performance:
    features:
      animated_progress_indicator: true
      card_loading_indicator: true
  dimensions:
    aspect_ratio: '16:9'
    aspect_ratio_mode: static
  view:
    camera_select: live
    triggers:
      show_trigger_status: false
      actions:
        trigger: live
      filter_selected_camera: false
    default_cycle_camera: false
    default_reset:
      interaction_mode: all
  live:
    show_image_during_load: true
    preload: true
    lazy_load: false
    controls:
      thumbnails:
        mode: none
      next_previous:
        style: chevrons
        size: 32
      builtin: false
      ptz:
        hide_zoom: true
        hide_home: true
    transition_effect: slide
    auto_mute:
      - microphone
  elements:
    - type: custom:advanced-camera-card-conditional
      conditions:
        - condition: view
          views:
            - live
            - image
        - condition: camera
          cameras:
            - camera.cam_garaz
        - condition: media_loaded
          media_loaded: true
      elements:
        - type: state-icon
          entity: input_boolean.kamera_garaz_snimat_zahradu
          style:
            position: absolute
            transform: translate(-50%, -50%) scale(110%)
            top: 93%
            left: 50%
          tap_action:
            action: toggle
  menu:
    buttons:
      mute:
        enabled: true
  status_bar:
    items:
      resolution:
        enabled: false
    popup_seconds: 2
```

**[REQUIRED] Description of problem:**

I have "Preload live view in background" enabled and "Live cameras are lazily loaded" disabled.
The 4 cameras stop and start the streams as I switch (swipe) between them instead of steadily playing all 4 streams in the background to be immediatelly available.

Tested on Chromium and Firefox browser and Android app, all behave the same.

When switching, the camera feed goes to the black iris logo and loads. All the streams should be running in parallel as it was before v7. Using WebRTC restream from Frigate via go2rtc.

**[OPTIONAL] Last working release (if known):**
Problem started with 7.0.0 or very shortly before that.

**[OPTIONAL] Javascript errors shown in the web inspector:**

No errors or warnings
```text
CARD-MOD 3.4.4 IS INSTALLED [card-mod.js:1:52519](https://homeassistant/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524344)
BROWSER_MOD 2.3.3 IS INSTALLED
    BrowserID: fe414c59-93fceb63 [browser_mod.js:385:6301](https://homeassistant/browser_mod.js?2.3.3)
AUTO-ENTITIES 1.13.0 IS INSTALLED [auto-entities.js:172:7850](https://homeassistant/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841130)
HUI-ELEMENT 1.1.2 IS INSTALLED <empty string> [hui-element.js:1:1813](https://homeassistant/hacsfiles/lovelace-hui-element/hui-element.js?hacstag=249942054180547)
vertical-stack-in-card
Version: 1.0.1 [vertical-stack-in-card.js:1:9](https://homeassistant/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833101)
  BUTTON-CARD  
 Version 4.1.2 [button-card.js:426:15087](https://homeassistant/hacsfiles/button-card/button-card.js?hacstag=146194325412)
LAYOUT-CARD 2.4.5 IS INSTALLED [layout-card.js:228:115](https://homeassistant/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866245)
 LOGBOOK-CARD  2.5.6 [logbook-card.js:472:185](https://homeassistant/hacsfiles/logbook-card/logbook-card.js?hacstag=216008446256)
 📷 Advanced Camera Card  7.2.1
```
