### ISSUE TITLE
Feature_Request: auto_mute "default"

### ISSUE THREAD

**Issue by snickers2k** [dermotduffy/advanced-camera-card#1915]
Live View plays sound all the time by default. 

I would like to have it muted by default, until actually selected.

smth like

```
live:
  auto_unmute:
    - selected
  auto_mute:
    - **default // true**
    - unselected
```
