### ISSUE TITLE
Auto play not consistently working with fullykiosk

### ISSUE THREAD

**Issue by Daniel-dev22** [dermotduffy/advanced-camera-card#1916]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.5.1
browser: >-
  Mozilla/5.0 (Linux; Android 15; SM-S938U1 Build/AP3A.240905.015.A2; wv)
  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/132.0.6834.166
  Mobile Safari/537.36 Home Assistant/2025.1.2-14946 (Android 15; SM-S938U1)
date: 2025-02-22T20:31:22.258Z
lang: en
timezone: America/New_York
git:
  hash: 43947b4
  build_date: Sun, 02 Feb 2025 00:09:40 GMT
  commit_date: Sat, 1 Feb 2025 16:08:32 -0800
ha_version: 2025.2.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      121894675fc2447d4c58c7cbe23d8009: 5.8.0/0.16.0-0083d09
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras_global:
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
  cameras:
    - camera_entity: camera.birdseye
  live:
    auto_play:
      - visible
    auto_pause:
      - hidden
  menu:
    buttons:
      frigate:
        enabled: true
```

**[REQUIRED] Description of problem:**

**[OPTIONAL] Last working release (if known):**

I tried both latest and 6.5.1 and still have an issue with auto play not working all the time with fully kiosk on my galaxy tab s7. 

This diagnostic isn't from that device but that's where I notice this issue. 

I notice because the tablet is on all the time and the screen turns off/on via an automation. Sometimes when the screen turns on the stream starts right away other times it's stuck on paused from when the screen was off. The fact it pauses when the screen is off is great but when I turn it on and the stream is visible I would hope that it would start playing immediately.

Previously I used webrtc card with the config option`intersection` 0.75 and never had this issue. I also used Birdseye and the stream was also webrtc and used go2rtc from frigate.

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

Interestingly I see a resource for both frigate card loaded and one for advanced camera card it seems that sometimes I noticed the card using latest version when it starts up and shows the version for a second and other times the older version. Not sure if that's related and if I should remove that frigate card resource
