### ISSUE TITLE
No Evensts/Snapshots/Clips in card - No media to display

### ISSUE THREAD

**Issue by hugalafutro** [dermotduffy/advanced-camera-card#1917]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases). ✅ 
- Please try clearing your browser cache. ✅ 

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.2.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/132.0.0.0 Safari/537.36
date: 2025-02-23T13:49:37.712Z
lang: en
timezone: Europe/London
git:
  hash: bb147a4
  build_date: Tue, 18 Feb 2025 04:14:32 GMT
  commit_date: Mon, 17 Feb 2025 20:13:21 -0800
ha_version: 2025.2.5
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JKTPD37PF9PR7MN34K0NQQMQ: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  view:
    actions:
      double_tap_action:
        action: custom:advanced-camera-card-action
        advanced_camera_card_action: fullscreen
    default: live
    default_cycle_camera: false
    camera_select: live
    theme:
      themes: []
  menu:
    buttons:
      clips:
        enabled: true
      snapshots:
        enabled: true
      download:
        enabled: true
      fullscreen:
        enabled: true
      media_player:
        enabled: false
      timeline:
        enabled: true
      camera_ui:
        enabled: false
      iris:
        enabled: true
        alignment: matching
        permanent: false
      display_mode:
        enabled: false
      screenshot:
        enabled: false
        permanent: true
      mute:
        enabled: true
        permanent: true
      recordings:
        enabled: false
    style: hidden
    position: top
    alignment: right
  live:
    preload: false
    controls:
      thumbnails:
        mode: none
        events_media_type: snapshots
      next_previous:
        style: none
    transition_effect: slide
    draggable: false
    lazy_unload:
      - unselected
      - hidden
    auto_mute:
      - hidden
      - unselected
  dimensions:
    aspect_ratio_mode: dynamic
  cameras:
    - camera_entity: camera.bedroom
      camera_name: bedroom_camera
      frigate:
        camera_name: bedroom_camera_sub
        url: http://172.17.0.1:5000
      reolink:
        media_resolution: low
        url: http://192.168.1.220
      go2rtc:
        modes: []
      live_provider: go2rtc
    - camera_entity: camera.bedroom_reo_sub
      reolink:
        media_resolution: low
      title: Reolink
  media_viewer:
    lazy_load: true
    controls:
      next_previous:
        style: thumbnails
      thumbnails:
        show_timeline_control: true
    draggable: false
    transition_effect: slide
    display:
      mode: single
  image:
    mode: camera
  timeline:
    show_recordings: false
    style: stack
    events_media_type: all
  media_gallery:
    controls:
      thumbnails:
        show_timeline_control: false
        size: 128
  performance:
    features:
      media_chunk_size: 500
  status_bar:
    style: popup
    position: bottom
    popup_seconds: 3
```

**[REQUIRED] Description of problem:**

I changed nothing in my setup, it used to work normally, but now I get this:
![Image](https://github.com/user-attachments/assets/69f218a6-7997-4bac-8752-78f8199e6efc)
timeline is empty:
![Image](https://github.com/user-attachments/assets/99b9c6a6-07eb-4e90-bccf-ad7515e8df6a)
but in both firgate web ui and ha/media/frigae they work:
![Image](https://github.com/user-attachments/assets/01face9f-3dcf-4f61-9c2a-9a5db7e850f2)
![Image](https://github.com/user-attachments/assets/a00684c2-42c5-4e91-95b3-d0eb011511ad)

**[OPTIONAL] Last working release (if known):**
I can't remember I don't look t the snaps in ha often

**[OPTIONAL] Javascript errors shown in the web inspector:**
no output in console when clicking on either clips/snaps/timeline
this shows up when the card loads before the camera stream pops in:
```text
card-1ab50869.js:75 jo: Failed to receive response from Home Assistant for request
    at Uv (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/card-1ab50869.js:75:186536)
    at async https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/engine-frigate-56a56cf5.js:1:4233
    at async L._getPTZCapabilities (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/engine-frigate-56a56cf5.js:1:4213)
    at async L._initializeCapabilities (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/engine-frigate-56a56cf5.js:1:3566)
    at async L.initialize (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/engine-frigate-56a56cf5.js:1:2558)
    at async Se.createCamera (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/engine-frigate-56a56cf5.js:3:11320)
    at async https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/card-1ab50869.js:79:220
    at async Promise.all (index 0)
    at async gg (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/card-1ab50869.js:75:144201)
    at async vy._initializeCameras (https://[REDACTED].ui.nabu.casa/hacsfiles/advanced-camera-card/card-1ab50869.js:79:184) 
{request: {…}, response: {…}}
request
: 
camera
: 
"bedroom_camera_sub"
id
: 
42
instance_id
: 
"frigate"
type
: 
"frigate/ptz/info"
[[Prototype]]
: 
Object
response
: 
code
: 
"frigate_error"
message
: 
"API error whilst retrieving PTZ info for camera bedroom_camera_sub for Frigate instance frigate"
[[Prototype]]
: 
Object
[[Prototype]]
: 
Object
```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
You have the card configured with 2 cameras, which one is the issue with? What is the camera name in Frigate? If the camera entity is a "normal" Frigate entity, remove the `camera_name` properties and the card will auto-detect the proper name -- I am guessing you are simply telling the card to use name X, but Frigate doesn't know what that is.

**Comment by hugalafutro** [comment]
The reolink camera can be ignored, it's there just as a backup if the frigate vm is down or w/e, it is just a stream. the card works with all the manual values removed, I just added them during testing.

Removing the camera name does fix the issue, however if I remove the camera name I lose audio in advanced-camera-card. How can I have both? More details below.

I added the audio restreaming as per the docs (https://docs.frigate.video/configuration/live#audio-support) thus having this in my `config.yml`
```
go2rtc:
  streams:
    bedroom_camera:
      - ffmpeg:http://192.168.1.220/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[REDACTED]&password=[REDACTED]#video=copy#audio=copy#audio=opus
      - ffmpeg:bedroom_camera#audio=opus
    bedroom_camera_sub:
      - ffmpeg:http://192.168.1.220/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=[REDACTED]&password=[REDACTED]#video=copy#audio=copy#audio=opus
      - ffmpeg:bedroom_camera_sub#audio=opus
  webrtc:
    candidates:
      - stun:8555
      - 192.168.1.101:8555

cameras:
  bedroom:
    live:
      stream_name: bedroom_camera_sub
    ffmpeg:
#      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroom_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```
This config ensured audio worked immediately upon loading Frigate web-ui, but it still didn't work in advanced-camera-card. The only way to get audio in advanced-camera-card is to define the name as either `bedroom_camera` or `bedroom_camera_sub` as those are the 2 go2rtc restreams with audio. Immediately upon changing the value or removing it the mute/unmute button disappears from the advanced-camera-card, reappearing immediately upon defining the camera name as eithe rof the 2 values.

**Comment by dermotduffy** [comment]
Is there a particular reason you have the streams named differently from the camera you wanted them associated with?

```yaml
go2rtc:
  streams:
    bedroom_camera:      <----------------------- NOT THE SAME
      - ffmpeg:http://192.168.1.220/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[REDACTED]&password=[REDACTED]#video=copy#audio=copy#audio=opus
      - ffmpeg:bedroom_camera#audio=opus
    bedroom_camera_sub:
      - ffmpeg:http://192.168.1.220/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=[REDACTED]&password=[REDACTED]#video=copy#audio=copy#audio=opus
      - ffmpeg:bedroom_camera_sub#audio=opus
  webrtc:
    candidates:
      - stun:8555
      - 192.168.1.101:8555

cameras:
  bedroom:                 <----------------- AS THIS
```

If you rename the go2rtc as just `bedroom` this might just work, although your cameras block (for advanced camera card) looks significantly over complicated. It can possibly be reduced to just:


```yaml
  cameras:
    - camera_entity: camera.bedroom
      frigate:
        url: http://172.17.0.1:5000
      live_provider: go2rtc
```

**Comment by hugalafutro** [comment]
I'm a bit confused here, the go2rtc defines 2 streams named `bedroom_camera` `bedroom_camera_sub` each with the audio restream of the same nae (otherwise audio does not work)

Then I define 1 camera named bedroom, which ingests the 2 streams as 2 inputs, 1 for record, 1 for detect, as per the Frigate docs for Reolink camera (the camera block is a literal copy & paste form the doc)

So, if I rename the go2rtc  bedroom_camera to bedroom then I have to rename the ffmpeg audio restream too no? the ` - ffmpeg:bedroom#audio=opus` and the path in the camera block as well no? `- path: rtsp://127.0.0.1:8554/bedroom?video=copy&audio=aac`

But I wish to stream audio+video from the _sub stream (low bandwith) and record and events from the hd stream (high bandwith), which means I would have to change the names for the _sub stream? But won't that then cause Frigate to use it for recordings and events?

**Comment by dermotduffy** [comment]
If you don't want to rename anything, you can ask the card to use a different stream with any arbitrary name:

```yaml
  cameras:
    - camera_entity: camera.bedroom
      frigate:
        url: http://172.17.0.1:5000
      live_provider: go2rtc
      go2rtc:
        stream: bedroom_camera
```
