### ISSUE TITLE
Version flip between 7.2.1 and 7.0.0

### ISSUE THREAD

**Issue by francescopeloi** [dermotduffy/advanced-camera-card#1919]
**Card diagnostic information:**

```yaml
card_version: 7.0.0
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/132.0.0.0 Safari/537.36
date: 2025-02-24T09:22:52.930Z
lang: en
timezone: Europe/Vatican
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.2.5
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      3f32dde608d9d2653462afcc83306c6e: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.giardino
  view:
    default: clips
    update_seconds: 60
    scan:
      enabled: true
    update_cycle_camera: false
  media_gallery:
    controls:
      thumbnails:
        show_timeline_control: false
        show_favorite_control: false
        size: 175
```

**Description of problem:**

I always update to your latest card version. I am seeing a weird downgrade happening out of nowhere, as you see I am on 7.0.0 now, even though I upgrade to all the versions till 7.2.1, and HA is not asking me to update to your latest version.

I cleared the browser cache before, and it went back to 7.2.1, but then today, I am again back to 7.0.0 (without having updated anything). It seems that it's getting the old version from somewhere, but I really don't know where since I cleared the browser cache multiple times. This is actually happening on my mobile too.

Only me?

**Comment by francescopeloi** [comment]
now I've just reloaded the page and I am again on 7.2.1

```yaml
card_version: 7.2.1
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/132.0.0.0 Safari/537.36
date: 2025-02-24T09:29:33.303Z
lang: en
timezone: Europe/Vatican
git:
  hash: bb147a4
  build_date: Tue, 18 Feb 2025 04:14:32 GMT
  commit_date: Mon, 17 Feb 2025 20:13:21 -0800
ha_version: 2025.2.5
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      3f32dde608d9d2653462afcc83306c6e: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.ingresso_civico_55
  view:
    default: clips
  media_gallery:
    controls:
      thumbnails:
        show_timeline_control: false
        show_favorite_control: false
        size: 175
```
