### ISSUE TITLE
go2rtc setup is adding a # to stream URL

### ISSUE THREAD

**Issue by cjd7734** [dermotduffy/advanced-camera-card#1922]
I am trying to setup direct access to unifi camera's and display them on the advanced camera card. The issues I am running into is the URL that is created to access the card stream has an # in not a / which is causing the stream not to load.  I can access the streams from the unifi protect integration, but it still adds some latency and i can not access all of the streams. 

I would expect 
http://10.0.1.205:1984/G4_Test_HR

and I am getting 
http://10.0.1.205:1984#G4_Test_HR

http://10.0.1.205:1984/G4_Test_HR stream works for opening the RTSP stream for me 

debug info 
```yaml
card_version: 7.2.1
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/133.0.0.0 Safari/537.36
date: 2025-02-28T04:22:51.650Z
lang: en
timezone: America/New_York
git:
  hash: bb147a4
  build_date: Tue, 18 Feb 2025 04:14:32 GMT
  commit_date: Mon, 17 Feb 2025 20:13:21 -0800
ha_version: 2025.2.5
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - go2rtc:
        stream: G4_Test_HR
        url: http://10.0.1.205:1984/
        modes:
          - mse
      live_provider: go2rtc
```
