### ISSUE TITLE
PTZ controls not visible in lovelave Home Assistant card

### ISSUE THREAD

**Issue by Baldilocks47** [dermotduffy/advanced-camera-card#1932]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```
I've added the default frigate menu button to the card, but long/short clicking it unfortunately does nothing.. I include below the config for the card instead
```
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.reolink_tiltpan
menu:
  style: hover
  position: left
  buttons:
    ptz_controls:
      enabled: true
      alignment: matching
      permanent: true
    frigate:
      enabled: true
    ptz_home:
      enabled: false
    fullscreen:
      alignment: matching
    timeline:
      enabled: false
    snapshots:
      enabled: false
    mute:
      enabled: true
live:
  controls:
    ptz:
      mode: "on"
      position: bottom-right
      orientation: horizontal
      hide_pan_tilt: false
  ptz:
    data_left:
      entity_id: camera.reolink_tiltpan
      direction: left
      speed: 5
    data_right:
      entity_id: camera.reolink_tiltpan
      direction: right
      speed: 5
    data_up:
      entity_id: camera.reolink_tiltpan
      direction: up
      speed: 5
    data_down:
      entity_id: camera.reolink_tiltpan
      direction: down
      speed: 5
  preload: true
view:
  keyboard_shortcuts:
    ptz_left:
      key: ArrowLeft
    ptz_right:
      key: ArrowRight
    ptz_up:
      key: ArrowUp
    ptz_down:
      key: ArrowDown
    ptz_zoom_in:
      key: +
    ptz_zoom_out:
      key: "-"
    ptz_home:
      key: h
status_bar:
  popup_seconds: 0
  style: none
grid_options:
  columns: full
```

**[REQUIRED] Description of problem:**

I am suffering an issue with my Reolink E1 outdoor PTZ cam. PTZ controls work fine via firmware in web browser. In Frigate in HA I can use PTZ controls, but on lovelace card I can toggle on PTZ controls however nothing appears on-screen. I've tried on several web browsers on different devices, all the same.

I have tried multiple configurations of orientation of the PTZ controls, no difference. I've toggled PTZ controls in the web UI under "Menu" and "Live", still no change. I've updated the configuration manually in the config file and still nothing.

**[OPTIONAL] Last working release (if known):**
N/A

**[OPTIONAL] Javascript errors shown in the web inspector:**

```Not applicable

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
> I am suffering an issue with my Reolink E1 outdoor PTZ cam. PTZ controls work fine via firmware in web browser. In Frigate in HA I can use PTZ controls, but on lovelace card I can toggle on PTZ controls however nothing appears on-screen. I've tried on several web browsers on different devices, all the same.

When you say "In Frigate in HA I can use PTZ controls", what are you referring to? Do you just mean the Frigate interface (not HA), or something else?

Is `camera.reolink_tiltpan` a Frigate entity, or a reolink entity?

> [Config]

There are also a number of issues with your config, but my advice will depend on your answer to the above question.

Minimally:

```
[...]
live:
  controls:
    ptz:
      mode: "on"
      position: bottom-right
      orientation: horizontal
      hide_pan_tilt: false
  ptz: <----------------------------- This should be with the camera it refers to, not under `live`, but even still it looks invalid to me.
    data_left:
[...]
```

**Comment by dermotduffy** [comment]
> It is a Frigate entity in HA

For Frigate entities, PTZ should just work out of the box, with no configuration beyond something like:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.this_is_a_frigate_camera
```

> Blue circle in the top right of the card never seems to go away. The info message suggests the stream has not yet loaded, but the feed is live and is streaming

This is your problem, and you need to fix this first. PTZ will only show up when the stream loads. You are likely just getting screenshots refreshing 1/second, and not the real stream. 

Troubleshooting steps: https://card.camera/#/troubleshooting?id=stream-does-not-load

**Comment by Baldilocks47** [comment]
I can get the blue circle to go away if I select "Home Assistant images", which I think must just be static images akin to what I was seeing with the blue circle, rather than a live stream? 

Good news is the PTZ controls now appear!

Now I just need to figure out how to fix the stream... 

I appreciate the fix is more likely in my Frigate config, rather than the card itself. I've read the documentation but tbh am a bit overwhelmed by all the options and what they mean in terms of getting a working/stable config.. 

Current Frigate config below:
```go2rtc:
  streams:
    reolink_doorbell:
      - rtsp://go2rtc:x@10.0.1.2:554/h264Preview_01_main#audio=pcm#audio=volume
      - ffmpeg:https://10.0.1.2:1935/flv?port=444&app=bcs&stream=channel0_main.bcs&user=go2rtc&password=xx#video=copy#audio=copy#audio=opus
    annke:
      - rtsp://go2rtc:xx@10.0.1.5:554/cam/realmonitor?channel=1&subtype=1
    reolink_tiltpan:
      - rtsp://admin:xx@10.0.0.38:554/h264Preview_01_main#audio=pcm#audio=volume
      - ffmpeg:https://10.0.0.38:1935/flv?port=443&app=bcs&stream=channel0_main.bcs&user=admin&password=xx#video=copy#audio=copy#audio=opus
    reolink_fixed1:
      - rtsp://admin:xx@10.0.0.39:554/h264Preview_01_main#audio=pcm#audio=volume
      - ffmpeg:https://10.0.0.39:1935/flv?port=443&app=bcs&stream=channel0_main.bcs&user=admin&password=xx#video=copy#audio=copy#audio=opus
    reolink_fixed2:
      - rtsp://admin:xx@10.0.0.40:554/cam/realmonitor?channel=1&subtype=1

  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"
    log_level: debug
  webrtc:
    candidates:
      - 10.0.1.0:8555
      - stun:8555

mqtt:
  host: 10.0.1.0
  port: 1883
  topic_prefix: frigate
  user: homeassistant
  password: xx
  stats_interval: 60

cameras:
  reolink_doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:xx@10.0.1.2:554/h264Preview_01_main
          roles:
            - record
        - path: 
            https://10.0.1.2:444/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=go2rtc&password=xx
          roles:
            - detect
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
    zones:
      path:
        coordinates: 0.614,0.512,0.155,1,0.642,0.999,0.696,0.507
        loitering_time: 1
        objects: person
  annke:
    enabled: true
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://go2rtc:xx@10.0.1.5:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - record
  reolink_tiltpan:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xx@10.0.0.41:554/h264Preview_01_main
          roles:
            - record
        - path: 
            https://10.0.0.41:443/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xx
          roles:
            - detect
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic-audio-copy
    onvif:
      host: 10.0.0.41
      port: 8000
      user: admin
      password: xx
      autotracking:
        enabled: true
        zooming: disabled
        calibrate_on_startup: false
        zoom_factor: 0.3
        track:
          - person
          - cat
          - dog
          - bird
        required_zones:
          - field_ground
        return_preset: field_main
        timeout: 20

    detect:
      enabled: true
    zones:
      Field_Ground:
        coordinates: 0,0.504,1,0.474,1,0.742,0,0.891
        loitering_time: 0
        objects:
          - bird
          - cat
          - dog
          - person
      Field_Sky:
        coordinates: 0,0,1,0,1,0.397,0,0.431
        loitering_time: 0
        objects: bird
      Field_Trees:
        coordinates: 0,0.401,1,0.379,1,0.532,0,0.55
        loitering_time: 0
        objects:
          - bird
          - cat
          - dog
          - person
  reolink_fixed1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xx@10.0.0.39:554/h264Preview_01_main
          roles:
            - record
        - path: 
            https://10.0.0.39:443/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xx
          roles:
            - detect
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
  reolink_fixed2:
    enabled: true
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://admin:xx@10.0.0.40:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - record

objects:
  track:
    - person
    - cat
    - dog
    - bird

  filters:
    person:
      threshold: 0.7

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 800
  height: 400

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  alerts:
    retain:
      days: 2
  detections:
    retain:
      days: 2

logger:
  logs:
    frigate.ptz.onvif: debug
version: 0.15-1
```

**Comment by Baldilocks47** [comment]
The stream doesn't load when accessing the entity as you describe - I just get a static image.

I tried it for camera.reolink_doorbell and got the same. However when I did camera.annke, the stream loaded fine.

**Comment by dermotduffy** [comment]
> The stream doesn't load when accessing the entity as you describe - I just get a static image.

OK, then I'm afraid your issue has nothing to do with the card (as your stream doesn't load even without it). I'd check your developer console (F12) and see if there's something useful in there, or try the general Home Assistant forums.

You could also try a different live provider, since `camera.reolink_tiltpan` is a Frigate entity, you might try using the `go2rtc` live provider like this:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.reolink_tiltpan
    live_provider: go2rtc
```

... this uses a different approach entirely to provide you the live stream. Note though that your underlying Home Assistant issue won't "go away" (but the card might work).
