### ISSUE TITLE
PTZ controls not out of the box :(

### ISSUE THREAD

**Issue by hohaha045** [dermotduffy/advanced-camera-card#1933]
I am using a reolink e1 zoom v2 camera with frigate 0.15.0-cea210d, Advanced Camera Card v7.3.1

and the ptz control/ icon is not show up on the card in both front and back end.

<img width="991" alt="Image" src="https://github.com/user-attachments/assets/3571a5f0-e977-4d96-a30f-80d0555bad93" />

I can control the ptz no problem in frigate UI 

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/04632a29-a233-40c0-8518-18c55942c267" />

Tried to force it by using 
```
live:
  controls:
    ptz:
    mode:"on"

```

my full config:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.guardian
view:
  default: live
menu:
  style: outside
  alignment: right
live:
  layout:
    fit: contain
  controls:
    ptz:
      mode: "on"
      position: bottom-left
```

and is it any way to move the camera to a preset location just like frigate ?

<img width="714" alt="Image" src="https://github.com/user-attachments/assets/e47efc17-e5d8-4021-94c1-2258bc61ca41" />
