### ISSUE TITLE
Gallery incorrectly hides `outside` menu

### ISSUE THREAD

**Issue by Obermayr-M** [dermotduffy/advanced-camera-card#1937]
**Card diagnostic information:**

```
card_version: 7.3.2
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36
date: 2025-03-04T14:30:22.054Z
lang: en
timezone: Europe/Vienna
git:
  hash: 3b77b11
  build_date: Tue, 04 Mar 2025 05:00:09 GMT
  commit_date: Mon, 3 Mar 2025 20:59:01 -0800
ha_version: 2025.2.5
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      xxxxxxxxxxxxxxxxxxxxxxxxxx: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: cam_a
      live_provider: go2rtc
      frigate:
        url: XXX.XXX.XXX.XXX:5000
      go2rtc:
        modes:
          - webrtc
        stream: cam_a_sub
      triggers:
        motion: false
        entities:
          - binary_sensor.cam_a_person_occupancy
        occupancy: false
      reolink: {}
  view:
    camera_select: live
    default: live
    interaction_seconds: 60
    triggers:
      show_trigger_status: false
      untrigger_seconds: 3
    default_cycle_camera: false
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
  menu:
    buttons:
      microphone:
        enabled: false
        priority: 50
        alignment: matching
        type: toggle
      mute:
        enabled: true
      substreams:
        enabled: true
      live:
        enabled: true
      snapshots:
        enabled: true
      recordings:
        enabled: true
      image:
        enabled: false
      iris:
        enabled: true
    style: outside
    position: bottom
  live:
    preload: true
    lazy_load: true
    microphone:
      disconnect_seconds: 60
      always_connected: false
    controls:
      thumbnails:
        size: 150
      ptz:
        hide_zoom: true
        hide_home: true
  performance:
    features:
      media_chunk_size: 250
  media_gallery:
    controls:
      thumbnails:
        size: 150
      filter: {}
  media_viewer:
    controls:
      thumbnails:
        size: 150
  timeline:
    controls:
      thumbnails:
        size: 150
```

**Description of problem:**
I am using the advanced camera card in a HA grid card@ top position (panel view (single card)).

Already with release 7.3.1 I recognized a missing menu bar, when I switched to any gallery view (clips, screenshots, recordings). It looks like the card size changes in gallery view and shifts out the menu bar which is located at the bottom permanently.
--> In the HASS android app it is not possible, to go back to camera view (except I click on a video or screen shot, then the menu bar appears again.
--> In the web browser a small 2nd scroll bar appears. Scrolling down makes the menu bar visible again.

**Last working release (if known):**
7.1.x (sure)
7.2.x (more or less sure)

**Additional information:**
Before scrolling down: No menu
![Image](https://github.com/user-attachments/assets/58b9a59f-5b6f-4672-9b31-1b2acaaf02dc)

After scrolling down: Menu
![Image](https://github.com/user-attachments/assets/cddc81e8-bb1a-4f72-b0f0-5e7bce8b84f8)

Not sure if it is a feature or a bug, I am just sure that it is a new behavior.
