### ISSUE TITLE
Reolink Duo2V - Stream never loads, all other cameras work fine. m3u8 issue?

### ISSUE THREAD

**Issue by baudneo** [dermotduffy/advanced-camera-card#1939]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.3.2
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/133.0.0.0 Safari/537.36
date: 2025-03-05T00:23:24.772Z
lang: en
timezone: America/Edmonton
git:
  hash: 3b77b11
  build_date: Tue, 04 Mar 2025 05:00:09 GMT
  commit_date: Mon, 3 Mar 2025 20:59:01 -0800
ha_version: 2025.2.5
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JMB3N1D166G9ETY7K7PAZBPB: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.alley_2
  elements:
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:menu
      items:
        - title: Light
          icon: mdi:light-flood-down
          entity: light.duo_2v_alley_floodlight
          tap_action:
            action: toggle
        - title: Siren
          entity: siren.duo_2v_alley_siren
          icon: mdi:alarm-light-outline
          tap_action:
            action: toggle
```

**[REQUIRED] Description of problem:**

Trying to view a reolink duo 2v in the advanced-camera-card and it does not work (only the 1 image every second), crashes hass eventually and continuously throws JS errors. m3u8 returns 524 and the stream proxy also throws errors.

Hass is exposed via cloudflare with TLS. STUN 8555 is port forwarded to the frigate host. Frigate itself can play the stream, ZoneMinder as well, HASS can't.

**[OPTIONAL] Last working release (if known):** First deployment

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

           GET https://<REDACTED>/api/hls/ef6a2160b5546b8ffc0717e224a732e6b2966ae8d78ec7a1da767a4d0467a9ac/master_playlist.m3u8 524        
            
           GET https://<REDACTED>/api/camera_proxy/camera.alley_2?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxM2VkZWY0NjBjMTM0MDgwOTlkMDcyYWU0YWEyYjdkYiIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuYWxsZXlfMiIsInBhcmFtcyI6W10sImlhdCI6MTc0MTA3NjUxNiwiZXhwIjoxNzQxMDc2NTQ2fQ.<REDACTED>&width=0&height=0 403 (Forbidden)
home:1 Uncaught (in promise) {code: 'not_found', message: 'Subscription not found.'}Understand this errorAI
home?edit=1:1 [Report Only] Refused to load media from 'blob:https://<REDACTED>/bf7505e5-d4fc-4d8b-a178-48e6bbcc19c4' because it violates the following Content Security Policy directive: "media-src 'none'".
            
            
           GET https://<REDACTED>/api/hls/ef6a2160b5546b8ffc0717e224a732e6b2966ae8d78ec7a1da767a4d0467a9ac/master_playlist.m3u8 524
           GET https://<REDACTED>/api/hls/ef6a2160b5546b8ffc0717e224a732e6b2966ae8d78ec7a1da767a4d0467a9ac/master_playlist.m3u8 524
            
            
           GET https://<REDACTED>/api/hls/ef6a2160b5546b8ffc0717e224a732e6b2966ae8d78ec7a1da767a4d0467a9ac/master_playlist.m3u8 524
            
           GET https://<REDACTED>/api/hls/ef6a2160b5546b8ffc0717e224a732e6b2966ae8d78ec7a1da767a4d0467a9ac/master_playlist.m3u8 524
```

**[OPTIONAL] Additional information:**
