### ISSUE TITLE
Full card snapshot gallery

### ISSUE THREAD

**Issue by templeowls21** [dermotduffy/advanced-camera-card#1940]
I'm curious if this is possible using the card. Essentially, I want the card to show full snapshots across all my cameras. This way, I can quickly see the latest snapshots and swipe from snapshot to snapshot.

I was able to get the below, but I was hoping that each snapshot could be full card rather than all of them on one view.

Is this possible?

![Image](https://github.com/user-attachments/assets/73c75aa2-9fe0-4493-885f-88d9efa9126d)

`type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.driveway
  - camera_entity: camera.mudroom
view:
  default: snapshots`

**Comment by dermotduffy** [comment]
I'm not sure exactly what you mean, but maybe it's this:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.driveway
    dependencies:
      all_cameras: true
  - camera_entity: camera.mudroom
view:
  default: snapshot
```

This will show you the recent recent snapshot (not the gallery of snapshot**S**), and makes all other cameras depend on `camera.driveway` so their events will get shown together.
