### ISSUE TITLE
Cloudflare | Https stream in card

### ISSUE THREAD

**Issue by apizzocolo** [dermotduffy/advanced-camera-card#1941]
I have an issue that I believe is related to the Cloudflare tunnel.

I have installed go2rtc, and when I connect via the web to Home Assistant (HA), I can correctly view the stream directly through the Cloudflare tunnel.

This is my go2rtc configuration:

streams:
  via_monte:
    - rtsp://User:Password@172.16.10.230:554/Streaming/Channels/101
    - isapi://User:Password@172.16.10.230:80/

api:
  listen: ":1984" # HTTP API
  '# username: "user" # Remove if Cloudflare Zero Trust is enabled
  '# password: "pass" # Remove if Cloudflare Zero Trust is enabled
  origin: "*" # Allows remote access
  tls_listen: ":1985" # Enables HTTPS if a secure connection is needed
  '# tls_cert: /ssl/cert.pem # Let's Encrypt certificate (if available)
  '# tls_key: /ssl/certkey.pem

I tried downloading the origin certificate from Cloudflare and then commenting it out, but it still doesn’t work.

Issue with configuring the stream in the camera card:

I am unable to configure the stream in the camera card:

```yaml
type: custom:advanced-camera-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      url: https://172.16.10.200:1985/stream.html
      stream: via_monte
      modes:
        - webrtc
```

Any ideas on how to resolve this issue?

AP

**Comment by dermotduffy** [comment]
The card doesn't know, or care, if your URL is Cloudflare or not. It just needs to be able to access that `go2rtc` URL.

**Comment by dermotduffy** [comment]
Looks like you're already close, but with some caveats:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    live_provider: go2rtc
    go2rtc:
      url: https://PATH_TO_GO2RTC:1984
```

... should work, on the assumption that that PATH is actually accessible from your browser. Note: If you use `http` and not `https`, you will only be able to access Home Assistant over `http` or your browser will complain about mixing `http` content on a `https` page.

**Comment by dermotduffy** [comment]
See: [documentation](https://card.camera/#/configuration/cameras/live-provider?id=go2rtc).

**Comment by dermotduffy** [comment]
Let me know if this doesn't work.

**Comment by dermotduffy** [comment]
Frigate card is just the old name for Advanced Camera Card. Same thing :-) The docs link above are for both.

**Comment by Fivedark** [comment]
I have the same issue, also trying to add a HikVision intercom to an Advanced Camera Card via go2rtc using Cloudflare.

The following stream URL is working like expected: https://my-domain.net/api/hassio_ingress/nZqmhf4Zb9KC6otDYW7mtpDfh4z0NfO9_ARfjh7el-E/webrtc.html?src=klingel&media=video+audio+microphone

But it's not working over: https://my-domain.net:1984 (or any other port)

Also, I don't know where to get the `camera_entity`. Is that even necessary?

My configuration looks like this at the moment, but I tried already a lot of different options:
```
type: custom:advanced-camera-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      url: https://my-domain.net/api/hassio_ingress/nZqmhf4Zb9KC6otDYW7mtpDfh4z0NfO9_ARfjh7el-E/webrtc.html?src=klingel&media=video+audio+microphone
      stream: klingel
```
The following message appears, if I click on the blue circle in the upper right corner of the video element:

> The video stream has not yet loaded. This is could for any number of reasons. If configured (and by default), there will be an image refreshing every second until the stream loads correctly . [Check troubleshooting](https://card.camera/#/troubleshooting?id=stream-does-not-load)

I would be very happy to receive helpful tips.
