### ISSUE TITLE
How to disable events popup overlay?

### ISSUE THREAD

**Issue by soonerfan237** [dermotduffy/advanced-camera-card#1943]
How can I disable this popup drawer that shows alerts for cameras?

<img width="550" alt="Image" src="https://github.com/user-attachments/assets/f5cd6f6b-cd64-42b4-9f47-437710639f1f" />

**Comment by dermotduffy** [comment]
```yaml
live:
  controls:
    thumbnails:
      mode: none
```
