### ISSUE TITLE
Status bar duplicate message

### ISSUE THREAD

**Issue by mark7463** [dermotduffy/advanced-camera-card#1948]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.3.3
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
date: 2025-03-07T09:06:14.048Z
lang: en
timezone: Asia/Singapore
git:
  hash: 473ac5b
  build_date: Thu, 06 Mar 2025 15:36:43 GMT
  commit_date: Thu, 6 Mar 2025 07:35:22 -0800
ha_version: 2025.2.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JCNTKH40W2NQ3G56AK8WWSQS: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.01gate
  status_bar:
    style: overlay
  automations:
    - conditions:
        - condition: state
          entity: input_boolean.booleantrue
          state: 'on'
      actions:
        - action: custom:advanced-camera-card-action
          advanced_camera_card_action: status_bar
          status_bar_action: add
          items:
            - type: custom:advanced-camera-card-status-bar-icon
              icon: mdi:alarm-light
              exclusive: true
            - type: custom:advanced-camera-card-status-bar-string
              string: Intruder detected!
              expand: true
              exclusive: true
              sufficient: true
      actions_not:
        - action: custom:advanced-camera-card-action
          advanced_camera_card_action: status_bar
          status_bar_action: reset


```

**[REQUIRED] Description of problem:**
I tried the dynamic status bar example from the docs (https://card.camera/#/examples?id=status-bar), only changing the trigger to a boolean helper. The status bar I get has a duplicate message string and icon. The extra set sometimes takes a few seconds to appear.

![Image](https://github.com/user-attachments/assets/9ca8bdeb-bb5f-4dc7-8cc7-1833eb6db372)

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
