### ISSUE TITLE
webrtc/go2rtc not displaying when on mobile network

### ISSUE THREAD

**Issue by Daz42** [dermotduffy/advanced-camera-card#1951]
- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
Upgraded to the latest version
- Please try clearing your browser cache.
Cleared

**[REQUIRED] Card diagnostic information:**

```

```

I have tried to long press the Iris menu while on a mobile network but the card is not generating any diagnostic data.

**[REQUIRED] Description of problem:**

I have a card setup to view a webrtc stream through go2rtc. While it works perfectly while connected to WiFi (I've tried 2 different locations), the card will not load the video stream when connected to a mobile data network. I have tried both on a MacBook and iPhone.

My card:

```yaml
type: custom:advanced-camera-card
cameras:
  - go2rtc:
      stream: millersleftofhouse
      modes:
        - webrtc
      url: https://myhost.mydomain:4443
    live_provider: go2rtc
```

I can on both my MacBook and iPhone while on Mobile data go straight to the url: https://myhost.mydomain:4443, select the stream and view it without any issues.

**Comment by dermotduffy** [comment]
The card does not know or care whether you're on WiFi or remote, so this is very unlikely to be an issue with the card itself and much more likely to be a networking issue.

Are you using Naba Casa? If yes, [this issue might be relevant to you](https://github.com/dermotduffy/advanced-camera-card/issues/1832). If not, I'd suggest opening your developer console (usually F12) on your macbook, when on mobile data, and see if you get any network errors shown on the console that might hint at where your issue is.

**Comment by Daz42** [comment]
I'm not using Nabu Casa. I'm using CloudFlare - on Wifi or on mobile data. The URL goes out onto the public internet and through my private firewall. I'll read through the link you gave me but it doesn't look like that issue is resolved. I'l try the F12 route and get back to you

**Comment by dermotduffy** [comment]
Yes, the Naba Casa issue is not understood. Since you're not using that service though, this _should_ work just fine. Let me know what you find on the console.

PS: Please try again on the diagnostics. Try clicking on the iris normally first, then click and hold down for a few seconds.

**Comment by Daz42** [comment]
Something interesting which may be related. When connected to WiFi - connecting to a stream directly througg go2rtc, the video is RTC. When doing the same thing on mobile data, the video is MSE. No idea why the switch. Can I force it to use RTC?

**Comment by Daz42** [comment]
```
card_version: 7.3.3
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/17.6 Safari/605.1.15
date: 2025-03-08T22:40:04.146Z
lang: en_GB
timezone: Europe/London
git:
  hash: 473ac5b
  build_date: Thu, 06 Mar 2025 15:36:43 GMT
  commit_date: Thu, 6 Mar 2025 07:35:22 -0800
ha_version: 2025.3.0
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - go2rtc:
        stream: millersleftofhouse
        modes:
          - webrtc
        url: https://ukoxfpod01-cam.globalconnecter.net:4443
      live_provider: go2rtc
  live:
    preload: true
```

I only seem to be able to get this when the card is streaming video.

**Comment by dermotduffy** [comment]
> Can I force it to use RTC?

You already should be since you are listing `webrtc` as the only acceptable mode. Are you saying the card is giving you an MSE stream with this configuration? Mind taking a screenshot?

**Comment by Daz42** [comment]
Ok, so found the fix:

```
type: custom:advanced-camera-card
cameras:
  - go2rtc:
      stream: millersleftofhouse
      modes:
        - webrtc
      url: https://myhost.mydomain:4443
    live_provider: go2rtc
```

If I remove

```
      modes:
        - webrtc
```

So my yaml looks like this:

```
type: custom:advanced-camera-card
cameras:
  - go2rtc:
      stream: millersleftofhouse
      url: https://myhost.mydomain:4443
    live_provider: go2rtc
```

Then I get a stream either on WiFi or Mobile data. Very strange!

**Comment by dermotduffy** [comment]
Guessing there is something not working with your webrtc setup, but MSE works fine (and so the working yaml is simply falling back to MSE, when you don't specify the mode it'll try a variety to get one that works).

**Comment by Daz42** [comment]
One more question if you don't mind. Is there any way I can pass the logon and password through the card if I define this in the go2rtc.yaml? Otherwise I have to keep entering the credentials whenever I refresh the card.

**Comment by dermotduffy** [comment]
> One more question if you don't mind. Is there any way I can pass the logon and password through the card if I define this in the go2rtc.yaml?

You may or may not be able to do this depending on how you have the authentication setup. If it's basic http authentication, something like this might work:

`https://username:password@myhost.mydomain:4443`

**Comment by gubsy420** [comment]
I have been having this same issue after upgrading to HA 2025.3. WebRTC was working flawlessly before.

**Comment by dermotduffy** [comment]
@gubsy420 That's unlikely, as Home Assistant is not involved in the path between the card and go2rtc. Are you using the `go2rtc` live provider?

**Comment by gubsy420** [comment]
@dermotduffy I am, and I keep it set to force the WebRTC mode. Is it dependant on the webRTC Card from HACS at all? Because I did recently uninstall that because I never use it.

**Comment by dermotduffy** [comment]
> Is it dependant on the webRTC Card from HACS at all?

No.

> isn't there precedent for HA updates breaking webRTC? 

Absolutely, but not when you've using the `go2rtc` live provider, only the `ha` or `auto` providers.

**Comment by Daz42** [comment]
> > One more question if you don't mind. Is there any way I can pass the logon and password through the card if I define this in the go2rtc.yaml?
> 
> You may or may not be able to do this depending on how you have the authentication setup. If it's basic http authentication, something like this might work:
> 
> `https://username:password@myhost.mydomain:4443`

This actually worked, if this is on your go2rtc config (see below). Obviously my username and password are much stronger than what you see in the example.

go2rtc.yaml
```
  api:
   listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
   username: "username"  # default "", Basic auth for WebUI
   password: "password"   # default "", Basic auth for WebUI
   origin: "*"        # default "", allow CORS requests (only * supported)
   tls_listen: ":4443" # default "", enable HTTPS server
   tls_cert: /ssl/fullchain.pem
   tls_key: /ssl/privkey.pem
```

And the card looks like:

Advanced Camera Card
```
type: custom:advanced-camera-card
cameras:
  - go2rtc:
      stream: streamname
      url: https://username:password@domanname.net:4443
    live_provider: go2rtc
live:
  lazy_load: false
  preload: true
```

I hope this helps someone using CloudFlare.
