### ISSUE TITLE
overrides bug

### ISSUE THREAD

**Issue by niro-zz** [dermotduffy/advanced-camera-card#1954]
Hi Hello
I think there is a problem with "overrides" when I put two conditions there

This example works
```yaml
overrides:
  - conditions:
      - condition: user_agent
        companion: true
    merge:
      menu:
        button_size: 32
```

This example not works
```yaml
overrides:
  - conditions:
      - condition: user_agent
        companion: true
    merge:
      menu:
        button_size: 32

  - conditions:
      - condition: fullscreen
        fullscreen: true
      - condition: display_mode
        display_mode: grid
    merge:
      live:
        display:
          mode: single
          grid_max_columns: 4
          grid_columns: 4
          grid_selected_width_factor: 3

```
Actually in the second example it works too but only when I select the grid then it also changes the size of the icons.

It feels like it only accepts one condition at a time something like this

Thanks

**Comment by dermotduffy** [comment]
This works fine for me. It's clearer with a different override, e.g. this:

```yaml
overrides:
  - conditions:
      - condition: fullscreen
        fullscreen: true
      - condition: display_mode
        display_mode: grid
    merge:
      menu:
        style: none
```

... hides the menu when it's both in fullscreen and in grid. 

> Actually in the second example it works too but only when I select the grid then it also changes the size of the icons.

Can you include a screenshot of before/after fullscreen+grid, and describe what you _expect_ to happen?

**Comment by felipecrs** [comment]
I think I'm facing the same issue. The moment I add a second override entry, the first stops working:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.video_porteiro
live:
  controls:
    builtin: false
menu:
  buttons:
    microphone:
      type: toggle
      priority: 49
    mute:
      enabled: true
  style: overlay
  button_size: 85
overrides:
  - conditions:
      - condition: microphone
        connected: true
    merge:
      menu:
        buttons:
          microphone:
            enabled: true
  - conditions:
      - condition: screen
        media_query: "(orientation: landscape)"
    merge:
      menu:
        style: outside
      dimensions:
        aspect_ratio_mode: dynamic
profiles:
  - low-performance
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: "16:9"
```

Demonstration:

https://github.com/user-attachments/assets/c6420959-6026-42ca-b507-85068cf18c4f
