### ISSUE TITLE
media_player custom card action

### ISSUE THREAD

**Issue by Daz42** [dermotduffy/advanced-camera-card#1955]
I am trying to configure a tap action to play an mp3 file.

I have setup the media player using webrtc using the camera with 2 way audio.

I am looking for a way to get this working in the Advanced Camera Card. In the documentation, there is a media_player custom card action. However, when I add 'advanced_camera_card_action: media_player' I get an invalid configuration - even through the Advanced Camera Card documentation shows this as an option?

```
  - type: custom:advanced-camera-card-menu-icon
    icon: mdi:message
    tap_action:
      - action: custom:advanced-camera-card-action
        advanced_camera_card_action: media_player
````

Does anyone have any good examples of playing an mp3 to a two way audio camera as there does not seem to be an example in the documentation and I can't find an example of someone else's config.

Cheers - D.

**Comment by Daz42** [comment]
Ok, this cleared the invalid configuration as it looks like you need to complete the whole section:

````
  - type: custom:advanced-camera-card-menu-icon
    icon: mdi:message
    tap_action:
      - action: custom:advanced-camera-card-action
        advanced_camera_card_action: media_player
        media_player: millersdoorbell_2
        media_player_action: play
````

Where do you specify the mp3 you want to play?

Thanks!!

**Comment by dermotduffy** [comment]
The Advanced Camera Card `media_player` action sends ("casts") the media you're looking at on the card (e.g. a clip, or a live view) to a media player, so I don't think this is what you're looking for. 

I'd recommend either a service ("perform-action") call ([random Googled example](https://community.home-assistant.io/t/play-audio-local-mp3-file-to-a-media-player/35883/17?page=2) or a Home Assistant script that plays the media you want, then just call that from the card.

**Comment by Daz42** [comment]
Thanks @dermotduffy,

I found what I needed in the Advanced Camera Card ->

```
          - action: perform-action
            perform_action: media_player.play_media
            target:
              entity_id: media_player.doorbellspeaker
            data:
              media_content_id: media-source://media_source/local/DoorbellMessage.mp3
              media_content_type: audio/mpeg
            metadata:
              title: DoorbellMessage.mp3
              thumbnail: null
              media_class: music
              children_media_class: null
              navigateIds:
                - {}
                - media_content_type: app
                  media_content_id: media-source://media_source
```

This of course needs a media player defined for the doorbell speaker, this is required in configuration.yaml:

```
media_player:
  - platform: webrtc
    name: doorbellspeaker
    stream: doorbellcamera_mp3
    audio: pcmu
````

The media (mp3) needs to be uploaded to 'My Media' which you can browse to and manage media from the Media Player Entity which provides the function.

I hope this helps someone as it took hours to get working. I used this as part of a doorbell implementation where I wanted message played if a courier was delivering a package (verified on camera) so I can remotely open the garage door as a safe place for the package.

Daz.
