### ISSUE TITLE
Turn camera light on/off

### ISSUE THREAD

**Issue by idar-a** [dermotduffy/advanced-camera-card#1961]
**[REQUIRED] Describe the feature you'd like:**

I have Arlo cameras which got lights and it is possible to turn on/off these lights within Arlo-app, but I would like to be able to turn the lights on/off in Advanced Camera Card as well

**[OPTIONAL] Describe alternatives you've considered:**

N/A

**[OPTIONAL] Additional context:**

N/A

**Comment by dermotduffy** [comment]
If there's a Home Assistant service or entity that controls those lights, then yes. If not, then no :-)

**Comment by idar-a** [comment]
Thank you for this quick reply 👏
Yep, there is an entity that can switch both lights and sieren on/off.

See attached images 😊

![Image](https://github.com/user-attachments/assets/bbbeba45-f4f4-4c70-8bae-28bb0c2af182)
![Image](https://github.com/user-attachments/assets/8ed849ff-42e3-4326-bee5-8251b65275f1)

**Comment by dermotduffy** [comment]
Great. Then you can just use a [`menu-state-icon`](https://card.camera/#/configuration/elements/custom/README?id=menu-state-icon) to control it from the menu.

[Very similar example](https://card.camera/#/examples?id=menu-state-icons).

**Comment by idar-a** [comment]
I have multiple cameras in my card, how should I then add this menu-state-icon for each camera, as the light entity name is different om each camera?

I tried this, but with no luck.
```
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.aarlo_inngang
                live_provider: auto
                always_error_if_entity_unavailable: true
                elements:
                  - type: custom:advanced-camera-card-menu-state-icon
                    entity: light.aarlo_inngang
                    tap_action:
                      action: toggle
                    icon: mdi:lightbulb
              - camera_entity: camera.aarlo_morgenplass
                always_error_if_entity_unavailable: true
                live_provider: auto
              - camera_entity: camera.aarlo_veranda
                live_provider: auto
                always_error_if_entity_unavailable: true
            view:
              default: image
              theme:
                themes: []
              keyboard_shortcuts:
                ptz_left:
                  key: ArrowLeft
                ptz_right:
                  key: ArrowRight
                ptz_up:
                  key: ArrowUp
                ptz_down:
                  key: ArrowDown
                ptz_zoom_in:
                  key: +
                ptz_zoom_out:
                  key: '-'
                ptz_home:
                  key: h
            status_bar:
              style: outside
              items:
                title:
                  enabled: true
                resolution:
                  enabled: false
                technology:
                  enabled: false
            timeline:
              style: ribbon
            menu:
              style: outside
              position: bottom
              buttons:
                ptz_controls:
                  enabled: true
                screenshot:
                  enabled: true
                mute:
                  enabled: true
                microphone:
                  enabled: true
                play:
                  enabled: false
                expand:
                  enabled: true
                image:
                  enabled: true
                recordings:
                  enabled: true
                fullscreen:
                  enabled: false
```

**Comment by dermotduffy** [comment]
Use a conditional element, like in this [example](https://card.camera/#/examples?id=conditional-elements), but that selects based on camera, e.g. something like this:

```yaml
elements:
  - type: custom:advanced-camera-card-conditional
    conditions:
      - condition: camera
        cameras
          - camera.aarlo_inngang
    elements:
      - type: custom:advanced-camera-card-menu-state-icon
        entity: light.aarlo_inngang
```

(I didn't test this, but hopefully it'll be enough of a hint, all of these conditions and elements are [documented](https://card.camera/#/configuration/README))
