### ISSUE TITLE
Question - how to hide events menu on the right?

### ISSUE THREAD

**Issue by mikecitt** [dermotduffy/advanced-camera-card#1966]
Is there an option to hide menu on the right that shows events - clips?
<img width="172" alt="Image" src="https://github.com/user-attachments/assets/a72162d6-45e1-4cb0-95fe-cb0b9dfebdc7" />

**Comment by dermotduffy** [comment]
```yaml
live:
  controls:
    thumbnails:
      mode: none
```

All documentation: https://card.camera
