### ISSUE TITLE
PTZ actions are repeatedly called on `v7.3.6`

### ISSUE THREAD

**Issue by XavierTora** [dermotduffy/advanced-camera-card#1967]
**Checklist:**

- Version 7.3.6 installed and browser cache cleared.

**[REQUIRED] Card diagnostic information:**

```
card_version: 7.3.6
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/134.0.0.0 Safari/537.36
date: 2025-03-17T20:14:49.382Z
lang: en
timezone: Europe/Madrid
git:
  hash: 773b486
  build_date: Sat, 15 Mar 2025 21:46:19 GMT
  commit_date: Sat, 15 Mar 2025 14:45:13 -0700
ha_version: 2025.3.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      17de67203d4da27e6e69bb2a9823cd1d: 5.8.0/0.14.1-
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.interior_1
      live_provider: go2rtc
      engine: frigate
      ptz:
        service: foscam.ptz
        data_home:
          entity_id: camera.foscam
          preset_name: '1'
        data_left:
          entity_id: camera.foscam
          travel_time: 0.5
          movement: left
        data_right:
          entity_id: camera.foscam
          travel_time: 0.5
          movement: right
        data_up:
          entity_id: camera.foscam
          travel_time: 0.5
          movement: up
        data_down:
          entity_id: camera.foscam
          travel_time: 0.5
          movement: down
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '16:9'
  performance:
    style:
      box_shadow: true
      border_radius: true
    features:
      card_loading_indicator: false
  status_bar:
    style: none
  elements:
    - type: icon
      icon: mdi:home
      service: foscam.ptz
      style:
        right: 25%
        top: 80%
        oppacity: 50%
        color: grey
      tap_action:
        action: perform-action
        perform_action: foscam.ptz_preset
        data:
          entity_id: camera.foscam
          preset_name: '1'
  menu:
    buttons:
      cameras:
        enabled: false
      substreams:
        enabled: false
      snapshots:
        enabled: false
      recordings:
        enabled: false
      download:
        enabled: true
      clips:
        enabled: false
      camera_ui:
        enabled: false
      expand:
        enabled: false
      display_mode:
        enabled: false
      ptz_controls:
        enabled: false
      ptz_home:
        enabled: false
      microphone:
        enabled: true
        type: toggle
      mute:
        enabled: true
      iris:
        enabled: true
    position: top
    alignment: right
  live:
    controls:
      builtin: false
```

**[REQUIRED] Description of problem:**

PTZ actions continuously triggers, for example, when relative action is called by card (left, right, up or down), this is executed repeatedly until page is refreshed.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
