### ISSUE TITLE
Disable microphone per stream?

### ISSUE THREAD

**Issue by Spectre5** [dermotduffy/advanced-camera-card#1968]
I have 3 cameras, two of which support two way audio and are working correctly.  However, the 3rd does not support two way audio, only 1 way.  However, the microphone button shows up for all 3 cameras in the card, which implies that it works on all 3.  Is there a way to disable the microphone button for the camera that does not support it?

I do not see it listed under the "Camera Capabilities -> Disable" section.

**Comment by Guruleenyc** [comment]
I'm experiencing this issue as well. For me, if I'm listening to music or any other audio when opening up my dashboard with this card, it stops whatever else I'm playing. It appears the camera card defaults to camera speaker on and commandeers the audio on my Android phone.

**Comment by Guruleenyc** [comment]
I'm experiencing this issue as well. For me, if I'm listening to music or any other audio when opening up my dashboard with this card, it stops whatever else I'm playing. It appears the camera card defaults to camera speaker on and commandeers the audio on my Android phone.

**Comment by dermotduffy** [comment]
@Guruleenyc That does not sound related to the posted issue.

@Spectre5 The card doesn't really know if your camera supports 2-way audio, only that the "plumbing" supports it. You could selectively enable the microphone button for some cameras with an override, something like this:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.has_2_way
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
  - camera_entity: camera.no_2_way
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
overrides:
  - conditions:
      - condition: camera
        cameras:
          - camera.has_2_way
    merge:
      menu:
        buttons:
          microphone:
            enabled: true
```
