### ISSUE TITLE
Browser mod popup crashes browser/app when used in card

### ISSUE THREAD

**Issue by dnestico** [dermotduffy/advanced-camera-card#1969]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```
card_version: 7.3.6
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/134.0.0.0 Safari/537.36
date: 2025-03-18T09:17:31.775Z
lang: en
timezone: America/Toronto
git:
  hash: 773b486
  build_date: Sat, 15 Mar 2025 21:46:19 GMT
  commit_date: Sat, 15 Mar 2025 14:45:13 -0700
ha_version: 2025.3.0
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JCZC5Y7VR4S3CN5QWHXHMGRY: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.porch
      dependencies:
        all_cameras: true
    - camera_entity: camera.driveway
      dependencies:
        all_cameras: true
    - camera_entity: camera.garage
      dependencies:
        all_cameras: true
    - camera_entity: camera.luna
      dependencies:
        all_cameras: true
  view:
    default: clips
    camera_select: clips
    theme:
      themes: []
  menu:
    style: outside
    position: top
    buttons:
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: false
      recordings:
        enabled: true
      camera_ui:
        enabled: false
      timeline:
        enabled: false
      play:
        enabled: false
      mute:
        enabled: false
      screenshot:
        enabled: true
        alignment: opposing
        icon: mdi:cellphone-screenshot
      iris:
        icon: mdi:home
        enabled: true
      display_mode:
        enabled: false
      download:
        alignment: opposing
      expand:
        alignment: opposing
      fullscreen:
        alignment: opposing
      media_player:
        alignment: opposing
  media_gallery:
    controls:
      thumbnails:
        show_favorite_control: false
        show_timeline_control: false
        size: 120
        show_details: true
        show_download_control: true
      filter:
        mode: none
  media_viewer:
    controls:
      builtin: true
      next_previous:
        style: chevrons
      timeline:
        mode: below
        style: stack
        events_media_type: clips
      thumbnails:
        mode: above
        show_timeline_control: false
        show_favorite_control: false
        size: 90
    auto_play:
      - selected
    auto_pause:
      - unselected
    auto_mute:
      - unselected
    auto_unmute:
      - selected
  dimensions:
    aspect_ratio_mode: unconstrained
  elements:
    - type: custom:advanced-camera-card-menu-icon
      icon: mdi:help-circle
      alignment: opposing
      title: Help
      style:
        left: 200px
        top: 50px
      tap_action:
        action: fire-dom-event
        browser_mod:
          service: browser_mod.popup
          data:
            title: Help
            content:
              type: markdown
              text_only: true
              content: |2-
                  <ha-alert title="Icon Information">

                  <ha-icon icon="mdi:filmstrip"></ha-icon> Clips 
                  <ha-icon icon="mdi:record-circle"></ha-icon> Recordings 
                  <ha-icon icon="mdi:camera"></ha-icon> Snapshots 
                  <ha-icon icon="mdi:cctv"></ha-icon> Live View
                  <ha-icon icon="mdi:monitor-screenshot"></ha-icon> Screenshot
                  <ha-icon icon="mdi:cast"></ha-icon> Cast Camera to display or TV

                  </ha-alert>
  status_bar:
    style: outside

```

**[REQUIRED] Description of problem:**

As you can see in the above code I have an element/button that when tapped activates a browser_mod popup, but it seems since a recent HA update it now completely crashes the entire browser, and when on the Android app where I can feel the vibrations of a button tap on the card when I tap that once specifically it vibrates like a million times, which I guess explains the crashing the browser part.

This issue seems to only happen on this card from what I can tell so far because I have a normal mushroom chip with the browser mod popup service that works fine without issue.

**[OPTIONAL] Last working release (if known):**

Don't know which exactly cuz I don't regularly use the button but before 2025.3 it was 100% working.
