### ISSUE TITLE
Audio works on Desktop but doesn't on Mobile

### ISSUE THREAD

**Issue by rodrigogbs** [dermotduffy/advanced-camera-card#1971]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

**Desktop:**
```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.3.6
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/134.0.0.0 Safari/537.36
date: 2025-03-18T13:53:50.097Z
lang: en
timezone: America/Sao_Paulo
git:
  hash: 773b486
  build_date: Sat, 15 Mar 2025 21:46:19 GMT
  commit_date: Sat, 15 Mar 2025 14:45:13 -0700
ha_version: 2025.3.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JAQS31SG8P4D3N71VHAPKJYC: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - webrtc_card:
        entity: camera.quadra_profile_000
      camera_entity: camera.quadra_profile_000
  view:
    default: live
    default_reset:
      every_seconds: 5
  menu:
    buttons:
      fullscreen:
        enabled: true
      microphone:
        enabled: false
      camera_ui:
        enabled: false
      frigate:
        enabled: false
      substreams:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      cameras:
        enabled: false
    style: outside
    position: top
    button_size: 30
    alignment: left
  live:
    microphone:
      always_connected: false
      disconnect_seconds: 1
    preload: true
    controls:
      ptz:
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 130px
  elements:
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:menu
      items:
        - title: Reboot
          icon: mdi:power
          entity: button.quadra_reboot
          tap_action:
            action: perform-action
            data:
              entity_id: button.quadra_reboot
            perform_action: button.press
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:cursor-move
      items:
        - title: Move UP
          icon: mdi:arrow-up
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              tilt: UP
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
        - title: Move DOWN
          icon: mdi:arrow-down
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              tilt: DOWN
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
        - title: Move LEFT
          icon: mdi:arrow-left
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              pan: LEFT
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
        - title: Move RIGHT
          icon: mdi:arrow-right
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              pan: RIGHT
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
  cameras_global:
    webrtc_card:
      background: true
    ptz:
      data_left:
        entity_id: camera.quadra_profile_000
        pan: LEFT
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      data_right:
        entity_id: camera.quadra_profile_000
        pan: RIGHT
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      data_up:
        entity_id: camera.quadra_profile_000
        tilt: UP
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      data_down:
        entity_id: camera.quadra_profile_000
        tilt: DOWN
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      service: onvif.ptz
```

**Mobile:**
```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.3.6
browser: >-
  Mozilla/5.0 (iPad; CPU OS 18_3_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML,
  like Gecko) CriOS/134.0.6998.99 Mobile/15E148 Safari/604.1
date: 2025-03-18T14:06:35.852Z
lang: en
timezone: America/Sao_Paulo
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.3.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JAQS31SG8P4D3N71VHAPKJYC: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - webrtc_card:
        entity: camera.quadra_profile_000
      camera_entity: camera.quadra_profile_000
  view:
    default: live
    default_reset:
      every_seconds: 5
  menu:
    buttons:
      fullscreen:
        enabled: true
      microphone:
        enabled: false
      camera_ui:
        enabled: false
      frigate:
        enabled: false
      substreams:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      cameras:
        enabled: false
    style: outside
    position: top
    button_size: 30
    alignment: left
  live:
    microphone:
      always_connected: false
      disconnect_seconds: 1
    preload: true
    controls:
      ptz:
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 130px
  elements:
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:menu
      items:
        - title: Reboot
          icon: mdi:power
          entity: button.quadra_reboot
          tap_action:
            action: perform-action
            data:
              entity_id: button.quadra_reboot
            perform_action: button.press
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:cursor-move
      items:
        - title: Move UP
          icon: mdi:arrow-up
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              tilt: UP
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
        - title: Move DOWN
          icon: mdi:arrow-down
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              tilt: DOWN
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
        - title: Move LEFT
          icon: mdi:arrow-left
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              pan: LEFT
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
        - title: Move RIGHT
          icon: mdi:arrow-right
          entity: camera.quadra_profile_000
          tap_action:
            action: perform-action
            data:
              entity_id: camera.quadra_profile_000
              pan: RIGHT
              move_mode: ContinuousMove
              continuous_duration: 1
              distance: 1
              speed: 1
            perform_action: onvif.ptz
  cameras_global:
    webrtc_card:
      background: true
    ptz:
      data_left:
        entity_id: camera.quadra_profile_000
        pan: LEFT
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      data_right:
        entity_id: camera.quadra_profile_000
        pan: RIGHT
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      data_up:
        entity_id: camera.quadra_profile_000
        tilt: UP
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      data_down:
        entity_id: camera.quadra_profile_000
        tilt: DOWN
        move_mode: ContinuousMove
        continuous_duration: 1
        distance: 1
        speed: 1
      service: onvif.ptz
```

**[REQUIRED] Description of problem:**

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
I was not using this card for a while, so I don't know in wich version it was working, but now in the latest version of Frigate + Advanced Camera Card, I can listen to the cameras audio only on Desktop (HA APP or Chrome), on Mobile it just doesn't reproduce any sound.
```

**[OPTIONAL] Additional information:**

**Comment by Spectre5** [comment]
It is probably a codec issue.  I had this same problem and then re-encoded the audio in frigate to opus (and use go2rtc card) and then audio worked it both for me.

**Comment by rodrigogbs** [comment]
> It is probably a codec issue. I had this same problem and then re-encoded the audio in frigate to opus (and use go2rtc card) and then audio worked it both for me.

this is my current frigate config:

```yaml
go2rtc:
  streams:
    videoporteiro:
      - ffmpeg:rtsp://xxx/Preview_01_main#video=copy#audio=copy#audio=opus
      - rtsp://xxx/h264Preview_01_main
  webrtc:
    listen: :8555
```

Is it alligned to your config?

**Comment by Spectre5** [comment]
Mine is a Reolink doorbell, so it is a little different.  Done the same as the doc recommend:
https://docs.frigate.video/configuration/camera_specific#reolink-doorbell

Here is my go2rtc setup:
```yaml
go2rtc:
  # the docs recomment http-flv for reolink cameras:
  # https://docs.frigate.video/configuration/camera_specific/#reolink-cameras
  streams:
    front_door:
      # "Clear" is channel0_main (2560x1920)
      # "Balanced" is channel0_ext (896x672)
      # "Fleunt" is channel0_sub (640x480)
      # - https://{FRIGATE_DOORBELL_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_DOORBELL_USER}&password={FRIGATE_DOORBELL_PASSWORD}
      # - https://{FRIGATE_DOORBELL_IP}/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_DOORBELL_USER}&password={FRIGATE_DOORBELL_PASSWORD}
      # - https://{FRIGATE_DOORBELL_IP}/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_DOORBELL_USER}&password={FRIGATE_DOORBELL_PASSWORD}
      # - rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASSWORD}@{FRIGATE_DOORBELL_IP}:554/h264Preview_01_main
      - "ffmpeg:https://{FRIGATE_DOORBELL_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_DOORBELL_USER}&password={FRIGATE_DOORBELL_PASSWORD}#video=copy#audio=copy#audio=opus"
      - rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASSWORD}@{FRIGATE_DOORBELL_IP}:554/h264Preview_01_sub
```

On the last line, be sure to include the user and password.  I originally only had the IP and the audio did not work, i.e. like this:

```yaml
      - rtsp://{FRIGATE_DOORBELL_IP}:554/h264Preview_01_sub
```
