### ISSUE TITLE
No Audio with RTC

### ISSUE THREAD

**Issue by Aggro600** [dermotduffy/advanced-camera-card#1973]
Audio on Figate WebUi OK 
Audio on go2rtc no Audio with RTC but with MSE
Camera card no audio with RTC but with MSE

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.haustur
    icon: mdi:cctv
    live: preload
    dependencies:
      cameras:
        - haustur_hd
    live_provider: go2rtc
    id: haustur
    title: Haustür
    go2rtc:
      modes:
        - webrtc
      stream: haustur_sub
    triggers:
      occupancy: false
      motion: false
      events: []
      entities: []
  - camera_entity: camera.haustur
    live_provider: go2rtc
    title: Haustür HD
    id: haustur_hd
    go2rtc:
      modes:
        - webrtc
      stream: haustur
    triggers:
      occupancy: false
      motion: false
      events: []
      entities: []
    capabilities:
      disable_except:
        - substream
```
