### ISSUE TITLE
Using Onvif PTZ with separate Frigate Server and go2RTC

### ISSUE THREAD

**Issue by peteDDD** [dermotduffy/advanced-camera-card#1974]
I have Frigate running on one server and Home Assistant running on another. They use the same MQTT server. I have a test camera set up, connected to the Frigate server and configured with go2RTC which is working fine showing that camera on the Advanced Camera Card on the Home Assistant server though the video there is not as smooth as on the Frigate API.  When I look at this same camera on the Frigate server (port 5000) and click on the image to get the live view, I see functional pan and tilt controls which work just fine.

I am trying to get the pan and tilt (and then later zoom) controls to show and to work within the Advanced Camera Card.

Live (Live camera view options)/Live Controls/Built-in video controls is ON
Live (Live camera view options)/Live Controls/PTZ/Mode is ON and hide pan & tile control is off BUT, there are no pan and tile controls shown in the image. All other functions I have tested so far for this configuration, such as motion triggers, are working just fine.  

Here is a view of the Advanced Camera Card where there are no PTZ controls showing for this camera.

![Image](https://github.com/user-attachments/assets/f9c0d0b6-272a-4e9d-b876-2224b0ffca2f)

Here is the config for the card. (other, non-go2RTC cameras removed)

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.test_camera
    live_provider: go2rtc
    go2rtc:
      url: 192.168.1.89
menu:
  buttons:
    ptz_controls:
      enabled: false
      alignment: matching
      permanent: true
      icon: mdi:pan
    ptz_home:
      enabled: false
      icon: mdi:diamond-stone
      permanent: true
live:
  controls:
    ptz:
      mode: "on"
      position: bottom-left
```
And the config on the Frigate server:
```
mqtt:
  enabled: true
  host: 192.168.1.217
  port: 1883
  user: homeassistant
  password: XXXX
  topic_prefix: frigate
go2rtc:
  streams:
    test_camera_hi:
      - ffmpeg:rtsp://admin:XXXX@192.168.10.99:554/11
    test_camera_low:
      - ffmpeg:rtsp://admin:XXXX@192.168.10.99:554/12
cameras:
  test_camera:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/test_camera_hi
          input_args: preset-rtsp-restream
          roles:
            - record
      
        # low res stream
        - path: rtsp://127.0.0.1:8554/test_camera_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800 
      height: 450
    live:
      stream_name: test_camera_hi
      height: 720
      quality: 8
    onvif:
      host: 192.168.10.99
      port: 8080
      user: admin
      password: XXXX

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
objects:
  track:
    - person

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    #NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    #NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  alerts:
    retain:
      days: 10
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 10
    pre_capture: 5
    post_capture: 5
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: false
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  #NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
version: 0.15-1
```

Is there a reference specific to split HA/Frigate configurations which I could refer to?

--OR--

My goal here is to move an 8 camera set-up from Blue Iris to Frigate and Home Assistant.   Based on the loads I see on Blue Iris, I decided to use a separate system for Frigate.  With only one 4K camera on Frigate, I am seeing an average CPU load of only 2.1% and a max load of 3.5%.  With the twin Coral TPU, my inference speed is 6.6ms.   This leads me to think that running Frigate, HA, and pi-hole on one system would be reasonable, even with 8 4K cameras.  WOULD HAVING THIS ALL ON ONE INSTANCE OF PROMOX SIMPLIFY ALL OF THESE SORTS OF ISSUES?

THANKS!

**Comment by dermotduffy** [comment]
PTZ controls do not relate to go2rtc at all. What runs where is not relevant, it's purely:

Card <-> Frigate Integration (runs as part of the Home Assistant process) <-> Frigate

Do the PTZ controls work in the Frigate UI? If not, start there. After that, as long as you refer to the _same camera_ (e.g. use a camera entity that the Frigate integration provides) this should all "just work" with literal zero extra configuration in the card, beyond specifying the camera.

**Comment by dermotduffy** [comment]
Oh, I see the issue. I don't think your stream is loading at all, instead you're just getting image snapshots updating 1/sec -- notice the "loading circle" on the top right of your screenshot. PTZ controls don't show until after the stream loads.

That is likely also be why you don't feel the video is smooth -- it's not a video at all, the card is showing you images whilst waiting for the stream to load!

Troubleshooting: https://card.camera/#/troubleshooting?id=stream-does-not-load

**Comment by peteDDD** [comment]
@dermotduffy   Thank you for your prompt reply and sorry for the delay in my response.   I will investigate that.  Thank you for that link.

Do you have an option on the having it all on one machine instead of my current split configuration?

**Comment by peteDDD** [comment]
This is interesting.   Web socket is failing

'ws://
192.168.1.220:8123/dashboard-frigatetest/192.168.1.89/api/ws?src=test_camera
'

192.168.1.220:8123 is the home assistant machine and that is accessible
from this browser
192.168.1.89 is the frigate machine
test_camera is the correct name for the camera

192.168.1.89/api is not accessible but 192.168.1.89:5000 is, of course

The full error message is:
WebSocket connection to 'ws://192.168.1.220:8123/dashboard-frigatetest/
192.168.1.89/api/ws?src=test_camera' failed:
onconnect @ index-d4f015ee.js:1

The camera on the frigate machine is on a separate NIC 192.168.10.0/24
while the connection between the two servers is on 192.168.1.0/24
COULD THIS BE AN ISSUE?

The other bit of info I gather from the Java console is:
The onconnect @ index-d4f015ee.js:1 part of the error message indicates
that the error originated from the onconnect function
located in the file index-d4f015ee.js at line 1, which in your code sample
corresponds to the first line of the onconnect method definition.

but I have no idea where to even start with that.

Any suggestions?

Thanks!

**Comment by dermotduffy** [comment]
> Do you have an option on the having it all on one machine instead of my current split configuration?

The card doesn't care at all. Works either way. I've run in both configurations before.

> WebSocket connection to 'ws://192.168.1.220:8123/dashboard-frigatetest/
192.168.1.89/api/ws?src=test_camera' failed:

Yes, this is very likely the problem. You have a networking issue between your browser and the go2rtc instance. Are you running your own custom go2rtc? If not, why are you specifying the `url` parameter? You shouldn't need to do that, and the Frigate integration (which you need to have installed), will automatically proxy between the browser and the go2rtc that is built into Frigate.

**Comment by peteDDD** [comment]
Thanks again for your reply @dermotduffy 

Yes, I am running the Frigate home assistant integration on my home assistant instance, pointing to the Frigate on the other server.

![Image](https://github.com/user-attachments/assets/c57575c5-f7c9-4789-ac57-8ce333cbbfe3)

Regarding "why are you specifying the url parameter in the card config" ... because I thought I had to ;^).   Now removing the URL pointer does not remove the "loading" indicator.

I am not running a custom go2rtc, just depending on the one in the Frigate integration.

The card config now with the explicit go2rtc url removed is below.  The javascript error (WebSocket connection error) is no longer present but the stream is still not loading.  (I restarted both the home assistant and Frigate server instances). So I have moved on to step 5 in the troubleshooting documentation.   My understanding is that webrtc and go2rtc are two different things so I have been ignoring any references to webrtc in the configuration documents. So nothing in step 5 would apply.  Am I correct in that understanding?  Do I need to do anything to specify the live stream?
```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.test_camera
    live_provider: go2rtc
menu:
  buttons:
    ptz_controls:
      enabled: false
      alignment: matching
      permanent: true
      icon: mdi:pan
    ptz_home:
      enabled: false
      icon: mdi:diamond-stone
      permanent: true
live:
  controls:
    ptz:
      mode: "on"
      position: bottom-left
```

and excerpt from the frigate config:
```
go2rtc:
  streams:
    test_camera_hi:
      - ffmpeg:rtsp://admin:XXXX@192.168.10.99:554/11
    test_camera_low:
      - ffmpeg:rtsp://admin:XXXX@192.168.10.99:554/12
cameras:
  test_camera:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/test_camera_hi
          input_args: preset-rtsp-restream
          roles:
            - record
      
        # low res stream
        - path: rtsp://127.0.0.1:8554/test_camera_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800 
      height: 450
    live:
      stream_name: test_camera_hi
      height: 720
      quality: 8
    onvif:
      host: 192.168.10.99
      port: 8080
      user: admin
      password: FincaJill8103

```


(I have to focus on a home remodeling project today but will be back to this late in the day today).  Thank you again!

**Comment by dermotduffy** [comment]
Your card config looks correct to me, on the assumption that the entity `camera.test_camera` is indeed a Frigate integration provided entity.

I notice you seem to be requesting a different stream name in your Frigate config, that doesn't match the camera name. This may be the issue:

```yaml
      stream_name: test_camera_hi
```

You can tell the card to use a different stream with something like this:

```yaml
cameras:
  - camera_entity: camera.test_camera
    live_provider: go2rtc
    go2rtc:
      stream: test_camera_hi
```

If none of this works, are there any interesting messages on your browser console (F12), or in your Home Assistant logs?
