### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by coserotondo** [dermotduffy/advanced-camera-card#1983]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases). -> DONE
- Please try clearing your browser cache. -> DONE

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.3.1
browser: &gt;-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/134.0.0.0 Safari/537.36
date: 2025-03-27T07:19:43.312Z
lang: en
timezone: Europe/Rome
git:
  hash: 41aa3d1
  build_date: Fri, 28 Feb 2025 04:51:01 GMT
  commit_date: Thu, 27 Feb 2025 20:49:54 -0800
ha_version: 2025.3.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01J58S0CDBKVM5FA71CPHQJCR2: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.giardino
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.ingresso_est
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.ingresso_ovest
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.patio
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.vialetto_nord
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.vialetto_sud
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
  live:
    controls:
      ptz:
        mode: 'off'
```

**[REQUIRED] Description of problem:**

Error logs in HA:

```text
Logger: frontend.js.modern.202503060
Source: components/system_log/__init__.py:331
First occurred: 8:18:02 AM (1 occurrences)
Last logged: 8:18:02 AM

Uncaught error from Chrome 134.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "focus-trap" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/advanced-camera-card/card-206decfa.js:75:3686
```

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
inject.js:1 Enkrypt: Hello from IN
lockdown-install.js:1 Removing unpermitted intrinsics
auto-entities.js?hacstag=1677445841130:172 AUTO-ENTITIES 1.13.0 IS INSTALLED
vertical-stack-in-card.js?hacstag=142051833101:1 vertical-stack-in-cardVersion: 1.0.1
uptime-card.js?hacstag=3505098670160:448  uptime-card    0.16.0    
mini-graph-card-bundle.js?hacstag=1512800620121:1  MINI-GRAPH-CARD  0.12.1 
fold-entity-row.js?hacstag=150781994220:78 FOLD-ENTITY-ROW 2.2.0 IS INSTALLED 
scheduler-card.js?hacstag=2862701573214:1813   SCHEDULER-CARD    Version: v3.2.14
mushroom.js?hacstag=444350375431:309 🍄 Mushroom 🍄 - 4.3.1
power-flow-card-plus.js?hacstag=618081815025:1 ⚡ Power Flow Card Plus v0.2.5 is installed
card-dfbafb45.js:616  📷 Advanced Camera Card  7.3.1 
/lovelace/0:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "focus-trap" has already been used with this registry
    at window.CustomElementRegistry.define (https://hass.cose.duckdns.org/frontend_latest/app.3deecc90c3ae9ae6.js:2:4303)
    at https://hass.cose.duckdns.org/hacsfiles/advanced-camera-card/card-206decfa.js:75:3686
scoped-custom-element-registry.js:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()
image.vialetto_nord_cat:1 
            
            
           Failed to load resource: the server responded with a status of 500 ()
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
lockdown-install.js:1 SES_UNCAUGHT_EXCEPTION: null
(anonymous) @ lockdown-install.js:1
```

**[OPTIONAL] Additional information:**
