### ISSUE TITLE
Can't get more than a single camera to be shown..

### ISSUE THREAD

**Issue by dopeytree** [dermotduffy/advanced-camera-card#1990]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.0.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/18.3.1 Safari/605.1.15
date: 2025-04-02T13:38:06.465Z
lang: en
timezone: Europe/London
git:
  hash: cc376a8
  build_date: Fri, 07 Feb 2025 03:33:44 GMT
  commit_date: Thu, 6 Feb 2025 19:32:32 -0800
ha_version: 2025.3.4
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.barn
    - camera_entity: camera.porch_cam
    - camera_entity: camera.road_cam
    - camera_entity: camera.bird_cam
    - camera_entity: camera.barn_catflap
  view:
    default: snapshot
    update_mode: auto
    camera_select: snapshot
    default_cycle_camera: true
    triggers:
      filter_selected_camera: false
      actions:
        trigger: default
  conditions:
    label: cat
  menu:
    style: hidden
  live:
    lazy_load: true
  image:
    mode: url
  card_mod:
    style: |
      :host {
        --frigate-card-event-max: 1; /* Limit to 1 event (latest) */
      }
```

**[REQUIRED] Description of problem:**

Can't get it to show anything other than a single camera. I want it to just show tags of cat from all cameras.
Top right card. The others are me playing around with the cat tag api image on a picture card.
![Image](https://github.com/user-attachments/assets/294d51a1-00bd-4810-bcc0-05845879c135)

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
> Can't get it to show anything other than a single camera. I want it to just show tags of cat from all cameras.

I'm not sure I follow. You should be able to just select the camera you want from the menu. If you want it to have all events "joined" together, you can use dependencies, by making the first camera depend on all the others, with something like:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.one
    dependencies:
      all_cameras: true
  - camera_entity: camera.two
  - camera_entity: camera.three
  - camera_entity: camera.four
```

That would cause the first camera to depend on all the others, so all the media for them would show up when the first camera is selected. Maybe this is what you mean?

See:  [Dependencies documentation](https://card.camera/#/examples?id=using-dependent-cameras-with-birdseye-for-all-cameras)

**Comment by dopeytree** [comment]
Am trying to have a single view that shows all events of cats from multiple camera without interacting with the card. 
See screenshot for how it work within frigate itself, select cat and it shows just cat images across all cameras.
![Image](https://github.com/user-attachments/assets/e03989b4-e6d1-4f14-97e1-5238f830b641)

**Comment by dopeytree** [comment]
![Image](https://github.com/user-attachments/assets/0ad6cc14-2969-41f0-b762-cdfbceec043b)

http://192.168.22.2:5000/api/barn/cat/snapshot.jpg

Is there a way to use frigate api to show just cat images rather than having to specify a camera?

**Comment by dopeytree** [comment]
I suppose it's easier to say I'm trying to have a way to place and see where my cat was last seen from a set of 5x cameras. I dont really want to just see 5x camera feeds, just the last few sightings on rotations or carousel etc or if this is not possible perhaps 3x stills (3x cards) that show the latest detections but again not tied to a particular camera, more tied to timescale as in most recent.

**Comment by dermotduffy** [comment]
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.one
    dependencies:
      all_cameras: true
    frigate:
      labels:
        - cat
  - camera_entity: camera.two
    frigate:
      labels:
        - cat
  - camera_entity: camera.three
    frigate:
      labels:
        - cat
  - camera_entity: camera.four
    frigate:
      labels:
        - cat
view:
  default: snapshot
```

... would show a single carousel of the most recent cat snapshots from all listed cameras.

Is this what you mean?
