### ISSUE TITLE
Is it possible to change the stock photo of purple flowers image?

### ISSUE THREAD

**Issue by livefeed** [dermotduffy/advanced-camera-card#1991]
Is it possible to change the stock photo of purple flowers image?

**Comment by dermotduffy** [comment]
> Is it possible to change the stock photo of purple flowers image?

... but why? It's already perfect ;-)

If you mean in the `image` view, you can specify an arbitrary URL like this:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.foo
image:
  mode: url
  url: https://plus.unsplash.com/premium_photo-1667680403604-c4b69984eef8?q=80&w=2921&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
view:
  default: image
```

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/f03c6ae4-4619-4db6-9604-7ef3f3672583" />
