### ISSUE TITLE
Streams should be unloaded whenever possible

### ISSUE THREAD

**Issue by EinfachHans** [dermotduffy/advanced-camera-card#1992]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.5.1
browser: >- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3.1 Safari/605.1.15
date: 2025-04-03T07:10:31.348Z
lang: en
timezone: Europe/Berlin
git:
  hash: '3678385'
  build_date: Sat, 29 Mar 2025 19:50:39 GMT
  commit_date: Sat, 29 Mar 2025 12:49:36 -0700
ha_version: 2025.3.4
custom_integrations:
  frigate:
    detected: false
    hass_web_proxy: detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - capabilities:
      - disable_except:
      - live
     camera_entity: camera.turklingel_flussig
     title: Türklingel
     dimensions: aspect_ratio_mode: static aspect_ratio: '1:1' 
```

**[REQUIRED] Description of problem:**

This night i had a battery drain on one of my Reolink battery powered camera (Video doorbell). This could only be stopped by restarting home assistant.

According to this [this comment](https://github.com/home-assistant/core/issues/140990#issuecomment-2774648963) this **may** be relative to this card.

Is there any logic to keep the streams open, or ping the camera even when the card is not visible?

If so, can it be turned of?

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
Try adding:

```yaml
live:
  lazy_unload:
    - unselected
    - hidden
```

... and see if it helps?

**Comment by EinfachHans** [comment]
@dermotduffy Thanks, i will and let u know!

Additional information. Happens today again and i enabled the debug logs of the reolink integration which were full of logs like:

```
2025-04-03 17:39:56.379 WARNING (MainThread) [homeassistant.components.go2rtc.server] 17:39:56.379 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error="read tcp 192.168.178.154:60362->192.168.178.47:554: i/o timeout" url=rtsp://admin:qeDLf%21zJ.gsN3dHQPbt9@192.168.178.47:554/Preview_01_sub
2025-04-03 17:39:59.672 WARNING (MainThread) [homeassistant.components.go2rtc.server] 17:39:59.671 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error=EOF url=ffmpeg:camera.turklingel_flussig#audio=opus#query=log_level=debug
2025-04-03 17:40:07.938 WARNING (MainThread) [homeassistant.components.go2rtc.server] 17:40:07.938 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error=EOF url=ffmpeg:camera.turklingel_flussig#audio=opus#query=log_level=debug
2025-04-03 17:40:18.244 WARNING (MainThread) [homeassistant.components.go2rtc.server] 17:40:18.243 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error=EOF url=ffmpeg:camera.turklingel_flussig#audio=opus#query=log_level=debug
```

I only use the advanced camera card withe the reolink source directly. No go2rtc. Is this something from this card? If yes will it be solved via the option you provided above?

**Comment by dermotduffy** [comment]
Well, Home Assistant uses go2rtc internally, so if the card was continuing to stream from the HA entity, it's conceivable those messages were emitted. Are you keeping a dashboard open? Or do you suspect the card is (somehow) consuming the battery even though there's no dashboard open anywhere? That is very unlikely / impossible ;-)

**Comment by EinfachHans** [comment]
No dashboard is open 🤔 I also thought the card only can do stuff when opened somewhere but i'm quite new into HA and don't now if it is maybe possible to do so

**Comment by dermotduffy** [comment]
> No dashboard is open 🤔 I also thought the card only can do stuff when opened

If you don't open a dashboard, the card will never run and cannot be responsible. Once you open a dashboard, the browser loads the card, and it _could_ be to blame if you keep the browser running (browser => on a PC, or phone, or tablet, either the HA companion app or just visiting your dashboard URL).

**Comment by EinfachHans** [comment]
Should the card and everything related to it be destroyed when switching to a different dashboard?

Or when the mobile app is moved to background?

If no, should it with this set?
```
live:
  lazy_unload:
    - unselected
    - hidden
```

**Comment by dermotduffy** [comment]
> Should the card and everything related to it be destroyed when switching to a different dashboard?

I assume you continue to have the battery drain problem?

I suspect the issue might be related to the video staying loaded if a dashboard is opened with Advanced Camera Card, and then even if the 'tab' *within* the dashboard is changed, the video stays loaded. If the browser tab was changed, or the browser closed, it would likely work correctly. Could this be your issue?

**Comment by EinfachHans** [comment]
I'm still trying to get to the root of the problem. This could definitely be the problem! Should the stream unload in that case of switching within the dashboard tabs?

**Comment by dermotduffy** [comment]
Right now, I don't think it does. It really depends on how the Home Assistant frontend treats 'non-current' tabs, but I think the card could deal with this in a smarter way. Playing around with it now to see if it can do better. Stay tuned.

**Comment by dermotduffy** [comment]
@EinfachHans I did find an issue. With the new release (`v7.6.2`), whenever a stream is disconnected from the DOM, no matter the circumstances, it should cut connections. If your usage pattern had been "viewing a dashboard, and then changing tabs in that dashboard", then that _may_ have been the source of your battery drain issue, and so it _may_ be fixed now. If your battery drain was caused by something else, then it won't help.

Keep these parameters:

```yaml
live:
  lazy_unload:
    - unselected
    - hidden
```

Let me know how it goes!
