### ISSUE TITLE
Reolink 2-way audio - Can't make it work

### ISSUE THREAD

**Issue by marcuscps** [dermotduffy/advanced-camera-card#1993]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.5.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/134.0.0.0 Safari/537.36
date: 2025-04-04T02:32:14.544Z
lang: en
timezone: Europe/London
git:
  hash: '3678385'
  build_date: Sat, 29 Mar 2025 19:50:39 GMT
  commit_date: Sat, 29 Mar 2025 12:49:36 -0700
ha_version: 2025.4.0
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JQYBYV16G89ABPS0NFH60SPJ: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.cam_doorbell
      always_error_if_entity_unavailable: false
      go2rtc:
        modes:
          - webrtc
        url: https://user:pass%@10.0.10.12:8123
        stream: cam_doorbell
      live_provider: go2rtc
  menu:
    buttons:
      microphone:
        enabled: true
        type: toggle
        alignment: opposing
      cameras:
        enabled: true
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
    position: bottom
    style: outside
  status_bar:
    style: outside
    position: top
  live:
    microphone:
      always_connected: false
      disconnect_seconds: 15
```

**[REQUIRED] Description of problem:**

I've been trying to configure 2-way audio with a Reolink PoE Doorbell.
I successfully configured Frigate to use https (port 8971). Audio (not 2-way) works well from the Frigate UI  (check screenshot below).
I can confirm go2rtc is working from its UI, and I can also load the stream on the browser (check screenshots below).

However, the Advanced Camera Card won't load the stream at all using go2rtc. It works for the same camera but using the live 

I've read the docs in details and also read most of the posts here and in other forums with no success.

I tried to specify the go2rtc URL manually (and also without it) with no success.

![Image](https://github.com/user-attachments/assets/757768d4-81fa-4570-9cec-032aea2be588)

![Image](https://github.com/user-attachments/assets/4427cae8-4f39-462c-9f54-62fa3100753e)

![Image](https://github.com/user-attachments/assets/7d2478c1-e5ca-4325-b905-dac1e23c60f1)

![Image](https://github.com/user-attachments/assets/98e4f0d0-bfd8-4ff8-962f-8d7807f20310)
Advanced Camera Card not loading the stream

![Image](https://github.com/user-attachments/assets/0d9328b5-9138-4fd6-b49a-deaedf720bbf)
Advanced Camera Card working for the same camera

**Additional information:**

HA runs on a Proxmox VM.

Frigate runs on a Proxmox LXC (privileged) on the same hardware that runs Docker.

My Frigate Config:
```yaml
version: 0.15-1

tls:
  enabled: false

auth:
  enabled: true

mqtt:
  enabled: true
  host: 10.0.10.14
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: pass
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  restream: true
  mode: continuous
  quality: 8
  width: 1920
  height: 1080

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  enabled: true
  fps: 5
  width: 640
  height: 360

live:
  height: 2160
  quality: 8

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000

record:
  enabled: true
  retain:
    days: 45
    mode: all
  alerts:
    pre_capture: 5
    post_capture: 10
    retain:
      days: 90
  detections:
    pre_capture: 5
    post_capture: 10
    retain:
      days: 90

go2rtc:
  webrtc:
    listen: :8555
    candidates:
      - 10.0.10.12:8555
      - stun:8556  

  streams:
    cam_doorbell:
      - rtsp://frigate:my_password@10.0.41.10:554/
      - ffmpeg:http://10.0.41.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=my_password#video=copy#audio=copy#audio=opus
      - rtsp://frigate:my_password@10.0.41.10:554/h264Preview_01_sub
    cam_doorbell_sub:
      - rtsp://frigate:my_password@10.0.41.10:554/h264Preview_01_sub
      - ffmpeg:http://10.0.41.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=my_password#video=copy#audio=copy#audio=opus
    cam_front:
      - rtsp://frigate:my_password@10.0.40.10:554/Streaming/Channels/101
    cam_front_sub:
      - rtsp://frigate:my_password@10.0.40.10:554/Streaming/Channels/102
    cam_corridor:
      - rtsp://frigate:my_password@10.0.40.11:554/Streaming/Channels/101
    cam_corridor_sub:
      - rtsp://frigate:my_password@10.0.40.11:554/Streaming/Channels/102
    cam_16:
      - rtsp://frigate:my_password@10.0.40.12:554/Streaming/Channels/101
    cam_16_sub:
      - rtsp://frigate:my_password@10.0.40.12:554/Streaming/Channels/102
    cam_20:
      - rtsp://frigate:my_password@10.0.40.13:554/Streaming/Channels/101
    cam_20_sub:
      - rtsp://frigate:my_password@10.0.40.13:554/Streaming/Channels/102
      
cameras:

  cam_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/cam_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: "10.0.41.10"
      user: "frigate"
      password: "my_password"
    live:
      stream_name: cam_doorbell
      height: 1920
    birdseye:
      order: 1
    ui:
      order: 1
    motion:
      mask: 
        0.021,0.469,0.016,0.633,0.029,0.757,0.339,0.673,0.373,0.743,0.832,0.729,0.905,0.641,1,0.709,1,0,0.493,0,0.153,0.254,0.042,0.415
    objects:
      mask: 
        -0.001,0.384,0.021,0.432,0.02,0.644,0.028,0.776,0.342,0.669,0.343,0.754,0.83,0.746,0.881,0.685,0.996,0.661,1,0,0,0

  cam_front:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:my_password@10.0.40.10:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://frigate:my_password@10.0.40.10:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam_front
    birdseye:
      order: 2
    ui:
      order: 2
    motion:
      mask:
        - 0.984,0.911,0.984,0.95,0.727,0.95,0.727,0.911
        - 0,0.548,0.041,0.654,0.282,0.189,0.298,0.277,0.868,0.451,0.882,0.363,0.905,0.374,0.911,0.407,1,0.458,1,0,0,0
    objects:
      mask: 
        0.041,0.657,0.282,0.191,0.299,0.278,0.87,0.45,0.883,0.362,0.904,0.372,0.912,0.413,1,0.457,1,0,0,0,0,0.54

  cam_corridor:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:my_password@10.0.40.11:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://frigate:my_password@10.0.40.11:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam_corridor
    birdseye:
      order: 3
    ui:
      order: 3
    motion:
      mask: 0.73,0.907,0.73,0.949,0.979,0.955,0.979,0.909

  cam_16:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:my_password@10.0.40.12:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://frigate:my_password@10.0.40.12:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam_16
    birdseye:
      order: 4
    ui:
      order: 4
    motion:
      mask: 0.744,0.924,0.744,0.974,0.991,0.978,0.991,0.93

  cam_20:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:my_password@10.0.40.13:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://frigate:my_password@10.0.40.13:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: cam_20
    birdseye:
      order: 5
    ui:
      order: 5
    motion:
      mask: 0.74,0.929,0.741,0.97,0.992,0.972,0.99,0.93

camera_groups:
  Monitoring:
    order: 1
    icon: LuView
    cameras: birdseye
```

**Comment by breakingspell** [comment]
Hello, here is my working Frigate and Card configuration for two-way audio with the Reolink Wifi Doorbell. I just stepped outside to confirm it works:

```yaml
go2rtc:
  webrtc:
    candidates:
      - <FRIGATE_IP>:8555
      - stun:8555
  streams:
    frontDoorBell:
      - ffmpeg:http://<REOLINK_IP>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=$USER&password=$PASS#video=copy#audio=copy#audio=opus
      - rtsp://$USER:$PASS@<REOLINK_IP>/Preview_01_sub
    frontDoorBell_sub:
      - ffmpeg:http://<REOLINK_IP>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=$USER&password=$PASS
```

```yaml
type: custom:advanced-camera-card
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - webrtc
cameras:
  - camera_entity: camera.frontdoorbell
menu:
  style: outside
  buttons:
    mute:
      enabled: true
    microphone:
      enabled: true
```

It looks like a few things on yours need corrected:

- The go2rtc stream setup to mix http+flv+opus on the primary stream with the rtsp substream is critical, It looks like yours has an additional RTSP main stream that could be causing the issue. 
  - For some reason these cameras hate RTSP, so HTTP must be used for the main stream. I found my unit would often crash/hang frigate's ffmpeg with RTSP+h264, while http+flv seems to not have this issue at all.

- Your camera's Server Settings show HTTP is disabled.  I don't know if the video feed can be used over HTTPS or if that port is simply for management. The http stream is still authenticated, so it's secure enough. 

- The card configuration references a go2rtc URL and stream name (not needed with Frigate integration). Otherwise it looks correct for the webrtc provider. 

Hope this helps! The video does "blip" out for a split second while the connection is established, but holding down the microphone button on the camera card does work to relay audio to the doorbell speaker.
