### ISSUE TITLE
Card always loading the substream first ?

### ISSUE THREAD

**Issue by alenzurfluh** [dermotduffy/advanced-camera-card#2000]
Hi,

I'm trying to display the main stream of my doorbell camera on a Home Assistant dashboard using advanced-camera-card.

Here's my current card configuration:

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.haustuere
    live_provider: go2rtc
    go2rtc:
      stream: haustuere_main
grid_options:
  columns: 12
  rows: 1
```
Setting the stream property to my main stream is partially working. However, when the page loads, the card briefly shows the **substream** (for about 1–2 seconds) before switching to the main stream.

Unfortunately, my camera uses different aspect ratios for the two streams:

- Main: 1920x1080 (16:9)
- Sub: 704x576 (4:3)

This causes a visual "jump" from 4:3 to 16:9 during initial loading, which looks a bit odd.

I have two questions:

Is it expected that the card initially shows the substream—even when specifying the main stream via the stream option like in my config?

Is there a way to prevent this behavior? As a fallback, is it possible to force the substream to also display as 16:9 to avoid the layout shift?

Thanks in advance!

**Comment by dermotduffy** [comment]
While the card is waiting for the stream to load, it will show still images of the Home Assistant entity (that refresh every 1/second) instead of showing you the media player loading in your browser. I suspect Home Assistant is providing stills from the "other" stream. You can simply turn that behavior off with:

```yaml
live:
  show_image_during_load: false
```

**Comment by alenzurfluh** [comment]
you are right when I try this there is no more image when the page is loaded -  you can now see a loading spinner though - but the size used by the card still seems to be in the format of the substream.  

Is there maybe a way to force the camera entity to take still images using my main stream?

I've made short video showing this: https://youtu.be/-pAHepemnpU

**Comment by dermotduffy** [comment]
> the size used by the card still seems to be in the format of the substream.

No, I think it's just using the minimum card size (`100px`) since it cannot know the size of the stream until it loads.

> Is there maybe a way to force the camera entity to take still images using my main stream?

This is a question for whatever integration provides that camera entity. I don't know :-)

Two other ideas:

Hard code the camera dimensions in the card (see [documentation](https://card.camera/#/configuration/cameras/README?id=dimensions)), something like this:
```yaml
cameras:
  - camera_entity: camera.haustuere
    live_provider: go2rtc
    go2rtc:
      stream: haustuere_main
    dimensions:
      aspect_ratio: 4:3     <---- Set this to whatever aspect ratio you want
```

Or just hard-code the dimensions of the entire card (will affect all views, so may have some unintended consequences):

```yaml
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: 4/3      <--- Whatever aspect ratio you want
```
