### ISSUE TITLE
PTZ controls customize default state and appearance

### ISSUE THREAD

**Issue by zolakt** [dermotduffy/advanced-camera-card#2003]
Hi, first of all, thanks for the great work you have done with this card.

I have a few suggestion to imporive the UI for the PTZ controls.

I found this discussion https://github.com/dermotduffy/advanced-camera-card/issues/1819, and while I agree it's an improvement, I think it's pretty opinionated. Having a configurable default state, as mentioned initially, would definetly be more flexible, than just forcing the state based the user-agent. Why would I only want them hidden initially on mobile, but not on desktop? Something like On/Off/UserAgent would be great. Personally, I very rarely use PTZ, so having it always show on desktop is a little annoying. Literally the first thing I do whenever I open this card is click the button to hide the PTZ controls.

Next, it would be great if the styling of the PTZ buttons would be configurable, so you can have separate buttons (not this wheel thing) similar to how Frigate UI has it. The wheel looks nice, but especially for mobile, it's not very practicle for us fat-fingered people. You guys must have very small fingers and/or huge phones :)

**Comment by BelayFR** [comment]
Shared @zolakt comment, especially the second point (PTZ styling). I understood this was formerly possible with the custom elements approach but the `type : custom:frigate-card-ptz` is no longer referred in the documentation.
I found this old piece of YAML linked to a Youtube video 
```
elements:
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.frigate1
    elements:
      - type: custom:frigate-card-ptz
        orientation: vertical
        style:
          transform: none
          right: 43%
          top: 60%
        service: mqtt.publish
        data_left:
          topic: myhome/dafang1/motors/horizontal/set
          payload: left
        data_right:
          topic: myhome/dafang1/motors/horizontal/set
          payload: right
        data_up:
          topic: myhome/dafang1/motors/vertical/set
          payload: up
        data_down:
          topic: myhome/dafang1/motors/vertical/set
          payload: down
```

Although I assume the PTZ configuration is made easier now, having the capacity to customize the PTZ styling would be great. 
Frigate approach is a valid one.
@dermotduffy  Is there already a valid workaround available (for techno savvy not yet developer kind people)

**Comment by dermotduffy** [comment]
## On or Off

> It would be nice if the default state of the PTZ controls would be configurable. I found this discussion https://github.com/dermotduffy/advanced-camera-card/issues/1819, and while I agree it's an improvement, I think it's pretty opinionated. Having a configurable default state, as mentioned initially, would definetly be more flexible than just forcing the state based on the user-agent. Why would I only want them hidden initially on mobile, but not on desktop? Something like On/Off/UserAgent would be great. Personally, I very rarely use PTZ, so having it always show on desktop is a little annoying. Literally the first thing I do whenever I open this card is click the button to hide the PTZ controls.

Why not just do something like this that disables the controls by default, but enables the button in the menu to toggle them on/off at will:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.foo
menu:
  buttons:
    ptz_controls:
      enabled: true
live:
  controls:
    ptz:
      mode: "off"
```

## Styling

Personally, I find the wheel much more intuitive than the "row of buttons!", but having additional styling (or perhaps sizing) flexibility is always a good thing.

> @dermotduffy Is there already a valid workaround available (for techno savvy not yet developer kind people)

Two ideas you can experiment with now (without any code work):
 - Pass CSS styling in directly, using the `live.controls.ptz.style` attribute (see [docs](https://card.camera/#/configuration/live?id=ptz)). This styling applies to the overall control, not the individual buttons, so this is probably good for position, not necessarily individual button styling.
 - Just "build your own" by using icon or menu icon [elements](https://card.camera/#/configuration/elements/stock/README?id=icon) that call the [PTZ actions](https://card.camera/#/configuration/actions/custom/README?id=ptz). This is all the "wheel" is doing anyway, it's just a UI on top of calling those same actions you could call from whatever custom icons / elements you want.
