### ISSUE TITLE
Reolink snapshot images stream doesn't load correctly

### ISSUE THREAD

**Issue by haitham506** [dermotduffy/advanced-camera-card#2010]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.6.3
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
date: 2025-04-14T18:19:17.553Z
lang: en
timezone: *****
git:
  hash: 54ee1e1
  build_date: Mon, 14 Apr 2025 15:59:20 GMT
  commit_date: Mon, 14 Apr 2025 16:58:17 +0100
ha_version: 2025.4.2
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.aaa_snapshots
      title: aaa
      live_provider: ha
      engine: generic
      image: {}
      triggers:
        occupancy: false
      webrtc_card: {}
  view:
    actions:
      double_tap_action:
        action: custom:advanced-camera-card-action
        advanced_camera_card_action: fullscreen
    default_reset:
      interaction_mode: all
  menu:
    button_size: 38
    buttons:
      cameras:
        enabled: false
      media_player:
        enabled: false
      live:
        enabled: false
      fullscreen:
        enabled: false
      iris:
        enabled: true
    style: hover-card
  live:
    draggable: false
    zoomable: true
    lazy_load: false
    controls: {}
  image: {}
  performance:
    style:
      border_radius: false
      box_shadow: false
    features:
      card_loading_indicator: false
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '4:3'
  cameras_global:
    dimensions:
      layout: {}
  status_bar:
    style: none
```

**[REQUIRED] Description of problem:**

When using Reolink Snapshot Images Stream, There will be an Icon on the Top Right saying (Waiting for live stream to load ...) but the snapshot stream works fine. 

![Image](https://github.com/user-attachments/assets/312f1b4e-41a8-4451-95ad-2f548835a362)

**Comment by dermotduffy** [comment]
> When using Reolink Snapshot Images Stream, There will be an Icon on the Top Right saying (Waiting for live stream to load ...) but the snapshot stream works fine.

No, I think the issue is the stream is not loading (I can reproduce, I just never tested with the "snapshot" stream before). You think it's working because the card is refreshing a snapshot every 1 second, which is probably what you want anyway ;-) If you're happy with that, you can just set your live provider to `image` and the little logo will go away.

However, the stream _should_ also load correctly...and that's a bug.

**Comment by dermotduffy** [comment]
I doubt it, at least I haven't gotten around to it yet. [Contributions welcome](https://github.com/dermotduffy/advanced-camera-card/issues/1248) if you'd like a faster or more deterministic resolution. Otherwise, I always update the issue and mark it closed when I've been able to prioritize it.

**Comment by dodgerbluee** [comment]
Mine presented this issue and was fixed by naming the camera name (cameras section) the same name as the go2rtc stream name.

Example:

```
go2rtc:
  streams:
    doorbell:
      - "ffmpeg:http://camera_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"
      - rtsp://camera_ip/Preview_01_sub
    doorbell_sub:
      - "ffmpeg:http://camera_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password"


cameras:
    living:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/living?video&audio=aac
            input_args: preset-rtsp-restream-low-latency
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/living_sub?video=copy&audio=aac
            input_args: preset-rtsp-restream-low-latency
            roles:
              - detect
```
