### ISSUE TITLE
focus-trap already defined – Error on iOS Companion App and Chrome (macOS)

### ISSUE THREAD

**Issue by lionel85** [dermotduffy/advanced-camera-card#2013]
**[REQUIRED] Description of problem:**

Hi 👋

I'm using the latest version of `advanced-camera-card` installed via HACS.  
I'm getting the following error when trying to view the card:

`Error: Failed to execute 'define' on 'CustomElementRegistry': the name "focus-trap" has already been used with this registry`

This happens:
- On iOS (iPhone, Companion App)
- On macOS (Google Chrome)
- Even after clearing frontend cache, reloading resources, and restarting Home Assistant

My YAML config is very minimal:
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.cour_profile000
    live_provider: auto
    go2rtc:
      modes: []
```
I suspect that the issue is due to the card or one of its dependencies trying to register focus-trap multiple times.
Let me know if I can help debug further! 😊
