### ISSUE TITLE
Rotate primary camera in grid every 'x' seconds

### ISSUE THREAD

**Issue by Zero-Circle** [dermotduffy/advanced-camera-card#2016]
Hi guys i have this code.

I would like to rotate the cameras through the grid to continiously show a new main picture every 'x' seconds, is this something that possible?

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.entry_gate
  - camera_entity: camera.exit_driveway
  - camera_entity: camera.exit_gate
  - camera_entity: camera.yard_left
  - camera_entity: camera.yard_right_3
    image: {}
media_gallery:
  controls:
    thumbnails:
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
media_viewer:
  auto_play:
    - visible
  draggable: false
  zoomable: false
  lazy_load: false
  display:
    mode: grid
live:
  draggable: false
  zoomable: false
  lazy_load: true
  display:
    mode: grid
  transition_effect: slide
view:
  triggers:
    filter_selected_camera: false
    show_trigger_status: false
    actions:
      trigger: default
```

**Comment by dermotduffy** [comment]
> I would like to rotate the cameras through the grid to continiously show a new main picture every 'x' seconds, is this something that possible?

Something like this might be what you're looking for (rotates through the cameras every 10 seconds). Let me know if I misunderstood:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.office
  - camera_entity: camera.front_door
view:
  default_cycle_camera: true
  default_reset:
    every_seconds: 10
```
