### ISSUE TITLE
Wrong stream used in MSE mode

### ISSUE THREAD

**Issue by SkeLLLa** [dermotduffy/advanced-camera-card#2017]
**Checklist:**

[x] Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
[x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.6.5
browser: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
date: 2025-04-18T09:10:26.937Z
lang: en
timezone: Europe/Warsaw
git:
  hash: 2eb0d9e
  build_date: Wed, 16 Apr 2025 09:59:19 GMT
  commit_date: Wed, 16 Apr 2025 10:58:18 +0100
ha_version: 2025.4.2
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      ***: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.frontyard_side_camera
      go2rtc:
        stream: side-frontyard
        modes:
          - mse
      live_provider: go2rtc
  grid_options:
    columns: 12
    rows: auto
  live:
    lazy_unload:
      - hidden
  status_bar:
    popup_seconds: 15
    style: hover
    position: top
  performance:
    features:
      media_chunk_size: 256
```

go2rtc config:
```yaml
go2rtc:
  webrtc:
    udp: true         
    tcp: true                
    # other stun-turn configs

  streams:
    side-frontyard:
      # raw 2k stream
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.1:554/cam/realmonitor?channel=1&subtype=0
      # encoding for HA
      - ffmpeg:side-frontyard#video=h264#width=854#height=480#rotate=90#hardware
```

**[REQUIRED] Description of problem:**

By default camera provides 2k HEVC stream, that's consumed by Frigate. In frigate go2rtc is configured for displaying cards in HA as it shown above.

When `live_provider: go2rtc` is selected the card shows not converted stream (2k, not rotated) in MSE mode. But when webrtc mode is selected, the card start showing resized and rotated stream (maybe because it can't play HEVC in webrtc mode).

Also if both modes are configured in card, even if webrtc is selected (according to icon in a toolbar), it starts using raw stream, instead of transcoded. 

No errors are shown in console.
