### ISSUE TITLE
Help with go2RTC integration

### ISSUE THREAD

**Issue by robertofabrizi** [dermotduffy/advanced-camera-card#2018]
Hello everyone, I've set up a camera in my HAOS via the go2rtc add on. The camera is a unify camera exposed via RTSP. If i go to http://192.168.0.238:1984/ and click stream next to the camera name, i see the stream just fine. What I don't get is how I can now create a advanced camera card that leverages this go2rtc integration. I tried this from the doc:

`type: custom:advanced-camera-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      stream: office
      url: https://my.go2rtc.url:1984/
`

This is the go2rtc config:

```
streams:
  AIProIngresso:
    - rtspx://192.168.0.1:7441/ZawnnrYyAcpQBGx2
```

replacing office with AIProIngresso and https://my.go2rtc.url:1984/ with http://192.168.0.238:1984/ didn't work, there is no image showing up in the advanced camera card.
Can anyone help me out? I've gone through the docs but it's very advanced and there is nothing else for this simple use case besides the example that I mentioned above.
Thank you and happy Easter.
Roberto

**Comment by dermotduffy** [comment]
To confirm: You're not using Frigate, and are running go2rtc independently?

This is the config that I'd expect to work given the above:

```yaml
type: custom:advanced-camera-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      stream: AIProIngresso     <------- STREAM NAME FROM GO2RTC
      url: https://my.go2rtc.url:443/    <----- See note below.
```

A bigger issue here will be that your browser probably will not let you mix `https` and `http` (it will complain if you try to mix  them in your dev console, press 'F12' to access). So either you need to access both your HA dashboard AND go2rtc via `https`, or both via `http`. `go2rtc` appears to support `https` [[docs](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-api], but you'd have to set that up first.

... and  I think this is the point at which @felipecrs gives me a hard time about [this](https://github.com/dermotduffy/advanced-camera-card/issues/1984) issue, which would make this much easier...
