### ISSUE TITLE
Favourites keep snapshots but videos are removed (not exported) in frigate according to configuration

### ISSUE THREAD

**Issue by limitless-code** [dermotduffy/advanced-camera-card#2019]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.6.2
browser: >-
  Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/135.0.0.0 Mobile Safari/537.36
date: 2025-04-19T12:57:50.161Z
lang: en
timezone: Europe/London
git:
  hash: a5ffd51
  build_date: Sat, 12 Apr 2025 09:49:37 GMT
  commit_date: Sat, 12 Apr 2025 10:48:37 +0100
ha_version: 2025.4.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      6289c9f440c77bec1aa3edf8d5691da4: 5.8.0/0.15.0-6cb5cfb
      01JC8KKK4NGG1XVFZDZ8R0K9JE: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - triggers:
        occupancy: false
        entities:
          - binary_sensor.doorbell_visitor
      go2rtc:
        modes:
          - webrtc
        stream: front_door_main
      webrtc_card:
        entity: camera.front_door
      camera_entity: camera.front_door
      capabilities:
        disable: []
      live_provider: go2rtc
    - camera_entity: camera.main_drive
      triggers:
        entities: []
        occupancy: false
      dependencies:
        all_cameras: true
      go2rtc:
        modes: []
      live_provider: jsmpeg
  view:
    default: live
    camera_select: live
    triggers:
      show_trigger_status: false
      actions: {}
      filter_selected_camera: false
    default_cycle_camera: false
    default_reset: {}
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
    dim: false
  live:
    draggable: true
    microphone:
      always_connected: false
    show_image_during_load: true
    auto_mute: []
    auto_unmute: []
    lazy_load: true
    controls:
      timeline:
        show_recordings: false
      next_previous:
        style: none
      builtin: true
    transition_effect: slide
  performance:
    style:
      box_shadow: true
      border_radius: true
  menu:
    buttons:
      download:
        enabled: true
        priority: 50
      timeline:
        enabled: false
      recordings:
        enabled: true
      microphone:
        enabled: true
        type: toggle
        alignment: opposing
        priority: 49
        permanent: true
      substreams:
        enabled: true
      camera_ui:
        enabled: false
      mute:
        enabled: true
        alignment: opposing
        priority: 48
        permanent: true
      screenshot:
        enabled: true
      fullscreen:
        enabled: true
        permanent: true
        priority: 100
      cameras:
        permanent: true
        priority: 100
      live:
        permanent: true
        priority: 100
    style: hidden
  media_viewer:
    lazy_load: true
    controls:
      thumbnails:
        show_download_control: true
    auto_unmute:
      - selected
    auto_mute: []
    auto_pause:
      - hidden
    auto_play:
      - selected
  media_gallery:
    controls:
      thumbnails:
        show_download_control: false
  dimensions:
    aspect_ratio_mode: unconstrained
  cameras_global:
    dimensions:
      layout:
        fit: contain
        position:
          'y': 0
  profiles: []
  status_bar:
    popup_seconds: 5
```

**[REQUIRED] Description of problem:**

Favourites keep snapshots but videos are removed (not exported, behaviour changed in the version of frigate I am using) in frigate according to configuration (the amount of days to retain recordings) and therefore disappear. Is it possible to keep the video when snapshots or clips are marked as favourite (yellow star), I believe the method now is to export the particular timeline?
**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
