### ISSUE TITLE
No Cameras Support This View when toggling tabs, multiple cards on same dashboard

### ISSUE THREAD

**Issue by stevenmccord** [dermotduffy/advanced-camera-card#2023]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.6.5
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/135.0.0.0 Safari/537.36
date: 2025-04-21T21:27:08.338Z
lang: en
timezone: America/New_York
git:
  hash: 2eb0d9e
  build_date: Wed, 16 Apr 2025 09:59:19 GMT
  commit_date: Wed, 16 Apr 2025 10:58:18 +0100
ha_version: 2025.4.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01J88JD7Q93J9RJVAWX1W475NH: 5.8.0/0.15.0-cea210d
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.dillons_room_frigate
      live_provider: webrtc-card
      title: Dillon's Room
      icon: mdi:garage
      go2rtc:
        modes: []
      image:
        mode: camera
  view:
    default: snapshot
    camera_select: snapshot
    default_reset:
      after_interaction: true
      interaction_mode: all
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
  menu:
    alignment: bottom
    buttons:
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: true
      clips:
        enabled: false
      snapshots:
        enabled: false
        permanent: true
      image:
        enabled: false
      play:
        enabled: false
      timeline:
        enabled: false
      download:
        enabled: false
      iris:
        enabled: true
        permanent: true
    style: overlay
  status_bar:
    height: 36
    items:
      title:
        enabled: true
      resolution:
        enabled: false
      technology:
        enabled: false
      engine:
        enabled: false
    style: overlay
  media_viewer:
    auto_play:
      - selected
    auto_pause:
      - unselected
    display:
      mode: single
    draggable: false
  image:
    mode: camera
  performance:
    style:
      border_radius: true
      box_shadow: true
  media_gallery:
    controls:
      thumbnails:
        size: 175
      filter:
        mode: none
  profiles: []
  live:
    preload: true
    draggable: false
    zoomable: false
    lazy_load: true
  elements:
    - type: state-label
      entity: sensor.blank_blank
      prefix: Dillon's Room
      tap_action:
        action: navigate
        navigation_path: /config/areas/area/dillons_room
      style:
        bottom: 4px
        right: 0px
        color: rgb(255,255,255)
        font-size: 16px
        transform: rotate(0deg)

```

**[REQUIRED] Description of problem:**

I am on the latest version, but I think think this has been happening with all releases, I just put it all together.  When I refresh the page or load the page for the first time, it loads correctly, but if I go to another link on the sidebar of home assistant (e.g., Areas, Energy, Logbook) and then go right back to the dashboard I get the following error on my cards.  This is in a chrome desktop browser on a MacBook:

<img width="511" alt="Image" src="https://github.com/user-attachments/assets/e18540a6-df33-4adf-a934-6198457068af" />

Then if I refresh the page it will load the card and image.

I see the following in the console when I return to the dashboard (before refreshing)

```
No cameras support this view.  card-807d37f1.js:75
zoomer-3a47b511.js:1 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

This also occurs if I edit the dashboard it presents itself again.  

As a note, I have multiple Advanced Cards on the same dashboard.
