### ISSUE TITLE
Question about using the render_entities config

### ISSUE THREAD

**Issue by danhajduk** [dermotduffy/advanced-camera-card#2027]
Hi!
First, thank you for the fantastic work on Advanced Camera Card — it's amazing!

I'm trying to correctly use the render_entities feature to trigger a refresh of the camera view when an entity changes. However, I'm having trouble getting it to actually re-render the camera when my entity updates.

Here is the relevant part of my card YAML configuration:
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.kids_bedroom
    live_provider: go2rtc
    go2rtc:
      stream: kids_bedroom_main
      modes:
        - mse
        - webrtc
        - mjpeg
    triggers:
      occupancy: false
      motion: false
  - camera_entity: camera.front_door_2
    go2rtc:
      stream: front_door_main
      modes:
        - webrtc
        - mse
        - mjpeg
    triggers:
      entities:
        - binary_sensor.front_door_person_detected
        - binary_sensor.front_door_visitor_detected
      occupancy: true
  - camera_entity: camera.fallback_camera
    triggers:
      entities:
        - binary_sensor.kids_bedroom_camera_offline
      occupancy: true
      priority: 2
  - camera_entity: camera.privacy_camera
    triggers:
      motion: false
      occupancy: true
      entities:
        - switch.kids_bedroom_privacy
view:
  default: live
  default_reset:
    after_interaction: true
  render_entities:
    - input_boolean.ha_test_button
```

Steps I've tried:

Confirmed that toggling input_boolean.ha_test_button works and shows correct state change in Home Assistant Developer Tools.

Confirmed that the input_boolean.ha_test_button is properly listed in render_entities.

Hard refreshed the browser (Ctrl+Shift+R) to clear any cache.

Opened browser console — no rebuild or re-render events observed when toggling the entity.

Running Advanced Camera Card version 7.6.5 installed via HACS.

Question:

Is this the correct and supported way to trigger a camera view re-render via render_entities?

Is there anything I should structure differently?

Should the re-render be immediately visible (for example, reloading the live video feed) when the render_entities triggers?

Is additional configuration needed on the entity (e.g., attributes or certain types of state changes)?

Thanks again for your time and for maintaining this card — really appreciate the effort!

**Comment by dermotduffy** [comment]
Hi, thank you for using the card and for the feedback!

> Is this the correct and supported way to trigger a camera view re-render via render_entities?

No. `render_entities` ([docs](https://card.camera/#/configuration/view?id=view)) is for super obscure and rarely needed cases that do not include this one.

I think it would help to describe what you want to achieve. You are listing `input_boolean.ha_test_button`, what is it you want to happen when that entity changes? You say you want to `trigger a refresh of the camera view`, does that mean to:

 - Reset the whole card to the default? (If yes, see `view.default_reset.entities` in docs above).
 - Select a particular camera (If yes, you'd like this entity under that camera's triggers).

**Comment by danhajduk** [comment]
Thank you for your fast response. 
I'm having an issue with my dashboard, which keeps freezing. It happens only on that one device. Right now, I keep refreshing the browser, but it's not pretty. The stream is active (I can see it on another dashboard), it just seems that this Linux-based tablet with Chromium browser ( happens on Firefox and Chrome) keeps freezing with the advanced camera card. I was hoping to have an elegant way to restore the card.

**Comment by dermotduffy** [comment]
> It just seems that this Linux-based tablet with Chromium browser ( happens on Firefox and Chrome) keeps freezing with the advanced camera card. 

You can try `view.default_reset.entities` (as mentioned above), which is supposed to force the card to reload the default view. However, if the card is somehow freezing on one device, I'm not sure it is going to respond to that change -- you could test it. I'd rather see if we can fix the freezing though ... but that is going to be challenging unless you are capable of debugging it on that device yourself.

**Comment by danhajduk** [comment]
I can debug it but I did not see in documentation how to enable debug logging. Right now I don't see anything in the console.

**Comment by dermotduffy** [comment]
There is some light logging that can be enabled with:

```yaml
debug:
  logging: true
```

But if the card is genuinely freezing, you'd need to be confident using the browser debugger (and since it's a tablet -- remotely) to be able to step through the code to see where it's freezing.

**Comment by danhajduk** [comment]
OK I think I might have found the error.
Not sure I understand it:

``` markdown
cal
Exception
: 
TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Set>' at http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:88381 at Za (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:88462) at to (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:96738) at no (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:98343) at Ff (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:158277) at bg._calculateTrueChange (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:83:4043) at bg.setState (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:83:3799) at pS._setConditionStateIfNecessary (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:92:28213) at pS.handleCameraEvent (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:92:26842) at G.eventCallback [as _eventCallback] (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:77:251)
message
: 
"Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Set>'"
stack
: 
"TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Set>'\n    at http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:88381\n    at Za (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:88462)\n    at to (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:96738)\n    at no (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:98343)\n    at Ff (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:75:158277)\n    at bg._calculateTrueChange (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:83:4043)\n    at bg.setState (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:83:3799)\n    at pS._setConditionStateIfNecessary (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:92:28213)\n    at pS.handleCameraEvent (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:92:26842)\n    at G.eventCallback [as _eventCallback] (http://10.0.0.100:8123/hacsfiles/advanced-camera-card/card-807d37f1.js:77:251)"
[[Prototype]]
: 
Error
this
: 
undefined
a
: 
undefined
e
: 
Set(1)
[[Entries]]
0
: 
"camera.kids_bedroom"
value
: 
"camera.kids_bedroom"
size
: 
1
[[Prototype]]
: 
Set
i
: 
undefined
n
: 
"Set"
t
: 
false
```

**Comment by dermotduffy** [comment]
Wonder if it's an older device with an old webview library that's no longer compatible with modern Javascript constructs?

**Comment by danhajduk** [comment]
It's not really a standard tablet. It was a lenovo windows tablet that I have debian installed on it:

### 📋 Device Info

**CPU:**  
- Model: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz  
- Architecture: x86_64  
- Cores: 8 (4 physical cores × 2 threads)  
- CPU Max Frequency: 4.4 GHz

**RAM:**  
- Total: 15 GB  
- Used: 7.1 GB  
- Free: 7.4 GB  
- Swap: 979 MB total (774 MB used)

**GPU:**  
- Intel TigerLake-LP GT2 [Iris Xe Graphics]

**Operating System:**  
- Debian GNU/Linux 12 (bookworm)
- Kernel: 6.1.0-31-amd64

**Chromium Version:**  
- Chromium 133.0.6943.126 (Built on Debian GNU/Linux 12)

**System Uptime:**  
- *(optional: add output of `uptime -p` here if you want)*

**Running as user:**  
- *(optional: add `whoami` output if needed, looks like `dan`)*

---

- Streams are displayed using MSE/WebRTC modes via go2rtc in Frigate.

**Comment by dermotduffy** [comment]
Probably not that then. Does it just immediately trigger those errors, or you do something specific and it happens?

**Comment by dermotduffy** [comment]
Does it happen if you don't use browser_mod?

**Comment by danhajduk** [comment]
> Does it happen if you don't use browser_mod?

Yes it does. It takes longer if I have only that card on my dashboard

**Comment by danhajduk** [comment]
OK,
So i have this in my config now:

```yaml
        view:
          default: live
          default_reset:
            entities:
              - input_boolean.ha_test_button

```
I have the boolean toggle every 5 minutes.
The Dashboard has been working for over an hour now with no issues. I'll keep monitoring over the night, and I'll close the card if it is solved.
