### ISSUE TITLE
[SOLVED] How to automatically switch to display grid mode when entering fullscreen?

### ISSUE THREAD

**Issue by MLAN1O** [dermotduffy/advanced-camera-card#2029]
Hi, first of all, thank you for this amazing card!
I'm trying to configure the card so that when entering fullscreen, it automatically switches the live.display.mode to grid.

I tried using an overrides block like this:

```yaml
overrides:
  - conditions:
      - condition: fullscreen
        fullscreen: true
    merge:
      live:
        display:
          mode: grid
```

However, this approach doesn't seem to work as expected. Is there a recommended way to trigger the grid view automatically when entering fullscreen, without manually changing the display mode?

Thanks in advance for your help!

**Comment by MLAN1O** [comment]
**[SOLVED]**

I solved the problem by implementing the following solution and added a double-tap action to toggle fullscreen mode. This allows for easy switching between grid and single view.

```yaml
automations:
  - conditions:
      - condition: fullscreen
        fullscreen: true
    actions:
      - action: custom:advanced-camera-card-action
        advanced_camera_card_action: display_mode_select
        display_mode: grid

  - conditions:
      - condition: fullscreen
        fullscreen: false
    actions:
      - action: custom:advanced-camera-card-action
        advanced_camera_card_action: display_mode_select
        display_mode: single

live:
  actions:
    double_tap_action:
      action: custom:advanced-camera-card-action
      advanced_camera_card_action: fullscreen
```

Now, when I double tap on the camera image, the card switches to fullscreen and automatically changes to grid mode, showing all cameras. When exiting fullscreen, it switches back to single mode!
