### ISSUE TITLE
Fixed camera.  Can't get rid of PTZ, home, tilt, zoom buttons.

### ISSUE THREAD

**Issue by peteDDD** [dermotduffy/advanced-camera-card#2033]
I know this should be simple but I am still not getting it right after trying many things.
Objective: not have tilt, zoom, and home buttons appear in selected advanced_camera_cards

Example:  
from frigate.yml

```
...
go2rtc:
  streams:
    cp2_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.102:554/11
    cp2_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.102:554/12
...

cameras:
  cp2:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/cp2_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/cp2_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: cp2_hi
      height: 720
      quality: 8
```

Advanced camera card config:
```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.cp2
    live_provider: go2rtc
    go2rtc:
      stream: cp2_hi
    live:
      controls:
        ptz:
          mode: "off"
          hide_pan_tilt: true
          hide_home: true
          hide_zoom: true
```

what I am seeing:

![Image](https://github.com/user-attachments/assets/697e969f-021b-4857-a79f-2e45853f04de)

the controls are initially not there when the card loads but then after a few seconds, they appear.  With the settings above, this delayed appearance is slowed a bit, but the buttons still appear.

Surely I am just missing something basic here.  Thanks!

**Comment by dermotduffy** [comment]
You have an indentation error in your config. I'd recommend using the visual card editor which is perhaps more user friendly. Here's the mistake with the indentation fixed:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.cp2
    live_provider: go2rtc
    go2rtc:
      stream: cp2_hi
live:             <----------------- NOW AT THE TOPLEVEL
  controls:
    ptz:
      mode: "off"
```
