### ISSUE TITLE
Reolink PTZ support should support `Reolink E1 Zoom`

### ISSUE THREAD

**Issue by InyoEndo** [dermotduffy/advanced-camera-card#2034]
Unsure if its the model of E1 Zoom (IPC_515BSD6) that I am using, possibly this does work out of the box for the newer model? But for my model of Reolink E1 Zoom the pan and tilt works, but dont see any controls/icons for the zoom function.

![Image](https://github.com/user-attachments/assets/129f9dd6-58cd-4f19-bab8-341fd381454e)

Since the zoom for the camera is setup as a number data type between 0-32, and is not an entity which has a speed attribute, I assume that might be why it doesn't work out of the box. I have been able to make the zoom function work with the camera through a convoluted process, using a Picture Glance card and Spook allowing me to use a number.increment method. So its possible to do, just would like for it to work on the advanced camera card. See code:

```
  - entity: number.bedroom_zoom
    icon: mdi:magnify-plus
    tap_action:
      action: call-service
      service: number.increment
      service_data:
        entity_id: number.bedroom_zoom
    hold_action:
      action: none
    double_tap_action:
      action: none
  - entity: number.bedroom_zoom
    icon: mdi:magnify-minus
    tap_action:
      action: call-service
      service: number.decrement
      service_data:
        entity_id: number.bedroom_zoom
    hold_action:
      action: none
    double_tap_action:
      action: none
```
