### ISSUE TITLE
Global Image setting not working, but camera-specific image setting works

### ISSUE THREAD

**Issue by loocd** [dermotduffy/advanced-camera-card#2036]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

tried this - nothing happens when long-pressing the iris button. here is the card code:
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.tuerklingel
  - camera_entity: camera.wand
    image:
      url: https://plus.unsplash.com/premium_photo-1667680403604-c4b69984eef8?q=80&w=2921&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      mode: url
  - camera_entity: camera.wohnzimmer
    image:
      url: https://plus.unsplash.com/premium_photo-1667680403604-c4b69984eef8?q=80&w=2921&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      mode: url
view:
  default: live
status_bar:
  style: outside
  position: bottom
  height: 25
  items:
    title:
      enabled: true
    resolution:
      enabled: true
    technology:
      enabled: false
    engine:
      enabled: false
live:
  controls:
    ptz:
      position: bottom-right
      orientation: vertical
      hide_home: true
    next_previous:
      style: none
    thumbnails:
      show_details: true
      show_favorite_control: false
      show_timeline_control: false
      mode: none
    timeline:
      mode: none
    builtin: false
  display:
    mode: grid
    grid_selected_position: first
menu:
  position: top
  buttons:
    iris:
      enabled: true
    cameras:
      enabled: false
    substreams:
      permanent: true
      alignment: opposing
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      alignment: matching
      permanent: true
    expand:
      enabled: true
      permanent: true
      alignment: matching
      priority: 49
    timeline:
      enabled: false
    media_player:
      enabled: false
    microphone:
      enabled: true
      alignment: opposing
      permanent: true
    play:
      enabled: true
      alignment: opposing
      permanent: true
    mute:
      enabled: true
      alignment: opposing
      permanent: true
    display_mode:
      permanent: true
      priority: 51
    ptz_controls:
      enabled: false
timeline: {}
image:
  url: >-
    https://plus.unsplash.com/premium_photo-1667680403604-c4b69984eef8?q=80&w=2921&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  mode: url

```

**[REQUIRED] Description of problem:**

I'd like to add a custom image that shows up while the stream is loading (to replace the purple flowers). However, when setting this globally, the image does not get replaced and I still get the purple flowers. But when setting it for a specific camera, I do get the proper image.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
I stumbled upon this issue, but it seems it never got a reply for the original poster

**Comment by dermotduffy** [comment]
> However, when setting this globally

When you say this, what do you mean? You are setting the default image for the the `image` view -- this is not related to what shows up with a `live` view stream is loading.

If you're trying to just set the same configuration for every camera, without needing to repeat it, try this (not tested, from memory):

```yaml
cameras_global:
  image:
    url: https://plus.unsplash.com/premium_photo-1667680403604-c4b69984eef8?q=80&w=2921&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
    mode: url
```
