### ISSUE TITLE
"timeline view" on one of cameras disappeared

### ISSUE THREAD

**Issue by aik** [dermotduffy/advanced-camera-card#2038]
**Checklist:**

I did clear cookies and cache .
Restarted HA and Frigate (no change).

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.6.5
browser: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
date: 2025-05-06T07:55:55.832Z
lang: en
timezone: Australia/Sydney
git:
  hash: 2eb0d9e
  build_date: Wed, 16 Apr 2025 09:59:19 GMT
  commit_date: Wed, 16 Apr 2025 10:58:18 +0100
ha_version: 2025.4.3
custom_integrations:
  frigate:
    detected: true
    version: 5.8.0
    devices:
      01JT6166A4JQ60H4PND3EB8Z1E: 5.8.0/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.zen
  performance:
    features:
      card_loading_indicator: false
      animated_progress_indicator: false
    style:
      border_radius: false
      box_shadow: false
```

**[REQUIRED] Description of problem:**

9 cameras configured in frigate, all configured to record, all have history available in the frigate webui.
8 cameras also have "timeline view" in the card.
1 camera has only 3 buttons: "liveview", "fullscreen", "send to media player".
yaml in HA and frigate is the same for all 9 cameras

How do I get the "timeline view" button back?

**[OPTIONAL] Last working release (if known):**

All the buttons were there but then there was a spike in the server (which runs frigate), I disabled the offending camera but since the this one camers does not have all the buttons. The server is i5-4670 which is not lightning fast.
Frigate integration is v5.9.2.
