### ISSUE TITLE
Fullscreen Toggle Ignores grid_selected_position: first Setting

### ISSUE THREAD

**Issue by igawa6** [dermotduffy/advanced-camera-card#2046]
Thanks so much for the fantastic grid card, its flexibility and performance have been a huge help in organizing my camera views! I really appreciate the effort and thought you’ve put into making the display options so customizable.

**However, What I Expected When I set:**

display:
  mode: grid
  grid_columns: 2
  grid_selected_position: first

I expect the grid to always keep the “first” card in the selected (highlighted) position—both in normal and fullscreen modes.

**What Happened Instead**

On initial load and after tapping a camera, the “first” position is honored correctly.

As soon as I toggle the fullscreen icon, the grid layout resets and no longer respects grid_selected_position: first.

Exiting fullscreen leaves the cards in the wrong order. Only tapping the camera again restores the intended layout.

**Comment by dermotduffy** [comment]
I confirm this is not working as intended. Test config:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.office
  - camera_entity: camera.front_door
  - camera_entity: camera.landing
live:
  display:
    mode: grid
    grid_columns: 2
    grid_selected_position: first
```
