### ISSUE TITLE
Trigger Entities doesn‘t work

### ISSUE THREAD

**Issue by Maddin1684** [dermotduffy/advanced-camera-card#2048]
After` Upgrade via UI to Advanced Camera Card the trigger entities doesn‘t work anymore.
When the Sensor triggers to on There is No pulsing border and live view with the triggered Camera doesn’t come up.
With „frigate-Card“ before everything worked fine. I didn‘t Change anything After the upgrade

```
type: custom:advanced-camera-card
cameras:
  - webrtc_card:
      style: |
        .mode { display: none; }
      background: true
      mode: mse
      entity: camera.reolink_trackmix_poe_fliessendes_objektiv_0
    frigate: {}
    title: Hof
    triggers:
      occupancy: true
      entities:
        - binary_sensor.reolink_trackmix_poe_haustier
        - binary_sensor.reolink_trackmix_poe_person
      motion: false
    icon: phu:reolink-trackmix
    image:
      mode: entity
    dependencies:
      all_cameras: false
    camera_entity: camera.reolink_trackmix_poe_fliessendes_objektiv_0
    go2rtc:
      modes: []
    live_provider: ha
    cast: {}
    reolink:
      media_resolution: high
  - live_provider: ha
    webrtc_card:
      style: |
        .mode { display: none; }
      background: true
      mode: mse
      entity: camera.garten_standardauflosung
    reolink:
      media_resolution: high
    camera_entity: camera.garten_standardauflosung
    triggers:
      entities:
        - binary_sensor.garten_person_2
        - binary_sensor.garten_tier_2
        - binary_sensor.contact_sensor_2
      occupancy: true
      events: []
      motion: false
view:
  default: live
  camera_select: live
  default_reset:
    after_interaction: false
  default_cycle_camera: false
  keyboard_shortcuts:
    ptz_left:
      key: ArrowLeft
    ptz_right:
      key: ArrowRight
    ptz_up:
      key: ArrowUp
    ptz_down:
      key: ArrowDown
    ptz_zoom_in:
      key: +
    ptz_zoom_out:
      key: "-"
    ptz_home:
      key: h
    enabled: false
  triggers:
    show_trigger_status: true
    filter_selected_camera: false
    actions:
      trigger: live
```

**Comment by Maddin1684** [comment]
has anyone a solution?
I‘ve checken triggers in the developer Tools. Everything works!
 
The Card itself does nothing.

**Comment by dermotduffy** [comment]
> After` Upgrade via UI to Advanced Camera Card the trigger entities doesn‘t work anymore.

I didn't get to look into this yet, but if you just upgraded, can you make sure you only have resources that refer to Advanced Camera Card (and not Frigate card), see [this troubleshooting entry](https://card.camera/#/troubleshooting?id=duplicate-versions-duplicate-element-registrations-custom-element-not-found-advanced-camera-card).

If that doesn't help, can you paste in the card [diagnostics](https://card.camera/#/support?id=diagnostics-missing-in-issue) .

**Comment by Maddin1684** [comment]
```
card_version: 7.6.5
browser: >-
  Mozilla/5.0 (iPhone; CPU iPhone OS 18_4_1 like Mac OS X) AppleWebKit/605.1.15
  (KHTML, like Gecko) Home Assistant/2025.3 (io.robbie.HomeAssistant;
  build:2025.1205; iOS 18.4.1) Mobile/HomeAssistant, like Safari
date: 2025-05-21T14:56:17.498Z
lang: en
timezone: Europe/Berlin
git:
  hash: 2eb0d9e
  build_date: Wed, 16 Apr 2025 09:59:19 GMT
  commit_date: Wed, 16 Apr 2025 10:58:18 +0100
ha_version: 2025.5.2
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - webrtc_card:
        style: |
          .mode { display: none; }
        background: true
        mode: mse
        entity: camera.reolink_trackmix_poe_fliessendes_objektiv_0
      frigate: {}
      title: Hof
      triggers:
        occupancy: false
        entities:
          - binary_sensor.reolink_trackmix_poe_haustier
          - binary_sensor.reolink_trackmix_poe_person
        motion: false
      icon: phu:reolink-trackmix
      image:
        mode: entity
      dependencies:
        all_cameras: false
      camera_entity: camera.reolink_trackmix_poe_fliessendes_objektiv_0
      go2rtc:
        modes: []
      live_provider: webrtc-card
      cast: {}
      reolink:
        media_resolution: high
    - live_provider: webrtc-card
      webrtc_card:
        style: |
          .mode { display: none; }
        background: true
        mode: mse
        entity: camera.garten_standardauflosung
      reolink:
        media_resolution: high
      camera_entity: camera.garten_standardauflosung
      triggers:
        entities:
          - binary_sensor.garten_person_2
          - binary_sensor.garten_tier_2
        occupancy: false
        events: []
        motion: false
  view:
    default: live
    camera_select: live
    default_reset:
      after_interaction: false
    default_cycle_camera: false
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
      enabled: false
    triggers:
      show_trigger_status: true
      filter_selected_camera: false
      actions:
        trigger: live
      untrigger_seconds: 5
  menu:
    style: hover-card
    position: bottom
    alignment: left
    buttons:
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      fullscreen:
        enabled: false
      mute:
        enabled: true
      expand:
        enabled: false
      microphone:
        enabled: true
      display_mode:
        enabled: false
      play:
        enabled: false
      ptz_controls:
        enabled: false
      iris:
        enabled: true
    button_size: 28
  live:
    webrtc_card:
      background: true
    preload: true
    draggable: true
    zoomable: false
    lazy_load: false
    controls:
      builtin: false
      next_previous:
        style: none
      ptz:
        hide_home: true
        hide_pan_tilt: true
        style:
          bottom: 18%
          right: 1%
        hide_zoom: true
    show_image_during_load: false
    microphone:
      always_connected: false
      disconnect_seconds: 0
    auto_play:
      - selected
      - visible
    auto_unmute: []
    auto_mute: []
    transition_effect: slide
  elements:
    - type: custom:advanced-camera-card-conditional
      conditions:
        - condition: camera
          cameras:
            - camera.reolink_trackmix_poe_fliessendes_objektiv_0
      elements:
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:launch
          tap_action:
            action: url
            url_path: https://reolink.com/ulink
        - type: conditional
          conditions:
            - condition: state
              entity: switch.reolink_trackmix_poe_aufzeichnen
              state: 'on'
          elements:
            - type: custom:advanced-camera-card-menu-state-icon
              entity: switch.reolink_trackmix_poe_aufzeichnen
              icon: mdi:cctv
              style:
                color: '#ff453a'
              tap_action:
                action: toggle
        - type: conditional
          conditions:
            - condition: state
              entity: switch.reolink_trackmix_poe_aufzeichnen
              state: 'off'
          elements:
            - type: custom:advanced-camera-card-menu-state-icon
              entity: switch.reolink_trackmix_poe_aufzeichnen
              icon: mdi:cctv-off
              tap_action:
                action: toggle
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:home
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_home
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-left-bold
          conditions:
            - condition: camera
              value: camera.front_door
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_links
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-down-bold
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_keller
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-right-bold
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_rechts
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-state-icon
          entity: light.reolink_trackmix_poe_scheinwerfer
          icon: mdi:track-light
          tap_action:
            action: toggle
        - type: custom:advanced-camera-card-menu-submenu-select
          icon: phu:panel-glass-door-4-locked
          entity: input_select.haustur_offnen
    - type: custom:advanced-camera-card-conditional
      conditions:
        - condition: camera
          cameras:
            - camera.garten_standardauflosung
      elements:
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:launch
          tap_action:
            action: url
            url_path: https://reolink.com/ulink
        - type: conditional
          conditions:
            - condition: state
              entity: switch.garten_aufzeichnen_2
              state: 'on'
          elements:
            - type: custom:advanced-camera-card-menu-state-icon
              entity: switch.garten_aufzeichnen
              icon: mdi:cctv
              style:
                color: '#ff453a'
              tap_action:
                action: toggle
        - type: conditional
          conditions:
            - condition: state
              entity: switch.garten_aufzeichnen_2
              state: 'off'
          elements:
            - type: custom:advanced-camera-card-menu-state-icon
              entity: switch.garten_aufzeichnen
              icon: mdi:cctv-off
              tap_action:
                action: toggle
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:home
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_garten_home
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-left-bold
          conditions:
            - condition: camera
              value: camera.front_door
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_garten_balkon
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-up-bold
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_garten_oben
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-down-bold
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_garten_hof
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-icon
          icon: mdi:arrow-right-bold
          tap_action:
            action: perform-action
            data:
              entity_id: input_button.ptz_garten_gang
            perform_action: input_button.press
        - type: custom:advanced-camera-card-menu-state-icon
          entity: light.garten_scheinwerfer_2
          icon: mdi:track-light
          tap_action:
            action: toggle
        - type: conditional
          conditions:
            - condition: state
              entity: input_boolean.garten_patroullie
              state: 'on'
          elements:
            - type: custom:advanced-camera-card-menu-state-icon
              entity: input_boolean.garten_patroullie
              icon: mdi:map-marker-path
              style:
                color: '#ff453a'
              tap_action:
                action: toggle
        - type: conditional
          conditions:
            - condition: state
              entity: input_boolean.garten_patroullie
              state: 'off'
          elements:
            - type: custom:advanced-camera-card-menu-state-icon
              entity: input_boolean.garten_patroullie
              icon: mdi:map-marker-path
              tap_action:
                action: toggle
  dimensions:
    aspect_ratio_mode: dynamic
  image:
    mode: url
    url: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFjwJ/lz3EGwAAAABJRU5ErkJggg==
    refresh_seconds: 0
  performance:
    features:
      animated_progress_indicator: false
      card_loading_indicator: false
    style:
      border_radius: false
  cameras_global:
    dimensions:
      layout:
        fit: contain
  profiles:
    - low-performance
  status_bar:
    style: none
  timeline:
    show_recordings: false
```

**Comment by Maddin1684** [comment]
Any solutions?
Triggers still doesn’t work

**Comment by eerison** [comment]
I am facing the same problem 😞 

it is my conf

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.poste
    go2rtc:
      modes:
        - webrtc
        - mse
    live_provider: go2rtc
    triggers:
      entities:
        - binary_sensor.poste_motion_alarm
      events:
        - snapshots
        - clips
```

**Comment by dermotduffy** [comment]
I have tested both of your configs and have not been able to reproduce the issue described. @eerison , since yours is the simpler config, can you explain how you are testing?

Here is a modified version of your config I tested with, along with some tweaked parameters:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.poste
    go2rtc:
      modes:
        - webrtc
        - mse
    live_provider: go2rtc
    triggers:
      entities:
        - switch.foo <------------------ Added a switch I can easily toggle
      events:
        - snapshots
        - clips
view:
  triggers:
    show_trigger_status: true   <----- Enable the pulsing border so I can see when the camera triggers easily
    actions:
      interaction_mode: all <---- Allow the trigger to control the card even if a human is interacting with it
```

**Comment by eerison** [comment]
Hey @dermotduffy  I never make this work, maybe I'm doing something wrong, I opened another issue, just to avoid spam for others in this issue.

#2082

**Comment by dermotduffy** [comment]
@Maddin1684 Let me know if the above interaction helps you in any way? As above, I have verified this works as expected using your config on my side, so I'm not yet able to reproduce any problem. It would help to create the smallest possible config that shows the problem, and then clearly describe what you are doing to test and what you expect to happen at each stage -- and I can try again.

**Comment by Maddin1684** [comment]
I‘ve Tried this (webrtc, go2rtc doesnt work), but nothing happens.

When i trigger the helper (Testcam) there is no pulsing border. 

```
card_version: 7.11.1
browser: >-
  Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15
  (KHTML, like Gecko) Home Assistant/2025.5 (io.robbie.HomeAssistant;
  build:2025.1264; iOS 18.5.0) Mobile/HomeAssistant, like Safari
date: 2025-06-04T14:18:20.425Z
lang: en
timezone: Europe/Berlin
git:
  hash: a3d062e
  build_date: Tue, 03 Jun 2025 03:56:19 GMT
  commit_date: Mon, 2 Jun 2025 20:55:09 -0700
ha_version: 2025.5.3
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.reolink_trackmix_poe_fliessendes_objektiv_0
      go2rtc:
        modes:
          - webrtc
          - mse
      live_provider: webrtc-card
      triggers:
        entities:
          - input_boolean.testcam
        events:
          - snapshots
          - clips
  view:
    triggers:
      show_trigger_status: true
      actions:
        interaction_mode: all
```

**Comment by Trexano99** [comment]
@Maddin1684 can you try to replace the `input_boolean` with a `binary_sensor` and try to see if works?

If you want you can create the binary_sensor from the input_boolean like this:
```
binary_sensor:
  - platform: template
    sensors:
      testcam_binary_sensor: # You can name this sensor whatever you like
        friendly_name: "Test Camera Status"
        value_template: "{{ is_state('input_boolean.testcam', 'on') }}"
```
