### ISSUE TITLE
Infinite Scroll Broken in Gallery

### ISSUE THREAD

**Issue by scott4290** [dermotduffy/advanced-camera-card#2049]
After updating via the UI to the Advanced Camera Card, the Home Assistant web interface only shows 10 rows of gallery images and the Android app only shows 25 rows.  These appear to be fixed values, and when I reach the bottom, the web page or app scrolls.  These images never continue loading.

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.camera1
profiles: []
dimensions:
  aspect_ratio_mode: unconstrained
```

As noted in this issue, the card should continue loading events/images: https://github.com/dermotduffy/advanced-camera-card/issues/2008#issuecomment-2804741892.

I recently updated from an older version of the card, before it was called advanced-camera-card (sorry, I don't have the exact previous version to reference).

I'm running Home Assistant in a docker container on Linux Mint.  I have the Advanced Camera Card/Frigate configured through HACS.

**Comment by dermotduffy** [comment]
Unhelpful, but works for me ;-) First, if you just upgraded, can you make sure you only have resources that refer to Advanced Camera Card (and not Frigate card), see [this troubleshooting entry](https://card.camera/#/troubleshooting?id=duplicate-versions-duplicate-element-registrations-custom-element-not-found-advanced-camera-card).

If that doesn't help, can you paste in the card [diagnostics](https://card.camera/#/support?id=diagnostics-missing-in-issue) .

**Comment by scott4290** [comment]
Thanks for your incredibly quick response.  The /hacsfiles/frigate-hass-card/frigate-hass-card.js JavaScript module was listed in the resources.  If possible, I'd like to suggest that the installer automatically remove the old JS.  Thanks for your help!

**Comment by scott4290** [comment]
I thought this was working after removing the old js file above.  I'm back to 10 rows in the browser and 25 rows in Android.

I'm not sure how to get the diagnostic info from the browser:
```
card_version: 7.6.5
browser: >-
  Mozilla/5.0 (Linux; Android 15; NE2215 Build/AP3A.240617.008; wv)
  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.60 Mobile
  Safari/537.36 Home Assistant/2025.4.3-15918 (Android 15; NE2215)
date: 2025-05-21T21:07:10.197Z
lang: en
timezone: America/New_York
git:
  hash: 2eb0d9e
  build_date: Wed, 16 Apr 2025 09:59:19 GMT
  commit_date: Wed, 16 Apr 2025 10:58:18 +0100
ha_version: 2025.5.1
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      8a6a788c23875d583d8657023096c567: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.camera_front
```
