### ISSUE TITLE
PTZ works in Frigate via ONVIF config, but PTZ controls in advanced-camera-card do not.

### ISSUE THREAD

**Issue by drewclauson** [dermotduffy/advanced-camera-card#2050]
**Checklist:**

✅  - Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
✅ - Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml 
card_version: 7.6.5
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101
  Firefox/138.0
date: 2025-05-21T17:11:56.909Z
lang: en
timezone: America/New_York
git:
  hash: 2eb0d9e
  build_date: Wed, 16 Apr 2025 09:59:19 GMT
  commit_date: Wed, 16 Apr 2025 10:58:18 +0100
ha_version: 2025.5.2
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      01JM04SE75W1TNDNT5ADYJNEKF: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.chicken_coop
      live_provider: go2rtc
  status_bar: {}
  menu:
    style: outside
    buttons:
      cameras:
        enabled: false
      substreams:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      recordings:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      microphone:
        enabled: true
      ptz_controls:
        enabled: false
      display_mode:
        enabled: true
      expand:
        enabled: true
  live:
    auto_play:
      - selected
    controls:
      ptz:
        hide_zoom: true
        hide_home: true
    preload: false
  view:
    default: image

```

**[REQUIRED] Description of problem:**

I have a few Foscam cameras that I have ONVIF configured in Frigate 0.51.1 and I'm able to control PTZ from the Frigate interface.  However, when I turn on a live stream in the advanced camera card, the PTZ controls in the card do not work.  I've looked around quite a bit to see if I can figure out how the communications for these commands would flow from this card to Frigate (or directly to the camera?) but I'm not exactly sure where to look to figure out where the communication might be breaking down.

Any ideas on where I should start to troubleshoot this?  Thanks!

**[OPTIONAL] Last working release (if known):**
Has never worked

**[OPTIONAL] Javascript errors shown in the web inspector:**
Checked, but none found

```text
```

**[OPTIONAL] Additional information:**
Applicable Frigate config excerpts:
```yaml
go2rtc:
  streams:
    chicken_coop:
      - ffmpeg:rtsp://[user]:[pw]@10.1.2.28:88/videoMain
      - ffmpeg:chicken_coop#audio=aac#audio=volume
cameras:
  chicken_coop:
    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 3
          mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/chicken_coop
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://[user]:[pw]@10.1.2.28:88/videoSub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - bird
        - dog
        - mouse
    onvif:
      host: 10.1.2.28
      port: 888
      user: [redacted]
      password: [redacted]
```
