### ISSUE TITLE
Thumbnails render incorrectly in >= `v7.7.0`

### ISSUE THREAD

**Issue by webjib** [dermotduffy/advanced-camera-card#2054]
I'm using the card with Frigate cameras, and now the layout of the thumbnails is broken. Font is smaller for the title, the image does not fit into the frame (cropped on the left), we've got an extra redundant title as the the first line...
 

**Card diagnostic information:**

```yaml
card_version: 7.7.1
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/18.5 Safari/605.1.15
date: 2025-05-22T07:20:16.716Z
lang: en
timezone: Europe/Paris
git:
  hash: e1e80e2
  build_date: Thu, 22 May 2025 03:13:26 GMT
  commit_date: Wed, 21 May 2025 20:12:21 -0700
ha_version: 2025.5.2
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      ***: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.portail
```

**Description of problem:**

Before the update, the thumbnails menu on the right would include for each item:

Title (in bigger font)
Date and time
Duration
Camera
Zone

Now, we have:
Title (in normal font)
Another title (filename ?) => for frigate, this is undesirable as this is the title + date and time + duration
Date and time
Duration
Camera
Zone

Also the image does not fit the frame.

<img width="506" alt="Image" src="https://github.com/user-attachments/assets/49e02347-76a9-48c1-a28f-6e05c483db92" />
