### ISSUE TITLE
Live doesn't work on iOS devices

### ISSUE THREAD

**Issue by kenevarle09** [dermotduffy/advanced-camera-card#2064]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.7.5
browser: >-
  Mozilla/5.0 (iPhone; CPU iPhone OS 18_4_1 like Mac OS X) AppleWebKit/605.1.15
  (KHTML, like Gecko) Home Assistant/2025.5 (io.robbie.HomeAssistant;
  build:2025.1264; iOS 18.4.1) Mobile/HomeAssistant, like Safari
date: 2025-05-25T07:33:39.706Z
lang: en
timezone: Asia/Manila
git:
  hash: c440019
  build_date: Sat, 24 May 2025 23:15:12 GMT
  commit_date: Sat, 24 May 2025 16:14:09 -0700
ha_version: 2025.5.3
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      03JVZ24HHR625FMH2QPEQ953NH: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.living_room_camera
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
  menu:
    buttons:
      microphone:
        enabled: true
        type: toggle
        alignment: opposing
  grid_options:
    columns: 12
    rows: 8
  dimensions:
    height: 500px
  view:
    dim: true
    interaction_seconds: 30

```

**Description of problem:**

In iOS HA companion app or Safari browser, the live stream won't work. I got the same issue with Windows PC chrome browser, but it can be solved by allowing the browser to access microphone. In iOS, that solution doesn't work.
