### ISSUE TITLE
Frigate card to display (only) most recent alert (regardless of which camera generated the alert)

### ISSUE THREAD

**Issue by peteDDD** [dermotduffy/advanced-camera-card#2066]
I would like to create a Frigate card that displays the clip of the most recent alert, regardless of which of my 8 cameras generated the alert.  How can this be achieved?  THANK YOU

**Comment by dermotduffy** [comment]
If you configure all 8 cameras in a single card, and for the first one mark all others as dependents, and then just the `clip` view, this might just work.

Something like this, not tested:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.one
    dependencies:
      all_cameras: true
  - camera_entity: camera.two
  - camera_entity: camera.three
  - camera_entity: camera.four
  - camera_entity: camera.five
  - camera_entity: camera.six
  - camera_entity: camera.seven
  - camera_entity: camera.eight
view:
  default: clip
```
