### ISSUE TITLE
Problems playing videos - Slow locally, no remote access via Nabu Casa

### ISSUE THREAD

**Issue by scott4290** [dermotduffy/advanced-camera-card#2069]
**[REQUIRED] Card diagnostic information:**

I'm not sure if this is because I increased the card size slightly or if there is another bug.  I long-press the iris and most of the time I can't get it to display diagnostic info.  When it does, I am unable to copy it to the clipboard.  The information displayed on the screen appears truncated.  I'm running card_version: 7.8.0, hash: c077f8b.

**[REQUIRED] Description of problem:**

For local access from my computer, images load fast, live view works just fine, when I select a video to play, it takes at least 10 seconds to load.
For local access from my phone, images load fast, live view works just fine, when I select a video to play, it takes at least 25 seconds to load.
For remote access, I'm using Nabu Casa.  Images load fast, live view works just fine.  Videos never load, sometimes the Home Assistant app crashes, sometimes it says reconnecting.
When I'm away from home, I can still download the videos and play them.  I just can't stream them.

**[OPTIONAL] Last working release (if known):**

Prior to the move to the advanced-camera-card, I was able to play event videos without any delay, both on my home network and remotely.  Everything worked well, even with old hardware.

**[OPTIONAL] JavaScript errors shown in the web inspector:**

No JavaScript errors in the debugger.

**[OPTIONAL] Additional information:**

I finally upgraded my Frigate config to use go2rtc with main streams and sub-streams.  My Frigate/docker machine is a gaming computer with an NVIDIA GeForce RTX 3060, so hardware is no longer the bottleneck.

Requests to play events from the Frigate web interface play videos instantly.  These requests look like:  /vod/camera_name/start/1748466000/end/1748469600/seg-318-v1.ts.  The requests through the card look like /vod/event/1748471011.699993-svd1gw/seg-1-v1.ts.  When I am attempting to access Home Assistant remotely, it doesn't appear to request anything except for the first segment.

**Comment by scott4290** [comment]
At first, I didn't think it would be helpful because my local feeds were barely working.  I made some edits to my configuration (below), and it's significantly better.  I may end up getting rid of Nabu Casa and using WireGuard or SSH with port forwarding to access my home network.  The thing is... the legacy card worked just fine for me.  I'll close this card for now, but won't give up hope for a code solution.

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.camera_front
    live_provider: go2rtc
    go2rtc:
      stream: camera_front_sub
      modes:
        - webrtc
media_viewer:
  controls:
    next_previous:
      style: none
  lazy_load: false
media_gallery:
  controls:
    filter:
      mode: right
    thumbnails:
      show_favorite_control: true
      show_download_control: true
profiles:
  - low-performance
dimensions:
  height: 350px
```
