### ISSUE TITLE
Camera expanding beyond view box when `camera.dimensions.aspect_ratio` is set

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/advanced-camera-card#2073]
**[REQUIRED] Card diagnostic information:**

I believe this is not required because the issue is reproduceable with the minimal config below. I'm on latest version 7.9.0.

**[REQUIRED] Description of problem:**

When in panel/single card dashboard layout, and when `camera.dimensions.aspect_ratio` is set, the camera is not respecting its boundaries and is expanding to outside the card.

Let's first see how it **behaves normally**:

```yaml
type: panel
path: test
title: Test
cards:
  - type: custom:advanced-camera-card
    cameras:
      - camera_entity: camera.video_porteiro
```

https://github.com/user-attachments/assets/ba1757c3-db70-4ecb-a282-391e4524b29a

All good!

Now, let's see when `camera.dimensions.aspect_ratio` is set:

```yaml
type: panel
path: test
title: Test
cards:
  - type: custom:advanced-camera-card
    cameras:
      - camera_entity: camera.video_porteiro
        dimensions:
          aspect_ratio: "16:9"
```

https://github.com/user-attachments/assets/a816da4f-833d-4bcc-89db-bc712e09a3c6

And as you can see, the camera no longer respects the view box constraints and instead expands to outside of it.

**[OPTIONAL] Last working release (if known):** N/A

**[OPTIONAL] Javascript errors shown in the web inspector:** N/A

**[OPTIONAL] Additional information:** N/A

**Comment by felipecrs** [comment]
Thanks a lot, @dermotduffy, this is working great:

https://github.com/user-attachments/assets/2c02d6c8-e75e-48f6-9127-98ab605574e3

There seems to be even a smoother animation now for the resizing.

---

However, I still noticed some unexpected behavior when `camera.dimensions.layout.fit: fill`:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.video_porteiro
    dimensions:
      aspect_ratio: "16:9"
      layout:
        fit: fill
```

https://github.com/user-attachments/assets/d00bb91d-bd87-4a82-8efc-33dfed95a80c

I believe the camera should be stretched to fill the 16:9 space, not fill the entire card. I use this feature to resize some cameras I have which are not exactly 16:9.

If users wanted the camera to fill the whole card, they'd leave the camera aspect ratio unconstrained (unset), I suppose.

Should I report as a separate issue?
