### ISSUE TITLE
Special characters in PTZ presets break PTZ controls

### ISSUE THREAD

**Issue by otaviobonder-deel** [dermotduffy/advanced-camera-card#2079]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.11.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/137.0.0.0 Safari/537.36
date: 2025-06-02T18:21:26.910Z
lang: en
timezone: America/Sao_Paulo
git:
  hash: 956a2e5
  build_date: Sun, 01 Jun 2025 00:14:46 GMT
  commit_date: Sat, 31 May 2025 17:13:39 -0700
ha_version: 2025.5.3
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      01JSAA8QJQPT34QM2M24F0498H: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.meninas
      live_provider: go2rtc
```

**[REQUIRED] Description of problem:**

I have two Tapo C500 cameras. They are configured in Frigate, and for both of them I can control the PTZ through Frigate. I added both of them to Advanced Camera Card, for one of them I can see the PTZ buttons, and they work, but for the other I can't see them, even if I set the PTZ mode to `on` to force it. Both cards have exactly the same config, and both cameras have exactly the same config in Frigate and Tapo. They are connecting through ONVIF, and they share also the same Tapo config

I've tried to delete the card and readd it a couple of times, clear cache and so on, but still I can't get PTZ to work in one of the cards.

YAML config for the cards, they are exactly the same, just changing the camera entity:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.meninas
    live_provider: go2rtc
```

**[OPTIONAL] Additional information:**

![Image](https://github.com/user-attachments/assets/36f26cce-bfef-4676-ba06-9c999e5317fe)

![Image](https://github.com/user-attachments/assets/bff7a10a-55a2-46e1-ad67-a535c7b2383b)

![Image](https://github.com/user-attachments/assets/84125ee3-9fa0-4e6e-986e-b6a6af6f67bd)
