### ISSUE TITLE
Trigget event does not work

### ISSUE THREAD

**Issue by eerison** [dermotduffy/advanced-camera-card#2082]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.11.1
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/136.0.0.0 Safari/537.36
date: 2025-06-03T09:52:23.806Z
lang: pt_BR
timezone: Europe/Berlin
git:
  hash: a3d062e
  build_date: Tue, 03 Jun 2025 03:56:19 GMT
  commit_date: Mon, 2 Jun 2025 20:55:09 -0700
ha_version: 2025.5.0
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      01JTV240QC4M0YKD6Q8XBN52CF: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.poste
      go2rtc:
        modes:
          - webrtc
          - mse
      live_provider: go2rtc
      triggers:
        entities:
          - input_boolean.poste_motion_alarm
        events:
          - snapshots
          - clips
    - camera_entity: camera.fundo_cozinha
      go2rtc:
        modes:
          - webrtc
          - mse
      live_provider: go2rtc
    - camera_entity: camera.fundo_direita
      go2rtc:
        modes:
          - webrtc
          - mse
      live_provider: go2rtc
  live:
    display:
      mode: grid
  media_gallery:
    controls:
      thumbnails:
        size: 250
  view:
    triggers:
      show_trigger_status: true
      actions:
        interaction_mode: all
```

**[REQUIRED] Description of problem:**

I am trying to take a snapshot/clip when one of my sensors active.

Note: this `input_boolean.poste_motion_alarm` is an entity helper

**Comment by eerison** [comment]
When I create an automation using `frigate.create_event`, I can see the snapshots!

**Comment by dermotduffy** [comment]
@eerison As per the [other issue](https://github.com/dermotduffy/advanced-camera-card/issues/2048#issuecomment-2934415303), I need to know how you are testing. 

Can you clarify (1) what you are doing to trigger, (2) what you expect the card to do, (3) and what you see the card actually doing? I can't tell if there's a bug, a misunderstanding or something else. Thanks!

**Comment by eerison** [comment]
Hey @dermotduffy 


1. I created a helper (input_boolean.poste_motion_alarm), to reproduce the original sensor, in other words,  it's a switch to help me to test. 
1. I expect it creates an snapshot/clip when the sensor is `on`.
1. I didn't get this question 😕

**Comment by dermotduffy** [comment]
> I expect it creates an snapshot/clip when the sensor is on.

Aha, then you are misunderstanding what this does. Triggers cause the card to take some action in _response_ to entity changes or events/clips/snapshots. They do not create a snapshot/clip.

If you want to create a Frigate event, you can use the Home Assistance service in an automation, without needing the card at all, the action would be something like:

```yaml
action: frigate.create_event
data:
  label: "My Event"
  duration: 30
  include_recording: true
```

You could also call that from a button on the card if you wanted, or add a button in the menu that does that (see the [perform-action](https://card.camera/#/configuration/actions/stock/README?id=perform-action) action, or [this example](https://card.camera/#/examples?id=menu-icons) that adds something to the menu).

This has nothing to do with triggering though.
