### ISSUE TITLE
Blue Iris cameras can be added but never show on screen - The configured camera_entity was not found

### ISSUE THREAD

**Issue by Ltek** [dermotduffy/advanced-camera-card#2098]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases). 
... on the latest as of this morning.
- Please try clearing your browser cache. 
... multiple times, tried Edge, Chrome and Android HA companion app

**[REQUIRED] Card diagnostic information:**

Please note, this is not easy to get on Windows Chrome or Edge browsers. It took me many tries to get the diagnostics to come up. Possibly since th card was 'busy' failing to render the cams?

```yaml
<html>
<body>
<!--StartFragment--><div class="nH bkK" style="overflow: hidden; -webkit-box-flex: 1; flex-grow: 1; color: rgb(32, 33, 36); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(248, 250, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="nH" style="background-color: rgba(255, 255, 255, 0.8); border-radius: 16px; margin-bottom: 16px; overflow-y: hidden;"><div class="nH ar4 z"><div class="aeI"><div class="AO" style="position: relative;"><div id=":3" class="Tm aeJ" style="background: none; overflow-y: scroll; padding-right: 0px; height: 863px;"><div id=":1" class="aeF" style="padding: 0px; vertical-align: bottom; min-height: 673.018px;"><div class="nH"><div class="nH" jsaction="uqVD7e:.CLIENT" role="main"><div class="nH g" jsaction="iE7Vzc:.CLIENT;v9KJX:.CLIENT"><div class="nH a98 iY" style="background: rgb(255, 255, 255); min-height: 64ex; min-width: 502px; position: static !important; margin: 0px; padding-right: 16px;"><div class="nH"><div class="aHU hx" style="background-color: transparent; color: rgb(34, 34, 34); min-width: 502px; padding: 0px; position: relative;"><div jslog="20686; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTgzNDQ2MDk3MDYzNTAwODgxNyJd; 4:W10." role="list"><div class="h7 ie" role="listitem" aria-expanded="true" jsaction="RUzSf:.CLIENT" tabindex="-1" style="padding-bottom: 0px; max-width: 100000px; clear: both; outline: none;"><div class="Bk" style="position: relative; margin-bottom: 0px; border-width: 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(239, 239, 239); border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-color: initial; border-radius: 0px; float: left; width: 1352.42px;"><div class="G3 G2" style="border-top: none; padding-top: 0px; background-color: transparent; border-right: 0px; border-bottom: 0px rgba(100, 121, 143, 0.12); border-left: 0px; border-image: initial; border-radius: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px;"><div><div id=":td"><div class="adn ads" data-message-id="#msg-f:1834460970635008817" data-legacy-message-id="197550888d049b31" style="border-left: none; padding: 0px; display: flex;"><div class="gs" style="margin: 0px; min-width: 0px; padding: 0px 0px 20px; width: auto;"><div class=""><div id=":th" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTgzNDQ2MDk3MDYzNTAwODgxNyJd; 4:WyIjbXNnLWY6MTgzNDQ2MDk3MDYzNTAwODgxNyIsbnVsbCxudWxsLG51bGwsMSwwLFsxLDAsMF0sMTE2LDEyMjUsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsbnVsbCxudWxsLFswXSxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCwwLDBd" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem; overflow-x: hidden;"><div id=":tg" class="a3s aiL " style="direction: ltr; font: small / 1.5 Arial, Helvetica, sans-serif; overflow: auto hidden; position: relative;"><div dir="auto"><div dir="auto">card_version: 7.13.1</div><div dir="auto">browser: &gt;-</div><div dir="auto">  Mozilla/5.0 (Linux; Android 15; SM-S911U1 Build/AP3A.240905.015.A2; wv)</div><div dir="auto">  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.61 Mobile</div><div dir="auto">  Safari/537.36 Home Assistant/2025.5.3-16170 (Android 15; SM-S911U1)</div><div dir="auto">date: 2025-06-09T14:06:38.327Z</div><div dir="auto">lang: en</div><div dir="auto">timezone: America/Denver</div><div dir="auto">git:</div><div dir="auto">  hash: f591873</div><div dir="auto">  build_date: Fri, 06 Jun 2025 21:32:00 GMT</div><div dir="auto">  commit_date: Fri, 6 Jun 2025 14:30:55 -0700</div><div dir="auto">ha_version: 2025.5.2</div><div dir="auto">custom_integrations:</div><div dir="auto">  frigate:</div><div dir="auto">    detected: false</div><div dir="auto">  hass_web_proxy:</div><div dir="auto">    detected: false</div><div dir="auto">config:</div><div dir="auto">  type: custom:advanced-camera-card</div><div dir="auto">  cameras:</div><div dir="auto">    - camera_entity: camera.front_door_live_view</div><div dir="auto">    - camera_entity: camera.driveway_cam_live_view</div><div dir="auto">    - camera_entity: camera.entry_cam_live_view</div><div dir="auto">    - camera_entity: camera.living_room_cam_live_<wbr>view</div><div dir="auto">    - live_provider: auto</div><div dir="auto">      camera_entity: camera.kitchen_living_room_<wbr>cam_live_view</div><div dir="auto">    - camera_entity: camera.large_deck_cam_live_<wbr>view</div><div dir="auto">      live_provider: auto</div><div dir="auto">    - camera_entity: camera.noahs_cam_live_view</div><div dir="auto">    - camera_entity: camera.tylers_cam_live_view</div><div dir="auto">    - camera_entity: camera.playroom_cam_live_view</div><div dir="auto">  grid_options:</div><div dir="auto">    columns: full</div><div dir="auto">    rows: 3</div><div dir="auto">  view: {}</div><div dir="auto">  status_bar:</div><div dir="auto">    style: hover-card</div><div dir="auto">  live:</div><div dir="auto">    display:</div><div dir="auto">      mode: grid</div><div dir="auto">  dimensions:</div><div dir="auto">    aspect_ratio_mode: dynamic</div></div><div class="yj6qo"></div><div class="adL"></div></div></div><div class="WhmR8e" data-hash="0" style="clear: both;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: transparent;"><div class="gB xu" jslog="184332; u014N:cOuCgd,Kr2w4b,xr6bB; 4:WyIjbXNnLWY6MTgzNDQ2MDk3MDYzNTAwODgxNyIsbnVsbCxudWxsLG51bGwsMSwwLFsxLDAsMF0sMTE2LDEyMjUsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsbnVsbCxudWxsLFswXSxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCwwLDBd" style="border-top: 0px; padding: 0px;"><div class="mVCoBd"></div><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":ti">
  | ReplyForwardAdd reaction
-- | --


</div></div></div></div></div></div></div></div></div></div><div></div></div></div><div class="nH"><div class="l2" style="margin: 0px 0px 16px; padding: 0px 16px; text-align: center; text-shadow: none; background-image: url(&quot;//ssl.gstatic.com/ui/v1/icons/mail/rfr/blank_2x.png&quot;); background-position: center center; background-repeat: no-repeat; background-size: 20px; min-height: 56px; visibility: hidden;"></div></div></div></div></div></div></div></div></div></div></div></div></div><div class="nH" style="color: rgb(32, 33, 36); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(248, 250, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aUx" jsaction="cZRHAe:.CLIENT;CyXzrf:.CLIENT" style="display: flex; height: 911.017px;"><div class="WN9Ejb buW" jsaction="oqYoCb:.CLIENT;LbSNDf:.CLIENT;ETEZVb:.CLIENT" style="--companion-shell-width: 320px; border-radius: 16px; margin-left: 16px; overflow: hidden;"><div class="brC-brG brC-aMv-bta" style="background-color: white; box-sizing: border-box; height: 911.012px; width: 320px; display: flex; -webkit-box-orient: vertical; -webkit-box-direction: normal; flex-direction: column;"><div class="brC-brG-bsf-Jz-Jw" style="height: 911.012px;"><div class="brC-brG-bsf-Jz-Jw" style="height: 911.012px;"><div class="brC-brG-bsf-Jw" style="display: flex; -webkit-box-orient: vertical; -webkit-box-direction: normal; flex-direction: column; height: 911.012px;"><div class="brB-brH brC-avC-J4-avO" role="tabpanel" aria-labelledby="gsc-gab-6" style="height: inherit; position: relative; width: 319.998px;"><div class="brB-Jz" style="height: 911.012px; left: 0px; position: absolute; top: 0px; width: 319.998px; z-index: 0;"><br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>


```

```yaml
dependencies:
  all_cameras: false
  cameras: []
triggers:
  motion: false
  occupancy: false
  entities: []
  events:
    - events
    - clips
    - snapshots
engine: auto
frigate:
  client_id: frigate
motioneye:
  images:
    directory_pattern: '%Y-%m-%d'
    file_pattern: '%H-%M-%S'
  movies:
    directory_pattern: '%Y-%m-%d'
    file_pattern: '%H-%M-%S'
reolink:
  media_resolution: low
live_provider: auto
image:
  mode: auto
  refresh_seconds: 1
ptz:
  r2c_delay_between_calls_seconds: 0.5
  c2r_delay_between_calls_seconds: 0.2
proxy:
  media: auto
  dynamic: true
  ssl_verification: auto
  ssl_ciphers: auto
always_error_if_entity_unavailable: false
camera_entity: camera.bi5_driveway_84
id: camera.bi5_driveway_84
```

**[REQUIRED] Description of problem:**

Blue Iris cameras can be added but throw an error... "The configured camera_entity was not found" and are never displayed

card YAML...

```yaml

type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.front_door_live_view
  - camera_entity: camera.bi5_driveway_84
  - camera_entity: camera.bi5_entry_82
  - camera_entity: camera.bi5_living_room_91
  - camera_entity: camera.bi5_deck_large_95
  - camera_entity: camera.bi5_noah_89
  - camera_entity: camera.bi5_tyler_88
  - camera_entity: camera.bi5_playroom_87
  - camera_entity: camera.bi5_kitchen_86
  - camera_entity: camera.bi5_kitchen_92
grid_options:
  columns: full
  rows: 3
view: {}
status_bar:
  style: hover-card
live:
  display:
    mode: grid
dimensions:
  aspect_ratio_mode: dynamic


```
