### ISSUE TITLE
Improve error recovery robustness

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/advanced-camera-card#2099]
**[REQUIRED] Describe the feature you'd like:**

To get the card working again if the connection is restored/available/back.

**[OPTIONAL] Describe alternatives you've considered:**

There are none.

**[OPTIONAL] Additional context:**

Advanced camera card can show "reconnecting" if frigate falls away and then is available again, but there's many scenario's where this is not the case, and the advanced camera card is not reconnecting without a refresh of the browser. On many automated screens and panels people are using, this is problematic. For example a screen that monitors the doorbell camera and shows it live. Or a baby camera. i have and use both.
Sometimes, advanced camera card says "unknown command". or sometimes "api not available", sometimes it shows a greyed out background of the camera and a loading icon in front of it. in all of these cases, a simple refresh solves it. Maybe it's possible to have timeout features for the card, that if one of these error messages show up, try to completely reload the stream or something? Mostly this card works well, but over the span of quite some hours and days even, these error messages always needs manual resolving from my side, and i just wish something could be done about that.

**Comment by dermotduffy** [comment]
@borgqueenx Presumably this is some momentary loss of connectivity between the browser and HA, or HA and MQTT or Frigate. Lots of moving parts. Would you mind taking a screenshot or photo of the different errors you're referring to here? I can try to see what it would take to "retry" somehow if I know which errors are problematic for you.

**Comment by borgqueenx** [comment]
Sure! This is one! Will add more when i see them. Should i enable debugging as well? Where/how can i do that as its a card, not a integration?
![Image](https://github.com/user-attachments/assets/0b4b2f78-4a89-4c1a-b1d7-29774565d650)

**Comment by neuhausf** [comment]
I have the same request: If the camera stops/restart due to a power cycle, the camera card recovers the stream.
But not on HA restarts: Then I find the same situation as described by @borgqueenx : The card shows "Unknown command". When I change views and come back to the dashboard, the stream works again.
I'm using the card on a Android Tablet with installed HA app.

A simple (?) retry would really help in this case!

**Comment by borgqueenx** [comment]
Any update if this is planned or not?

**Comment by dermotduffy** [comment]
> Any update if this is planned or not?

Every open issue is planned ... eventually. It's just a matter of prioritization and "thumbs up"ing. Feel free to [help](https://github.com/dermotduffy/advanced-camera-card/issues/1248) if you'd rather not wait. Sorry I don't have a better answer.

**Comment by borgqueenx** [comment]
> > Any update if this is planned or not?
> 
> Every open issue is planned ... eventually. It's just a matter of prioritization and "thumbs up"ing. Feel free to [help](https://github.com/dermotduffy/advanced-camera-card/issues/1248) if you'd rather not wait. Sorry I don't have a better answer.

Appriciate the response and development!

**Comment by PecceG2** [comment]
I’d like to add my support to improve this proposal. We have several installations experiencing the same issue: when Home Assistant is updated (and restarted), the dashboard gets stuck on “Connection lost, reconnecting...”. Then it reconnects and fully reloads the dashboard, but the only card that does not sync correctly and remains broken with “Unknown command” is this one.

It would be ideal if, upon receiving the “Unknown command” error, it would retry reloading the camera every 5 seconds (or similar), or as mentioned above, include a “Reload” button.

**Comment by dermotduffy** [comment]
@PecceG2 If you're up for it, try the [v8 release candidate](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v8.0.0-rc.2). It includes changes that should help with this. Otherwise, hang tight until the release branch makes it to the stable release.

**Comment by PecceG2** [comment]
Hi @dermotduffy ! How are you?

I tested installing version v8.0.0-rc.2 in two of my environments, and the issue is still happening.
After installing that version, I also cleared the browser cache to make sure it wasn’t related to stale frontend files.

When a dashboard is already loaded with the cameras working and Home Assistant is restarted, the card switches to "Reconnecting...". Then, as soon as HASS finishes starting up, it changes to an error saying: "Camera initialization failed: Unknown command. Check troubleshooting."
<img width="504" height="285" alt="Image" src="https://github.com/user-attachments/assets/d1244772-f345-4afe-b063-51b366a0c4fe" />

After that, the dashboard stays stuck on that error and does not recover until the page is manually reloaded.

I'm willing to submit a PR if you think it makes sense. What do you think about adding a "Reload" button to the error state so we can at least reload the card and reinitialize it manually?

**Comment by dermotduffy** [comment]
@PecceG2 (From mobile, pardon typos) From one of the failed instances can you fetch the card diagnostics (hold down the main Iris menu button for a few seconds). Should that not work, at least verify the version number that flashes up in the center of the card is v8 and not v7. Proper response later!

**Comment by PecceG2** [comment]
@dermotduffy I definitely had an outdated version of the card, and reinstalling it from HACS had left me with a duplicated folder using the card’s previous name.
I cleaned everything up, reinstalled it again in one of the environments, and we’ve now confirmed that the version matches the one you mentioned (8.0.0-rc.2), but unfortunately the issue still persists.

I’m attaching both the debug logs and a video showing exactly what happens so we have more context.

Previous:
```
card_version: 6.5.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/148.0.0.0 Safari/537.36
date: 2026-05-28T13:13:31.380Z
lang: en
timezone: America/Buenos_Aires
git:
  hash: 43947b4
  build_date: Sun, 02 Feb 2025 00:09:40 GMT
  commit_date: Sat, 1 Feb 2025 16:08:32 -0800
ha_version: 2026.4.4
```

Now:
```
card_version: 8.0.0-rc.2
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/148.0.0.0 Safari/537.36
date: 2026-05-28T13:33:25.949Z
lang: en
timezone: America/Buenos_Aires
git:
  hash: ebe6b2f
  build_date: Mon, 09 Mar 2026 04:06:56 GMT
  commit_date: Sun, 8 Mar 2026 21:00:54 -0700
ha_version: 2026.4.4
custom_integrations:
  frigate:
    detected: true
    version: 5.15.3
    devices:
      xxxxx: 5.15.3/0.17.0-f0d69f7
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.ext1
      cast: {}
  view:
    default: live
    triggers: {}
    default_cycle_camera: false
  live:
    zoomable: true
    controls:
      builtin: false
  cameras_global:
    dimensions:
      layout:
        position:
          'y': 68
  dimensions:
    aspect_ratio_mode: dynamic
  image:
    mode: screensaver
  media_gallery:
    controls:
      thumbnails:
        size: 114
        show_details: true
        show_favorite_control: false
        show_timeline_control: false
        show_download_control: false
  menu:
    style: hidden
    alignment: right
    buttons:
      media_player:
        enabled: false
      timeline:
        enabled: false
  timeline: {}
  profiles:
    - casting
  performance:
    features:
      animated_progress_indicator: true
      card_loading_indicator: true
```

Video:
https://www.youtube.com/watch?v=rModvN6sxB0
