### ISSUE TITLE
Issues with camera triggering on startup

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/advanced-camera-card#2103]
Hi @dermotduffy — it's me again (the one who opened issue [#2087](https://github.com/your-repo/issues/2087), from which this awesome new feature originated)!

First of all, I just want to say: **incredible work in such a short amount of time — truly impressive**. Kudos for your effort and responsiveness!

That said, while testing the new feature, I think I’ve encountered **two potential bugs**. I’ve detailed both below with minimal test configurations to reproduce them.

---

<details>
<summary>⚠️ 1. Triggered camera doesn’t reset if entity goes off while card is not active</summary>

**Description:**  
When a camera is triggered, it correctly becomes active. However, if I leave the view (i.e., navigate away from the card) and the triggering entity turns off **while I’m away**, then upon returning to the card **without a page refresh**, the camera remains stuck in the triggered state. As a result, it won’t switch to another camera when a new trigger occurs, because it thinks the previous one is still active.

**Test configuration:**
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.ingresso_pt
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://127.0.0.1:8555/ingresso_pt
    triggers:
      motion: false
      occupancy: false
      events: []
      entities:
        - binary_sensor.frigate_mostra_telecamera_ingresso_pt
    go2rtc:
      modes: []
view:
  triggers:
    show_trigger_status: true
```
</details>

---

<details>
<summary>⚠️ 2. Error loading substream when using <code>view-triggers-action-trigger: live</code></summary>

**Description:**  
When using a camera setup with a substream and setting the trigger action to `live`, the card crashes **if** the trigger entity is activated **before** the card is opened. It throws the following error:

> _The selected camera does not support this view._  
> [Check problem resolution](https://card.camera/#/troubleshooting)  
> `view: live`  
> `camera: ingresso_pt`  
> `camera_capabilities:`  
> `  substream: true`

**Test configuration:**
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.ingresso_pt
    live_provider: webrtc-card
    dependencies:
      cameras:
        - ingresso_pt
    webrtc_card:
      url: rtsp://127.0.0.1:8555/ingresso_pt_sub_1
    triggers:
      motion: false
      occupancy: false
      events: []
      entities:
        - binary_sensor.frigate_mostra_telecamera_ingresso_pt
    go2rtc:
      modes: []
  - camera_entity: camera.ingresso_pt
    id: ingresso_pt
    capabilities:
      disable_except:
        - substream
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://127.0.0.1:8555/ingresso_pt
    triggers:
      motion: false
      occupancy: false
      events: []
      entities:
        - binary_sensor.frigate_mostra_telecamera_ingresso_pt
    go2rtc:
      modes: []
view:
  triggers:
    show_trigger_status: true
    actions:
      trigger: live
```
</details>

---

Let me know if you’d like me to open these as separate issues. Happy to provide logs or video captures if needed. Thanks again for all the great work!

_Originally posted by @Trexano99 in https://github.com/dermotduffy/advanced-camera-card/issues/2095#issuecomment-2960699430_
