### ISSUE TITLE
PTZ controls overlap audio controls

### ISSUE THREAD

**Issue by aik** [dermotduffy/advanced-camera-card#2104]
**[REQUIRED] Card diagnostic information:**
```
card_version: 7.14.1
browser: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
date: 2025-06-12T01:26:58.245Z
lang: en
timezone: Australia/Sydney
git:
  hash: 1bbc5be
  build_date: Mon, 09 Jun 2025 00:02:24 GMT
  commit_date: Sun, 8 Jun 2025 17:01:13 -0700
ha_version: 2025.5.3
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      01JT6166A4JQ60H4PND3EB8Z1E: 5.9.2/0.16.0-1fa7ce5
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.driveway_2
  performance:
    features:
      card_loading_indicator: false
      animated_progress_indicator: false
    style:
      border_radius: false
      box_shadow: false
  menu:
    buttons:
      mute:
        enabled: true
      media_player:
        enabled: false
```

**[REQUIRED] Description of problem:**

Cannot easily enable audio and adjust the volume because there are PTZ controls overlapping the bottom bar.

**[OPTIONAL] Additional information:**

![Image](https://github.com/user-attachments/assets/960bb9b6-63d8-4f84-9572-dee33cd969c2)
