### ISSUE TITLE
Add timeline support for folders

### ISSUE THREAD

**Issue by suside** [dermotduffy/advanced-camera-card#2106]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases). ✅
- Please try clearing your browser cache. ✅

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 7.14.1
browser: >-
  Mozilla/5.0 (Linux; Android 15; Pixel 7a Build/BP1A.250505.005.B1; wv)
  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.89 Mobile
  Safari/537.36 Home Assistant/2025.5.3-16170 (Android 15; Pixel 7a)
date: 2025-06-16T14:07:20.560Z
lang: pl
timezone: Europe/Warsaw
git:
  hash: 1bbc5be
  build_date: Mon, 09 Jun 2025 00:02:24 GMT
  commit_date: Sun, 8 Jun 2025 17:01:13 -0700
ha_version: 2025.6.1
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.[redacted]
      reolink:
        media_resolution: high
        url: https://192.168.[redacted]/
  folders:
    - type: ha
      ha:
        url: >-
          /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/[redacted]
        path:
          - {}
          - {}
          - {}
          - parsers:
              - type: date
                regexp: \d{14}
                format: yyyyMMddHHmmss
  view_layout:
    position: main
  status_bar:
    position: bottom
    style: outside

```

**[REQUIRED] Description of problem:**

After setting up the parsers I can see that folder files have correct metadata (from Reolink FTP upload path in the format of `yyyy/MM/dd/Cameraname_00_yyyyMMddHHmmss.mp4`):

![Image](https://github.com/user-attachments/assets/a9ea7faf-30a4-4e0d-b5d3-a8eb17a23c0c)

However if I click "See media in timeline" crosshair icon the timeline is empty, if I go to timeline directly it's empty as well (even if zoomed out):

![Image](https://github.com/user-attachments/assets/6b250b72-1c83-4f7c-925e-2e52ece5ac38)

I can play the mp4 files without any problems but only through folders icon.

**[OPTIONAL] Last working release (if known):**
None

**[OPTIONAL] Javascript errors shown in the web inspector:**
In the timeline there is no errors but when I go to "Clips gallery" I get "No media to display" and

```text
scoped-custom-element-registry.ts:684 Uncaught TypeError: Cannot set property registry of #<ShadowRoot> which has only a getter
    at Element.attachShadow (scoped-custom-element-registry.ts:684:47)
    at ao.createRenderRoot (gallery-core-e7dd2751.js:6:294)
    at ao.connectedCallback (card-855fd26e.js:12:3150)
    at ao.connectedCallback (card-855fd26e.js:24:586)
    at t.connectedCallback (scoped-custom-element-registry.ts:424:40)
    at ee.S (card-855fd26e.js:18:4200)
    at ee.T (card-855fd26e.js:18:4274)
    at ee.$ (card-855fd26e.js:18:4619)
    at ee._$AI (card-855fd26e.js:18:4058)
    at card-855fd26e.js:24:510
```

Perhaps I misunderstood something and parsed metadata is not enough to have timeline/Clips gallery visible?
