### ISSUE TITLE
Regular black-out when viewing live stream

### ISSUE THREAD

**Issue by webjib** [dermotduffy/advanced-camera-card#2108]
** Card diagnostic information:**

```yaml
card_version: 7.14.1
browser: >-
  Mozilla/5.0 (iPhone; CPU iPhone OS 19_0 like Mac OS X) AppleWebKit/605.1.15
  (KHTML, like Gecko) Home Assistant/2025.5 (io.robbie.HomeAssistant;
  build:2025.1264; iOS 19.0.0) Mobile/HomeAssistant, like Safari
date: 2025-06-18T11:01:17.996Z
lang: en
timezone: Europe/Paris
git:
  hash: 1bbc5be
  build_date: Mon, 09 Jun 2025 00:02:24 GMT
  commit_date: Sun, 8 Jun 2025 17:01:13 -0700
ha_version: 2025.6.1
```

**[REQUIRED] Description of problem:**

On a regular basis (less than every minute), the live stream black-outs, even when not touching the screen (iOS mobile) or doing something particular (desktop). Most of the times, stream comes back in a few seconds, but sometimes it gets locked on the black screen. This issue has been there for a long time.

I can confirm that the live view in Frigate UI does not suffer from the same issue. 

Do you know how I can debug what's happening and causing this black out?

Here is a GIF of the issue:

![Image](https://github.com/user-attachments/assets/fdefeb5f-ff8d-4b5b-bfb5-1d623c211453)

**Comment by sulsa** [comment]
I have the same problem. Figure out how to fix this @webjib ?

**Comment by dermotduffy** [comment]
Huh, weird. Can you include your card config? Have you tried other live providers? If you just open the same camera stream in HA outside the card (assuming you're using `auto` or `ha` live providers), do you get the same thing?

**Comment by exchange321** [comment]
I'm having this issue too, albeit a bit more severe that my stream doesn't load at all. The following is my config:
```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.front_left
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: front_left_sub
```
The stream works fine when testing in go2rtc page (both webrtc and mse), but in the HA card, it's just blank, regardless of the mode:

<img width="426" height="319" alt="Image" src="https://github.com/user-attachments/assets/b479f60c-0f37-4750-8fc0-be9c03ffa874" />

This is my diagnostic info in case it helps:
```
card_version: 7.17.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
date: 2025-09-10T08:02:10.874Z
lang: en
timezone: Australia/Brisbane
ha_version: 2025.8.3
```
