### ISSUE TITLE
Video doesn't fit the sceen since 7.13.0 version

### ISSUE THREAD

**Issue by rodrigogbs** [dermotduffy/advanced-camera-card#2109]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/advanced-camera-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.14.1
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/137.0.0.0 Safari/537.36
date: 2025-06-20T10:49:33.995Z
lang: en
timezone: America/Sao_Paulo
git:
  hash: 1bbc5be
  build_date: Mon, 09 Jun 2025 00:02:24 GMT
  commit_date: Sun, 8 Jun 2025 17:01:13 -0700
ha_version: 2025.6.1
custom_integrations:
  frigate:
    detected: true
    version: 5.9.2
    devices:
      cee7ac4fb67469c51378ba6125fdd730: 5.9.2/0.15.0-6cb5cfb
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  microphone:
    always_connected: false
    disconnect_seconds: 1
  cameras:
    - webrtc_card:
        url: my_rtsp_url
      camera_entity: camera.lavanderia
  view:
    default: live
    default_reset:
      every_seconds: 5
  menu:
    buttons:
      fullscreen: {}
      microphone:
        enabled: true
      camera_ui:
        enabled: false
      frigate:
        enabled: false
      substreams:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      timeline:
        enabled: true
      media_player:
        enabled: false
      cameras:
        enabled: false
    style: outside
    position: top
    button_size: 30
    alignment: left
  live:
    preload: true
    controls:
      ptz:
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 130px
  elements:
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:menu
      items:
        - title: Privacy
          icon: mdi:eye-outline
          entity: switch.camera_lavanderia_privacy
          tap_action:
            action: toggle
        - title: Reboot
          icon: mdi:power
          entity: button.camera_lavanderia_reboot
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_lavanderia_reboot
            perform_action: button.press
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:cursor-move
      items:
        - title: Move UP
          icon: mdi:arrow-up
          entity: button.camera_lavanderia_move_up
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_lavanderia_move_up
            perform_action: button.press
        - title: Move DOWN
          icon: mdi:arrow-down
          entity: button.camera_lavanderia_move_down
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_lavanderia_move_down
            perform_action: button.press
        - title: Move LEFT
          icon: mdi:arrow-left
          entity: button.camera_lavanderia_move_left
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_lavanderia_move_left
            perform_action: button.press
        - title: Move RIGHT
          icon: mdi:arrow-right
          entity: button.camera_lavanderia_move_right
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_lavanderia_move_right
            perform_action: button.press
  cameras_global:
    webrtc_card:
      background: true
    ptz:
      data_left:
        entity_id: button.camera_lavanderia_move_left
      data_right:
        entity_id: button.camera_lavanderia_move_right
      data_up:
        entity_id: button.camera_lavanderia_move_up
      data_down:
        entity_id: button.camera_lavanderia_move_down
      service: button.press
```

**[REQUIRED] Description of problem:**

After upgrading to 7.13.0+ the video doesn't fit the card anymore, as used to happen until 7.12.0 version.

7.12.0:

<img width="397" alt="Image" src="https://github.com/user-attachments/assets/2fe4e471-4139-4010-b265-c1698b8dbf69" />

7.14.1:

<img width="397" alt="Image" src="https://github.com/user-attachments/assets/4b3f29e8-43e8-4902-8472-2ac2c5c641d3" />

**[OPTIONAL] Last working release (if known):**
7.12.0

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
I suspect this has already been fixed in the latest versions. Please re-open if I'm mistaken.

**Comment by rodrigogbs** [comment]
@dermotduffy I tried on all versions above 7.12.0 and the problem persists:

<img width="1204" height="2367" alt="Image" src="https://github.com/user-attachments/assets/575c1227-22b0-402d-a579-cf8dfaa3eede" />

If I enter in fullscreen mode and return, it fits the whole card, but refreshing the screen, the problem starts happening again.

**Comment by rodrigogbs** [comment]
I tried but I can't repoen the issue, maybe because you closed it as duplicate.

**Comment by dermotduffy** [comment]
@rodrigogbs Just to confirm, have you updated to the very latest [v7.16.0](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.16.0)? Your diagnostics post is still from an older version. Make sure when the card loads it is showing at least `v7.16.0`.

**Comment by rodrigogbs** [comment]
> @rodrigogbs Just to confirm, have you updated to the very latest [v7.16.0](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.16.0)? Your diagnostics post is still from an older version. Make sure when the card loads it is showing at least `v7.16.0`.

Yeah, the last scenario described is related to 7.16.0 version.

**Comment by felipecrs** [comment]
I don't see any configuration related to dimensions or layout in your example.

@dermotduffy if the version bisect is correct, the only PR that could have caused it is https://github.com/dermotduffy/advanced-camera-card/pull/2088, which seems weird.

@rodrigogbs do you confirm that it works with 7.12.0 and breaks after updating to **7.13.0**?

**Comment by rodrigogbs** [comment]
> I don't see any configuration related to dimensions or layout in your example.
> 
> @dermotduffy if the version bisect is correct, the only PR that could have caused it is https://github.com/dermotduffy/advanced-camera-card/pull/2088, which seems weird.
> 
> @rodrigogbs do you confirm that it works with 7.12.0 and breaks after updating to **7.13.0**?

Exactly.

**Comment by dermotduffy** [comment]
It is extremely unlikely that PR is causing this problem. It's more likely you're not running the version you think you are :-)

@rodrigogbs Can you open your development console (often F12) and find the version number printed there, it will look something like this:

<img width="211" height="21" alt="Image" src="https://github.com/user-attachments/assets/8dd5756d-7479-4181-b021-98761c4ecf9f" />

If you're not running the version you think you are, you may [suffer from this issue](https://card.camera/#/troubleshooting?id=duplicate-versions-duplicate-element-registrations-custom-element-not-found-advanced-camera-card).

**Comment by rodrigogbs** [comment]
> It is extremely unlikely that PR is causing this problem. It's more likely you're not running the version you think you are :-)
> 
> [@rodrigogbs](https://github.com/rodrigogbs) Can you open your development console (often F12) and find the version number printed there, it will look something like this:
> 
> <img alt="Image" width="211" height="21" src="https://private-user-images.githubusercontent.com/1136829/484324186-8dd5756d-7479-4181-b021-98761c4ecf9f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY4MTUxMTYsIm5iZiI6MTc1NjgxNDgxNiwicGF0aCI6Ii8xMTM2ODI5LzQ4NDMyNDE4Ni04ZGQ1NzU2ZC03NDc5LTQxODEtYjAyMS05ODc2MWM0ZWNmOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDJUMTIwNjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDgzZGNmMWE4ZWM2MzQ2MGI4ZTA1ZDU3YmRjYzI5MTU3Yzc1NDMwNTc1OGZiZjQ1MTEyZDAyZmE4ZWU0NzIzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5AK_6JPEl1LMfcHxm118NFlGCIJPWFus1rGOzoblccc">
> If you're not running the version you think you are, you may [suffer from this issue](https://card.camera/#/troubleshooting?id=duplicate-versions-duplicate-element-registrations-custom-element-not-found-advanced-camera-card).


--> 7.17.0

<img width="717" height="26" alt="Image" src="https://github.com/user-attachments/assets/f2f77447-3c97-4741-a079-4ab5dbb5d317" />

```
Card diagnostics. Please review for confidential information prior to sharing
card_version: 7.17.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/139.0.0.0 Safari/537.36
date: 2025-09-02T12:06:39.293Z
lang: en
timezone: America/Sao_Paulo
git:
  hash: 6b656b1
  build_date: Mon, 01 Sep 2025 23:15:28 GMT
  commit_date: Mon, 1 Sep 2025 16:14:30 -0700
ha_version: 2025.8.3
custom_integrations:
  frigate:
    detected: true
    version: 5.9.4
    devices:
      cee7ac4fb67469c51378ba6125fdd730: 5.9.4/0.15.2-3bda638
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  microphone:
    always_connected: false
    disconnect_seconds: 1
  cameras:
    - webrtc_card:
        url: >-
          rtsp://user:pass@192.168.68.150:554/stream2
      camera_entity: camera.cozinha
  view:
    default: live
    default_reset:
      every_seconds: 5
  dimensions:
    layout:
      fit: fill
      aspect_ratio_mode: dynamic
      aspect_ratio: '4:3'
      height: auto
  menu:
    buttons:
      fullscreen: {}
      microphone:
        enabled: true
      camera_ui:
        enabled: false
      frigate:
        enabled: false
      substreams:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      timeline:
        enabled: true
      media_player:
        enabled: false
      cameras:
        enabled: false
    style: outside
    position: top
    button_size: 30
    alignment: left
  live:
    preload: true
    controls:
      ptz:
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 130px
  elements:
    - type: conditional
      conditions:
        - condition: state
          entity: input_boolean.camera_cozinha_privacy_mode
          state: 'on'
          state_not: 'off'
      elements:
        - type: image
          entity: input_boolean.camera_cozinha_privacy_mode
          state_image:
            'on': /local/privacy14.png
          state_filter:
            'on': brightness(80%)
          style:
            left: 100px
            top: 180px
            height: 290px
            width: 820px
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:menu
      items:
        - title: Privacy Mode
          icon: mdi:eye-outline
          entity: input_boolean.camera_cozinha_privacy_mode
          tap_action:
            action: toggle
        - title: Privacy Tapo
          icon: mdi:eye-outline
          entity: switch.camera_cozinha_privacy
          tap_action:
            action: toggle
        - title: Reboot
          icon: mdi:power
          entity: button.camera_cozinha_reboot
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_cozinha_reboot
            perform_action: button.press
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:arrow-up-down
      items:
        - title: Move UP
          icon: mdi:arrow-up
          entity: button.camera_cozinha_move_up
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_cozinha_move_up
            perform_action: button.press
        - title: Move DOWN
          icon: mdi:arrow-down
          entity: button.camera_cozinha_move_down
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_cozinha_move_down
            perform_action: button.press
    - type: custom:advanced-camera-card-menu-submenu
      icon: mdi:arrow-left-right
      items:
        - title: Move LEFT
          icon: mdi:arrow-left
          entity: button.camera_cozinha_move_left
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_cozinha_move_left
            perform_action: button.press
        - title: Move RIGHT
          icon: mdi:arrow-right
          entity: button.camera_cozinha_move_right
          tap_action:
            action: perform-action
            data:
              entity_id: button.camera_cozinha_move_right
            perform_action: button.press
  cameras_global:
    webrtc_card:
      background: true
    ptz:
      data_left:
        entity_id: button.camera_cozinha_move_left
      data_right:
        entity_id: button.camera_cozinha_move_right
      data_up:
        entity_id: button.camera_cozinha_move_up
      data_down:
        entity_id: button.camera_cozinha_move_down
      service: button.press
```

<img width="844" height="801" alt="Image" src="https://github.com/user-attachments/assets/7c1d46fd-ae13-4993-844b-a0fd39241b88" />

<img width="844" height="801" alt="Image" src="https://github.com/user-attachments/assets/5c42cc26-5dc9-4da0-b726-10943cfa7b77" />


--> 7.12.0

<img width="712" height="29" alt="Image" src="https://github.com/user-attachments/assets/23362856-c5a4-482d-a485-0e05e341ca2c" />

<img width="864" height="803" alt="Image" src="https://github.com/user-attachments/assets/31d084a5-c802-42d7-a7cb-91d45419da0d" />

<img width="864" height="803" alt="Image" src="https://github.com/user-attachments/assets/2b13f9cb-ae2f-4679-a433-88ec9f662349" />
