### ISSUE TITLE
Allow grid to scale itself to only within available space

### ISSUE THREAD

**Issue by Ltek** [dermotduffy/advanced-camera-card#2110]
I've done a lot of testing with different YAML. I could not find any way to have ACC simultaneously scale both rows and columns to fill/fit the full display resolution / dimensions. 

Seems the Advanced Camera Card's internal grid does not allow for this?

I tried CSS mod-card and multiple Layout Card wrappers but they have no influence on the ACC's grid.  Layout card's Panel type allows the ACC card itself to expand to the screen width, but not the height.

ACC is an awesome card so surprised it either does not have an easy way to automatically fill the screen limits without requiring hard set parameters in Layout cards.

I'm using two separate YAMLs for now but would like to have a single YAML to rule them all. :)

Landscape...

```
type: panel
path: ""
cards:
  - type: custom:advanced-camera-card
    cameras:
      - camera_entity: camera.front_door_live_view
      - camera_entity: camera.bi5_driveway_84
      - camera_entity: camera.bi5_entry_82
      - camera_entity: camera.bi5_living_room_91
      - camera_entity: camera.bi5_deck_large_95
      - camera_entity: camera.bi5_89
      - camera_entity: camera.bi5_88
      - camera_entity: camera.bi5_playroom_87
      - camera_entity: camera.bi5_kitchen_86
      - camera_entity: camera.bi5_kitchen_92
      - camera_entity: camera.bi5_patio_83
    live:
      display:
        mode: grid
        grid_columns: 5
    status_bar:
      style: hover-card
    dimensions:
      aspect_ratio_mode: dynamic
title: Cams wide



```

Portrait...

```
type: custom:vertical-layout
title: cameras
path: cameras
icon: mdi:cctv
cards:
  - type: custom:advanced-camera-card
    cameras:
      - camera_entity: camera.front_door_live_view
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_driveway_84
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_entry_82
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_patio_83
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_deck_large_95
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_living_room_91
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_89
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_88
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_playroom_87
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_kitchen_86
        double_tap_action:
          action: more-info
      - camera_entity: camera.bi5_kitchen_92
        double_tap_action: more-info
    view: {}
    live:
      display:
        mode: grid
        grid_columns: 2
        reflow: true
    dimensions:
      aspect_ratio_mode: dynamic
    menu:
      position: top
      buttons:
        screenshot:
          enabled: true
        play:
          enabled: true

```
