### ISSUE TITLE
Advanced Camera Card Unknown error after few seconds of stream

### ISSUE THREAD

**Issue by iwanpot** [dermotduffy/advanced-camera-card#2112]
Running latest version 7.14.1
Browser cache cleared on multiple devices.
Running latest version of HA: 2025.6.3

**[REQUIRED] Card diagnostic information:**
```
card_version: 7.14.1
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0
date: 2025-06-24T21:12:27.091Z
lang: en
timezone: Europe/Belgrade
git:
  hash: 1bbc5be
  build_date: Mon, 09 Jun 2025 00:02:24 GMT
  commit_date: Sun, 8 Jun 2025 17:01:13 -0700
ha_version: 2025.6.3
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:advanced-camera-card
  cameras:
    - camera_entity: camera.zvono_fluent
      live_provider: ha
      webrtc_card:
        entity: camera.zvono_fluent
```

Description of problem:

On page refresh card loads and display's stream from camera for 3-4 seconds after which error is displayed on the card. On another page reload camera feed is again visible for 3-4 seconds and error is displayed again.

Camera operates normally within HA and stream is visible without any issues when not using Advanced Camera Card. 

```
Failed to receive response from Home Assistant for request . [Check troubleshooting](https://card.camera/#/troubleshooting)
request:
  type: media_source/browse_media
  media_content_id: media-source://reolink/RES|01J91NG9YCKMV37FPWQ0ECW9EQ|0|sub
  id: 50
response:
  code: unknown_error
  message: Unknown error
```

Last working release (if known): card_version: 7.14.1 / HA version

Additional error from HA when Advanced Camera Card is loaded in browser:
The error from the following log repeats on each reload of dashboard where Advanced Camera Card is deployed:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/reolink/media_source.py:336
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:03:18 (14 occurrences)
Last logged: 23:14:43

[547403212864] Error handling message: Unknown error (unknown_error) Ivan from 192.168.0.251 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0)
[547403073312] Error handling message: Unknown error (unknown_error) Ivan from 192.168.0.251 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0)
[547343149600] Error handling message: Unknown error (unknown_error) Ivan from 192.168.0.251 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0)
[547403207104] Error handling message: Unknown error (unknown_error) Ivan from 192.168.0.251 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0)
[547395571840] Error handling message: Unknown error (unknown_error) Ivan from 192.168.0.251 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 203, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id", ""))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 137, in async_browse_media
    item = await _get_media_item(hass, media_content_id, None).async_browse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 79, in async_browse
    return await self.async_media_source().async_browse_media(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/reolink/media_source.py", line 135, in async_browse_media
    return await self._async_generate_camera_days(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        config_entry_id, int(channel_str), stream
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/reolink/media_source.py", line 336, in _async_generate_camera_days
    statuses, _ = await host.api.request_vod_files(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        channel, start, end, status_only=True, stream=stream
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/reolink_aio/api.py", line 5419, in request_vod_files
    raise ApiError(f"Host: {self._host}:{self._port}: Request VOD files: API returned error code {data.get('code', -1)}, response: {json_data}")
reolink_aio.exceptions.ApiError: Host: 192.168.0.161:443: Request VOD files: API returned error code 1, response: [{'cmd': 'Search', 'code': 1, 'error': {'detail': 'rcv failed', 'rspCode': -17}}]
```

Additional information:
- Attempted rollback of HA to previous working version of Advanced Camera Card: issue persists
- All traces of former frigate card are removed from both Resources and 
- Attempted on clean dashboard where there is no other card.
- Reolink integration is working without issues, fully displaying the stream.
- Attempted from multiple different devices to confirm the error is not localized on single device.

**Comment by dermotduffy** [comment]
The issue is almost certainly not related to the stream, but to the card trying to fetch you Reolink media (for thumbnails / event viewing). You could test by disabling thumbnails temporarily on the live stream and see if that works:

```yaml
live:
  controls:
    thumbnails:
      mode: none
```

Assuming it does, my next question would be whether or not Reolink media works in HA but outside of the card -- if you use the 'Media' sidebar in Home Assistant, can you navigate down into media for the camera you are trying to use with the card? My guess is you have some issue with your Reolink integration and/or camera that is causing media fetching to fail. That's likely not actually related to the card -- but if it works fine via the HA media browser, but not in the card, then I'd change that assessment :-)

**Comment by iwanpot** [comment]
Thank you for the reply, i can confirm that camera feed works outside of Advanced Camera card, and works from the Reolink integration itself in HA.

![Image](https://github.com/user-attachments/assets/97f9af21-04bb-47d8-a57d-e44cb873d6a7)

**Comment by dermotduffy** [comment]
> Thank you for the reply, i can confirm that camera feed works outside of Advanced Camera card, and works from the Reolink integration itself in HA.

That wasn't the question, though ;-)

Please answer these questions:
 
- Does the temporary YAML workaround I described cause the card to load the stream correctly? (i.e. workaround this issue)
- Do media playbacks for this same camera work correctly via the HA media browser ("Media" is the item in the sidebar, can you navigate to this camera and play back media items without any error)?

**Comment by iwanpot** [comment]
Apologies :)
Tested the workaround you described and with it it works like a charm :).
Media playback for this camera work correctly via the HA media browser, it did not have any issues/errors.
Thank you so much!

**Comment by dermotduffy** [comment]
> Tested the workaround you described and with it it works like a charm :).

Great.

> Media playback for this camera work correctly via the HA media browser, it did not have any issues/errors.

Hmm. OK. Is this camera connected via a Reolink NVR? If so, you might try setting the channel value as perhaps that's causing the issue, try this (you'd need to disable the workaround I just gave you to test, of course):

```yaml
  cameras:
    - camera_entity: camera.zvono_fluent
      live_provider: ha
      reolink:
        channel: 0 <------ Try a variety of different small integer values here, each number should map to a different camera, see if you can get a value that works. If you have 5 cameras, usually the value would be 0-5 .
```
