### ISSUE TITLE
Two-Way Audio with WebRTC Card Live-Provider

### ISSUE THREAD

**Issue by dzlandis** [dermotduffy/advanced-camera-card#2116]
This is what my configuration looks like (at least the relevant part):
```yaml
type: custom:advanced-camera-card
cameras:
  - live_provider: webrtc-card
    webrtc_card:
      entity: camera.camera
      media: video,audio,microphone
```

With this configuration, I am able to get the card to correctly request for microphone permission. The problem is that no microphone toggle appears so I have no way to actually control the microphone function and it just stays on for forever. I've tried enabling the microphone button but no toggle button appears on the card. Also worth noting that I think under the hood, the webrtc-card is using go2rtc. Any help is greatly appreciated.
