### ISSUE TITLE
Single camera works, multiple cameras show me an error

### ISSUE THREAD

**Issue by selmaohneh** [dermotduffy/advanced-camera-card#636]
I am trying to integrate a second camera. But I can't get the config to work ...

* Using each camera standalone using the `camera_entity` syntax works like a charm.
* As soon as I try to add multiple cameras using the `cameras:` syntax, I get an error that the camera_entity and/or the camera_name needs to be specified - which I thought I did.

What am I doing wrong?

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.backyard
  - camera_entity: camera.frontyard
view:
  default: snapshots
menu:
  buttons:
    frigate: false
```

**Comment by dermotduffy** [comment]
Can you paste in the text of the config (not screenshot) for the multiple cameras, and a screenshot of the error you receive. The second syntax in your screenshot looks right, as long as you're using at least v3 of the card.

**Comment by selmaohneh** [comment]
* Edited the issue to now contain the text.
* Just did the update to v3. Restarted the server.
* Same issue.

Here is the screenshot:
 
![image](https://user-images.githubusercontent.com/29881939/172423534-ef42f06c-964a-49b6-a5cd-ce7fb7336376.png)

**Comment by dermotduffy** [comment]
Are you using a recent Frigate integration version? Latest is 2.3. Are they definitely Frigate camera entities (i.e. when you navigate to the Frigate integration in settings, do those entities show up?). The camera name auto detection only works for native Frigate cameras.

**Comment by dermotduffy** [comment]
If you just installed card v3, also make sure to flush your cache. (e.g. try it in an incognito window and see if you get the same result)

**Comment by selmaohneh** [comment]
* I am using Frigate v2.3.
* The entities are definitely Frigate camera entities, just checked.
* Flushing the cache was a good point. Did that and tried the incognito mode. Result: The error is gone.
* But: Only the snapshots of the first camera get shown. So my config still seems to be wrong, i.e. the second camera gets ignored.
* Further ideas? Thanks already!

**Comment by dermotduffy** [comment]
Can you change to the second camera via the camera selector button? What happens if you change to the second camera, and then click the snapshots or clips button?

**Comment by selmaohneh** [comment]
I enabled the frigate button and swapped the order of both cameras in the config:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.frontyard
  - camera_entity: camera.backyard
view:
  default: snapshots
menu:
  buttons:
    frigate: true
```

Now only the snapshots of the frontyard camera get shown. So in conclusion only the snapshots of the camera mentioned first in the config get shown.

I am able to swap between the cameras via the Frigate / Select camera button though. I can view the snapshots of both cameras seperatley that way - but still not merged. :-/
